import {GALA_KEY,loadGala} from './identity.mjs';
export const MELEE=new Set(['rapier','greatsword','dagger','spear','trident','scythe','gauntlets']);
export function equipmentProgress(value={}){return {activeDays:Math.max(0,Number(value.activeDays)||0),totalXp:Math.max(0,Number(value.activeDays)||0)*100,strength:1+Math.floor(Math.max(0,Number(value.completedSets)||0)/4)};}
export function initRestArena(){
 const A=window.GalaAvatar,W=window.GalaWeapons,canvas=document.getElementById('restAvatar'),scene=document.querySelector('.encounter'),type=document.getElementById('weaponType'),tier=document.getElementById('weaponTier'),note=document.getElementById('weaponStatus');
 let progress=equipmentProgress(),look=null,equipped={type:'rapier',tier:0},running=false,frame=0,last=0,strike=-Infinity,team=false;
 window.GalaProgress={read:()=>progress};const body=document.createElement('canvas'),weapon=document.createElement('canvas');weapon.width=40;weapon.height=72;
 for(const item of W.types){const option=document.createElement('option');option.value=item.id;option.textContent=item.name;type.append(option);}
 function load(){look=loadGala(localStorage,A).look;const selected=look.weapon||{type:'rapier',tier:0};equipped=W.unlocked(selected,progress)?selected:{type:selected.type,tier:0};A.draw(body,look,{base:false,weapon:false,prop:false});const ctx=weapon.getContext('2d');ctx.clearRect(0,0,40,72);W.draw(ctx,equipped);type.value=selected.type;tier.replaceChildren();for(let i=0;i<W.tiers.length;i++){const item={type:selected.type,tier:i},option=document.createElement('option'),r=W.requirements(item);option.value=i;option.disabled=!W.unlocked(item,progress);option.textContent=W.tiers[i]+(option.disabled?` · ${r.days} days / strength ${r.strength}`:'');tier.append(option);}tier.value=equipped.tier;note.textContent=W.name(equipped)+` · ${progress.activeDays} workout days · Strength ${progress.strength}`+(selected.tier!==equipped.tier?'. Your imported upgrade will equip when earned.':'');document.getElementById('restWeaponName').textContent=W.name(equipped);scene.dataset.weapon=MELEE.has(equipped.type)?'melee':'ranged';draw(performance.now());}
 function equip(){try{const next={type:type.value,tier:Number(tier.value)};if(!W.unlocked(next,progress))return;localStorage.setItem(GALA_KEY,JSON.stringify({...look,weapon:next}));window.dispatchEvent(new Event('mominc-avatar-change'));}catch{note.textContent='Could not save this weapon. Check device storage.';}}
 type.addEventListener('change',equip);tier.addEventListener('change',equip);
 function draw(now){canvas.width=160;canvas.height=168;const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,age=(now-strike)/650,hit=!reduced&&age>=0&&age<1,pulse=hit?Math.sin(age*Math.PI):0;ctx.drawImage(body,26+pulse*7,14-pulse*8,96,144);ctx.save();ctx.translate(109+pulse*12,80-pulse*16);ctx.rotate(-.1+(MELEE.has(equipped.type)?pulse*1.1:pulse*.15));ctx.drawImage(weapon,-17,-32,34,62);ctx.restore();if(hit){ctx.strokeStyle=team?'#e4b5ff':'#b0ffec';ctx.lineWidth=team?4:2;ctx.globalAlpha=1-age;if(MELEE.has(equipped.type)){ctx.beginPath();ctx.arc(103,72,35,-1.8,.4);ctx.stroke();}else{ctx.fillStyle=team?'#e4b5ff':'#b0ffec';ctx.fillRect(114+age*22,59-age*48,team?8:5,12);}}}
 function tick(now){frame=0;if(!running||document.hidden)return;if(now-last>32){draw(now);last=now;}frame=requestAnimationFrame(tick);}
 function start(){running=true;load();if(!frame)frame=requestAnimationFrame(tick);}
 function stop(){running=false;if(frame)cancelAnimationFrame(frame);frame=0;scene.classList.remove('team-strike');}
 const visibility=()=>{if(document.hidden){if(frame)cancelAnimationFrame(frame);frame=0;}else if(running&&!frame)frame=requestAnimationFrame(tick);};
 const account=event=>{progress=equipmentProgress(event.detail);load();};window.addEventListener('myr5:account-progress',account);window.addEventListener('mominc-avatar-change',load);document.addEventListener('visibilitychange',visibility);load();
 return {load,start,stop,attack(hit){strike=performance.now();team=!!hit.assisted;scene.classList.toggle('team-strike',team);draw(strike);},dispose(){stop();window.removeEventListener('myr5:account-progress',account);window.removeEventListener('mominc-avatar-change',load);document.removeEventListener('visibilitychange',visibility);type.removeEventListener('change',equip);tier.removeEventListener('change',equip);}};
}
