// User-selected coach identities. Each retained coach has one or two display names.
// Person, workout, and tech preserve provenance from the matching original candidate.
// Track is the coach's primary mapped workout group (performance-catalog tracks).
export const EXCLUDED_COACH_IDS=Object.freeze(['roster/21-flyer--winged_humanoid_3d_model','roster/18-quad-all--wooden_robot_3d_model']);
const ROWS=[
["myr5","original",["MYR5 Jacked LaLAN","Jack LaLanne","jacked strength","local area network"],["MYR5 AT-Lift Prime","Charles Atlas","lift","model designation"]],
["02-taper-tallstalk--humanoid_robot_3d_model1","arms",["Arnoid Press","Arnold Schwarzenegger","Arnold press","android"],["ScotTorque Curl","Larry Scott","curl","motor torque"]],
["19-genie-multi--multi-armed_humanoid_3d_model1","arms",["Ferri-Delt L0U","Lou Ferrigno","delt","robot designation"],["R0N Curlman","Ronnie Coleman","curl","engine manifold"]],
["19-genie-multi--multi-armed_humanoid_3d_model","arms",["Frank Delt-Zan3","Frank Zane","delt","magnetic coil"],["Cutlerator Curl","Jay Cutler","curl","accelerator"]],
["17-shellcap-manyarm--mushroom_creature_3d_model","arms",["KAI-nematic Raise","Kai Greene","raise","kinematic mechanism"],["Philament Heave Press","Phil Heath","press","electrical filament"]],
["17-shellcap-manyarm--mushroom_robot_3d_model","arms",["Wheel-er Servo-Shrug","Flex Wheeler","shrug","servo wheel"]],
["23-blob-texture-bodies--patchwork_plush_figure_3d_model","arms",["Ree-volts Raise","Steve Reeves","raise","voltage"]],
["08-shard-asym--robot_3d_model4","arms",["S3RG Oliv-Armature","Sergio Oliva","arm","motor armature"]],
["17-shellcap-manyarm--3d_character_figurine","arms",["Delt-alinn Bailey","Dana Linn Bailey","delt","Delta designation"]],
["06-ridge-triad--geometric_robot_3d_model1","chest",["Oliva-C Pec","Sergio Oliva","pec","vacuum drive"]],
["08-shard-asym--geometric_robot_3d_model","chest",["Pec-n0ld Reactor","Arnold Schwarzenegger","pec","reactor"]],
["16-spade-arch--pyramid_head_figure_3d_model","chest",["Franx Pec-Zane","Frank Zane","pec","motor drive"],["Y4TES Yoke","Dorian Yates","press","powered yoke"]],
["04-crest-wedge--robot_creature_3d_model","chest",["L0U Ferri-pecctor","Lou Ferrigno","pec","reactor"],["Wheeler Wheel-Bench","Flex Wheeler","bench","drive wheel"]],
["16-spade-arch--stylized_humanoid_3d_model","chest",["Cutlerator Press","Jay Cutler","press","accelerator"]],
["04-crest-wedge--stylized_3d_character","chest",["Gr33ne Grid-Press","Kai Greene","press","power grid designation"]],
["09-monolith-tanka--3d_robot_model","chest",["chris BenchSTEAD","Chris Bumstead","bench","robot"]],
["09-monolith-tanka--white_horned_robot_3d_model","chest",["Cavalier-EX Chest","Jeff Cavaliere","chest","exercise model EX"]],
["15-orbital-coili--robot_character_3d_model","quads",["t-OHM Platzma","Tom Platz","squat","plasma"]],
["13-fan-split--stylized_3d_character2","quads",["Quad-Cutler LEGS THO","Jay Cutler","quad","circuit"],["BumSTEADy Squat","Chris Bumstead","squat","steady-state control"]],
["22-curve--stylized_cartoon_figure_3d_model","quads",["Kai Gr33ne Lunge","Kai Greene","lunge","gear designation"]],
["02-taper-tallstalk--3d_humanoid_figure","quads",["Hane-Yoke Lunge","Lee Haney","lunge","powered yoke"],["Stern-on Squat","Erin Stern","squat","power-on switch"]],
["02-taper-tallstalk--white_humanoid_doll_3d_model","quads",["Oli-Volt Lunge","Sergio Oliva","lunge","voltage"],["Y4TES Yoke-Squat","Dorian Yates","squat","robot designation"]],
["18-quad-all--wooden_four-legged_robot_3d_model","quads",["Priest-L33 Squat","Lee Priest","squat","piston"]],
["18-quad-all--stylized_quadruped_3d_model","quads",["Quadzilla Platz","Tom Platz","quads","kaiju creature"],["SternShift Squat","Erin Stern","squat","gear shift"]],
["23-blob-texture-bodies--honeycomb_humanoid_3d_model","glutes",["Con-Thrust-Era","Bret Contreras","hip thrust","thruster"]],
["23-blob-texture-bodies--sand_creature_3d_model","glutes",["Tingularity Thrust","Chloe Ting","hip thrust","singularity"]],
["03-pearl-orb-ring--stylized_3d_character1","glutes",["Gyrvanium Glute-Drive","Caroline Girvan","glute","futuristic alloy"],["Jill-iON Hinge-Flex","Jillian Michaels","hip hinge","ion drive"]],
["03-pearl-orb-ring--stylized_humanoid_figure_3d_model","glutes",["Trac-ION Hip-Thrust","Tracy Anderson","hip thrust","ion drive"],["Simmonics Bridge-Servo","Whitney Simmons","bridge","electronics servo"]],
["03-pearl-orb-ring--abstract_humanoid_3d_model","glutes",["Robo-ertson Bridge","Heather Robertson","bridge","robot"],["Hearn-ess ExoHinge","Katy Hearn","hinge","exosuit harness"]],
["03-pearl-orb-ring--circle_center","glutes",["Con-Terra Coil-Bridge","Bret Contreras","bridge","planetary coil"],["Cyb-Ho Holo-Bridge","Cassey Ho","bridge","cyborg hologram"]],
["23-blob-texture-bodies--cute_blob_creature_3d_model","glutes",["Chlo-Turbo Thrust","Chloe Ting","thrust","turbine"]],
["10-petal-wisp--fantasy_creature_3d_model4","yoga",["Adriene A-Sana Mk II","Adriene Mishler","asana","model revision"]],
["19-genie-multi--fantasy_creature_3d_model","yoga",["Mat-Gregor Matrix","Kino MacGregor","mat","simulation matrix"]],
["10-petal-wisp--ghost_character_3d_model","yoga",["Warri0r-ner Drive","Dylan Werner","warrior pose","motor designation"],["Kathryn Bend-1g","Kathryn Budig","bend","robot"]],
["08-shard-asym--stylized_action_figure_3d_model","yoga",["Yee-lastic Flow","Rodney Yee","yoga flow","elastic mechanics"]],
["22-curve--stylized_alien_3d_model","yoga",["Strom Flex Current","Max Strom","stretch","electric current"]],
["10-petal-wisp--stylized_creature_3d_model","yoga",["Iyeng-Arc Inversion","B. K. S. Iyengar","inversion","powered arc"]],
["19-genie-multi--stylized_octopus_3d_model","yoga",["Yee Gyro-Yogi","Rodney Yee","yoga","gyroscope"]],
["01-seed-pearo--cute_alien_figure_3d_model","yoga",["Wern-Axis Flow","Dylan Werner","flow","robotic axis"],["Mat-Gregor Drive","Kino MacGregor","mat practice","motor drive"]],
["01-seed-pearo--white_3d_character_model","yoga",["Budig-ital Balance","Kathryn Budig","balance","digital"],["Corn Kernel Cobra","Seane Corn","cobra pose","computing kernel"]],
["09-monolith-tanka--boxy_humanoid_3d_model","martial-arts",["Bruce L3300","Bruce Lee","kick","alphanumeric call sign"],["GSP-Drive","Georges St-Pierre","spar","motor drive"]],
["11-anvil-cask--clay-style_robot_3d_model","martial-arts",["Anderson Sil-VOLT","Anderson Silva","strike","voltage"],["r0nda Rous-Bot","Ronda Rousey","armbar","robot"]],
["05-slope-bobble--clay_humanoid_figure_3d_model","martial-arts",["C0N0R McG-Gear","Conor McGregor","kick","gear transmission"],["Nor-Rotor Punch","Chuck Norris","punch","rotor"]],
["14-chisel-spire--cone_head_3d_model","martial-arts",["LiDAR Jett-Jab","Jet Li","jab","laser ranging"],["Jaa-Bot Jab","Tony Jaa","jab","robot"]],
["08-shard-asym--fantasy_creature_3d_model2","martial-arts",["Waters0nic","Michelle Waterson","kick","sonic drive"],["Amanda Nu-NEURAL","Amanda Nunes","strike","neural implant"]],
["09-monolith-tanka--mini_robot_3d_model","martial-arts",["Machi-Droid-a","Lyoto Machida","chop","android"],["Bas Rut-TORque","Bas Rutten","kick","motor torque"]],
["09-monolith-tanka--robot_3d_model3","martial-arts",["Israel Ade-SYNC-ya","Israel Adesanya","strike","synchronization"],["Shev-Servo Sweep","Valentina Shevchenko","sweep","servo"]],
["13-fan-split--stylized_toy_3d_model","martial-arts",["BlankSaber Kick","Billy Blanks","kick","energy saber"],["Wilsonic Kick","Don Wilson","kick","sonic drive"]],
["09-monolith-tanka--robot_3d_model2","martial-arts",["Rous-Torque Throw","Ronda Rousey","throw","motor torque"],["Jackie Chain-Kick","Jackie Chan","kick","chain drive"]],
["07-bulb-sphereling--humanoid_robot_3d_model","cardio",["B0LT Sprint-Drive","Usain Bolt","sprint","electrical bolt drive"]],
["03-pearl-orb-ring--ringed_humanoid_3d_model","cardio",["Fon-Dynamo Footwork","Jane Fonda","footwork","dynamo"],["Simmonics Sweatstream","Richard Simmons","aerobic sweat","electronics stream"]],
["06-ridge-triad--robot_3d_model1","cardio",["M0 Farah Fastlane","Mo Farah","fast run","electric capacitance"]],
["03-pearl-orb-ring--robot_3d_model","cardio",["Feli-X Footdrive","Allyson Felix","footwork","X-model drive"],["Rad-Clutch Run","Paula Radcliffe","run","motor clutch"]],
["20-lume--robotic_figure_3d_model","cardio",["Pre-Font-AI-ne Pace","Steve Prefontaine","pace","AI running model"],["Ohm-wens Run","Jesse Owens","run","electrical resistance"]],
["07-bulb-sphereling--cute_robot_3d_model","cardio",["Billy Blanx Beam","Billy Blanks","boot camp","waveform"],["GebreShell Runloop","Haile Gebrselassie","run","software shell loop"]],
["01-seed-pearo--blank_toy_figure_3d_model","cardio",["Phelpeller Pulse","Michael Phelps","cardio pulse","propeller"],["Fon-Droid Footwork","Jane Fonda","footwork","android"]],
["18-quad-all--dragon_creature_3d_model","meditation",["H0F-Lung","Wim Hof","breathing","oxygen-code lung"]],
["18-quad-all--fantasy_creature_3d_model1","meditation",["Max Ohm-Strom Breath","Max Strom","breathing","electrical resistance"],["Yee-uro Zen","Rodney Yee","mindful movement","neural interface"]],
["18-quad-all--fantasy_creature_3d_model3","meditation",["Shiva Rea-spatory","Shiva Rea","respiration","airlock"]],
["18-quad-all--four-legged_robot_3d_model","meditation",["Tara-5tile5-Standby","Tara Stiles","breathing","computer standby"]],
["18-quad-all--quadruped_robot_3d_model1","meditation",["Werner Wind0wn","Dylan Werner","wind-down practice","alphanumeric standby mode"]],
["18-quad-all--quadruped_robot_3d_model","meditation",["Yee Holo-Om","Rodney Yee","mindful movement","hologram"]],
["18-quad-all--robotic_dog_3d_model","meditation",["Budig-ital Breath","Kathryn Budig","breathing","digital"]],
["12-seedpod-snailslug--stylized_slug_3d_model","meditation",["H0F Hold-Circuit","Wim Hof","breath hold","circuit and model code"],["Ohm-Strom Still","Max Strom","stillness","electrical resistance"]],
["12-seedpod-snailslug--stylized_worm_3d_model","meditation",["Pilat-OS Calm-Circuit","Joseph Pilates","mindful breathing","operating system circuit"]],
["14-chisel-spire--low_poly_robot_3d_model","meditation",["Rea-Spire Relay","Shiva Rea","respiration","air relay"]],
["01-seed-pearo--3d_character_model","meditation",["McKe-O2 Nose-Cone","Patrick McKeown","nasal breathing","rocket nose cone"],["Vertu-al Vent","Shona Vertue","ventilation","virtual reality"]],
["23-blob-texture-bodies--blob_creature_3d_model","meditation",["Blob 1 · H0F Hold-Drive","Wim Hof","breath hold","air drive and model code"]],
["01-seed-pearo--blank_humanoid_figure_3d_model","meditation",["Corn Kernel Om","Seane Corn","meditation","computing kernel"],["Kino-Kinetic Breath","Kino MacGregor","breathing","kinematics"]],
];
const META=Object.freeze(Object.fromEntries(ROWS.map(([path,track,...candidates])=>[path==='myr5'?path:`roster/${path}`,Object.freeze({track,names:Object.freeze(candidates.map(([name,person,workout,scifi])=>Object.freeze({name,person,workout,scifi})))})])));
export const COACH_NAME_META=META;
/** One or two user-selected names by stable coach id. */
export const COACH_NAMES=Object.freeze(Object.fromEntries(Object.entries(META).map(([id,m])=>[id,Object.freeze(m.names.map(n=>n.name))])));
export const normalizePun=text=>String(text).toLowerCase().normalize('NFD').replace(/[^a-z0-9]/g,'');
function metaFor(coachId){const meta=META[coachId];if(!meta)throw RangeError(`No coach name for ${coachId}.`);return meta;}
/** Primary name, or the second candidate if available. */
export const coachName=(coachId,alternative=false)=>{const names=metaFor(coachId).names;return names[alternative?1:0]?.name??names[0].name;};
/** Toggle a pair; a single-name coach keeps its selected name. */
export function cycleCoachName(coachId,current){const names=metaFor(coachId).names.map(n=>n.name);return names.length===1?names[0]:current===names[0]?names[1]:names[0];}
