import {isInstalled} from './install-context.mjs';
const KEY='myr5-gala-run-v1';
const valid=data=>data?.version===1&&/^[0-9a-f-]{36}$/.test(data.id)&&/^[a-f0-9]{64}$/.test(data.token);
export function decodeGala(raw){if(typeof raw!=='string'||raw.length>18000)throw Error('This Gala invitation is invalid.');let data;try{data=JSON.parse(decodeURIComponent(escape(atob(raw))));}catch{throw Error('This Gala invitation is unreadable.');}if(!valid(data))throw Error('This Gala invitation is invalid.');return data;}
function importIdentity(data){if(window.MBS_DJ?.valid(data.dj))localStorage.setItem('mbs-dj-identity-v1',JSON.stringify(data.dj));if(data.avatar&&window.GalaAvatar){try{localStorage.setItem('mominc-avatar-v1',JSON.stringify(window.GalaAvatar.normalize(data.avatar)));window.dispatchEvent(new Event('mominc-avatar-change'));}catch{}}}
export function captureGala(){const params=new URLSearchParams(location.hash.slice(1)),raw=params.get('gala');if(raw){params.delete('gala');history.replaceState(null,'',location.pathname+location.search+(params.size?'#'+params:''));const data=decodeGala(raw);localStorage.setItem(KEY,JSON.stringify(data));importIdentity(data);return data;}try{const data=JSON.parse(localStorage.getItem(KEY));return valid(data)?data:null;}catch{return null;}}
async function request(path,data,token){const r=await fetch('/api/gala/'+path,{method:data?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:{...(data?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{})},body:data?JSON.stringify(data):undefined,signal:AbortSignal.timeout(15000)});const value=await r.json();if(!r.ok)throw Error(value.error||'Your Gala run could not connect. Retry while connected.');return value;}
export async function prepareGalaInstall(){const data=captureGala();if(data)await request('install-draft',{id:data.id,token:data.token});return data;}
async function restoreGala(){let data=captureGala();if(!data){data=(await request('install-draft')).data;if(valid(data))localStorage.setItem(KEY,JSON.stringify(data));else data=null;}if(data)importIdentity(data);return data;}
export async function saveInstalledRun(){if(!isInstalled())return null;const data=await restoreGala();if(!data)return null;const value=await request('runs/'+data.id+'/install',{installed:true},data.token);if(value.djName&&!window.MBS_DJ?.read()){const base=value.djName.split(' · ')[0],dj={version:1,base,moniker:value.moniker,parts:base.split(' ').slice(0,3),chosenAt:value.startedAt,completedAt:value.startedAt};while(dj.parts.length<3)dj.parts.push('DJ');if(window.MBS_DJ?.valid(dj)){localStorage.setItem('mbs-dj-identity-v1',JSON.stringify(dj));window.dispatchEvent(new Event('mominc-avatar-change'));}}return value;}
export async function mountGalaReturn(){let data,error='';try{data=isInstalled()?await restoreGala():captureGala();}catch(e){error=e.message;}if(!data&&!error)return;let panel=document.getElementById('galaReturn');if(panel)return;panel=document.createElement('aside');panel.id='galaReturn';panel.style.cssText='padding:14px;margin:12px 0;background:#111d28;color:#acffe0;border:2px outset #648d99;font:14px/1.5 monospace';panel.innerHTML='<strong>GOON GALA · RUN ARCHIVE</strong><p role="status"></p><a href="https://mominc.online/gala/terminal/" style="color:#befaff">Return to the Gala terminal →</a><button type="button" style="margin-left:10px;min-height:40px">Retry saving</button>';(document.querySelector('.install-card')||document.getElementById('accountContent')||document.body).append(panel);const message=panel.querySelector('p'),retry=panel.querySelector('button');async function save(){try{retry.disabled=true;await prepareGalaInstall();const run=await saveInstalledRun();message.textContent=run?(run.completedAt?'App received. Your run is saved. Join the rankings at the Gala terminal.':'App received. Finish your remaining run clearances at the Gala terminal.'):'Install and open MYR5 from its app icon to save this run.';retry.hidden=!!run;}catch(e){message.textContent=e.message;retry.hidden=false;}finally{retry.disabled=false;}}retry.onclick=save;window.addEventListener('online',save);if(error)message.textContent=error;else save();}
