import {mountLaunch} from './launch-shell.mjs';
import {renderAchievements} from './achievements.mjs';
mountLaunch();
const $=id=>document.getElementById(id),keys=['myr5-recipe-v1','myr5-motion-v1','mominc-avatar-v1','myr5-pod-power-v1'];
let account=null,revision=0,worker=null,photoUrl=null,registration=null,installPrompt=null;
const set=(id,text)=>$(id).textContent=text;
export async function api(path,method='GET',data){const response=await fetch(path,{method,credentials:'same-origin',headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined,cache:'no-store'});if(response.redirected||!response.headers.get('content-type')?.includes('application/json'))throw Error('Sign in to Coach again to reconnect.');const value=await response.json();if(!response.ok)throw Object.assign(Error(value.error||'Please try again.'),{status:response.status});return value;}
const button=(text,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=fn;return b;};
function download(data,name,type='application/json'){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([data],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function publishProgress(p){window.dispatchEvent(new CustomEvent('myr5:account-progress',{detail:p}));set('accountLevel',`Level ${p.level}`);set('accountSets',`${p.completedSets} completed sets`);$('rewardList').replaceChildren();for(const [label,key,sets] of [['Ember','ember',4],['Arc','arc',16],['Frost','frost',36],['Shield break','shieldBreak',196]]){const row=document.createElement('li');row.className='unlock-row';row.dataset.unlocked=String(p.unlocks[key]);const name=document.createElement('span'),state=document.createElement('span');name.textContent=label;state.textContent=p.unlocks[key]?'✓ Unlocked':`${Math.max(0,sets-p.completedSets)} sets left`;row.append(name,state);$('rewardList').append(row);}}
async function refresh(){try{const value=await api('/api/account');account=value;revision=value.revision;$('signIn').hidden=true;$('accountContent').hidden=false;$('accountSettingsContent').hidden=false;set('accountName',value.user.email);publishProgress(value.progress);set('accountStatus','Your completed workouts and meal log sync with this account.');set('syncBadge','Account connected · progress saved online');set('pushStatus',value.push.schedulerActive?'Online reminder sender is running. Enable notifications on each device.':'The reminder sender is connecting or temporarily unavailable. Try again shortly.');$('enablePush').disabled=!value.push.configured||!value.push.schedulerActive;await flushSets();return value;}catch(e){if(e.status===401){account=null;$('signIn').hidden=false;$('accountContent').hidden=true;$('accountSettingsContent').hidden=true;$('workoutList').replaceChildren();set('accountName','Sign in to keep your meals, workouts and appearance across devices.');set('syncBadge','Sign in to save progress');}else set('syncBadge',navigator.onLine?e.message:'Offline · reconnect to sync');return null;}}
const pendingKey=user=>`myr5-pending-sets:${user}`;
function pending(user){try{return JSON.parse(localStorage.getItem(pendingKey(user))||'[]');}catch{return [];}}
async function flushSets(){if(!account)return;const user=account.user.id,queue=pending(user);for(const item of queue){try{const r=await api('/api/workouts/complete','POST',item);const rest=pending(user).filter(x=>x.id!==item.id);localStorage.setItem(pendingKey(user),JSON.stringify(rest));publishProgress(r.progress);}catch(e){set('syncBadge',`Set waiting to sync: ${e.message}`);break;}}}
window.coachAccount={async start(mode,goal){const ready=account||await refresh();if(!ready)throw Error('Sign in from Progress before starting a saved workout.');await flushSets();return api('/api/workouts/start','POST',{mode,goal});},async complete(data){if(!account)return;const queue=pending(account.user.id);if(!queue.some(x=>x.id===data.id)){queue.push(data);localStorage.setItem(pendingKey(account.user.id),JSON.stringify(queue));}await flushSets();}};
const localDate=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
$('mealForm').elements.eatenAt.value=localDate();$('reminderForm').elements.timezone.value=Intl.DateTimeFormat().resolvedOptions().timeZone;
async function meals(){try{const {items}=await api('/api/meals');$('mealList').replaceChildren();if(!items.length)set('mealList','No meals logged yet.');for(const item of items){const row=document.createElement('div');row.className='entry';const text=document.createElement('div');text.textContent=item.name;const detail=document.createElement('small');detail.textContent=`${item.portion} · ${new Date(item.eaten_at).toLocaleString()}${item.calories===null?'':` · ${item.calories} kcal`}`;text.append(detail);row.append(text,button('Remove',async()=>{try{await api(`/api/meals/${item.id}`,'DELETE');await meals();}catch(e){set('mealStatus',e.message);}}));$('mealList').append(row);}}catch(e){set('mealList',e.message);}}
$('mealForm').onsubmit=async e=>{e.preventDefault();const form=e.target,submit=form.querySelector('[type=submit]');submit.disabled=true;const d=Object.fromEntries(new FormData(form));for(const n of ['calories','protein','carbs','fat'])d[n]=d[n]===''?null:Number(d[n]);d.id=crypto.randomUUID();d.eatenAt=new Date(d.eatenAt).toISOString();try{await api('/api/meals','POST',d);set('mealStatus','Meal saved to your account.');form.reset();form.elements.eatenAt.value=localDate();await meals();}catch(err){set('mealStatus',err.message);}finally{submit.disabled=false;}};
$('foodPhoto').onchange=()=>{const file=$('foodPhoto').files[0];if(photoUrl)URL.revokeObjectURL(photoUrl);photoUrl=null;$('foodSuggestions').replaceChildren();if(!file)return;if(file.size>15*1024*1024){set('foodStatus','Choose a photo smaller than 15 MB.');return;}photoUrl=URL.createObjectURL(file);$('foodPreview').src=photoUrl;$('foodPreview').hidden=false;set('foodStatus','Photo ready. Tap Recognize food.');};
$('recognizeFood').onclick=async()=>{if(!photoUrl){set('foodStatus','Choose a meal photo first.');return;}$('recognizeFood').disabled=true;try{const img=await createImageBitmap($('foodPhoto').files[0]);const canvas=document.createElement('canvas'),ratio=Math.min(1,768/Math.max(img.width,img.height));canvas.width=Math.round(img.width*ratio);canvas.height=Math.round(img.height*ratio);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);img.close();worker??=new Worker('/food-worker.mjs',{type:'module'});worker.onerror=()=>{set('foodStatus','Recognition is unavailable in this browser. Type the food name below.');$('recognizeFood').disabled=false;worker?.terminate();worker=null;};worker.onmessage=({data})=>{if(data.type==='progress')set('foodStatus',data.text);else{$('recognizeFood').disabled=false;if(data.type==='error'){set('foodStatus',data.text);return;}set('foodStatus',data.uncertain?'I’m not sure this photo shows a recognizable food. Enter the name or select a suggestion.':'Possible matches. Select the food, then confirm its name and portion.');$('foodSuggestions').replaceChildren(...data.items.map(item=>button(item.label,()=>{$('mealName').value=item.label;$('mealName').focus();})));}};worker.postMessage({image:canvas.toDataURL('image/jpeg',.85)});}catch{set('foodStatus','Could not read that photo. Try a JPEG or PNG.');$('recognizeFood').disabled=false;}};
async function reminders(){try{const {items}=await api('/api/reminders');$('reminderList').replaceChildren();if(!items.length)set('reminderList','No reminders saved yet.');for(const r of items){const row=document.createElement('div');row.className='entry';const text=document.createElement('div');text.textContent=`${r.kind[0].toUpperCase()+r.kind.slice(1)} · ${r.time}`;const hint=document.createElement('small');hint.textContent=`Daily · ${r.timezone} · Quiet ${r.quiet_start}–${r.quiet_end}`;text.append(hint);row.append(text,button('Remove',async()=>{try{await api(`/api/reminders/${r.id}`,'DELETE');await reminders();}catch(e){set('reminderStatus',e.message);}}));$('reminderList').append(row);}}catch(e){set('reminderList',e.message);}}
$('reminderForm').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{await api('/api/reminders','POST',{...Object.fromEntries(new FormData(e.target)),id:crypto.randomUUID(),enabled:true});set('reminderStatus',account?.push.schedulerActive?'Reminder saved.':'Reminder saved; delivery starts once the online sender is connected.');await reminders();}catch(err){set('reminderStatus',err.message);}finally{b.disabled=false;}};
const fromBase64=text=>Uint8Array.from(atob(text.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(text.length/4)*4,'=')),c=>c.charCodeAt(0));
$('enablePush').onclick=async()=>{try{if(!('Notification'in window)||!('PushManager'in window))throw Error('Install Coach on your home screen and use a browser that supports notifications.');if(!account?.push.schedulerActive)throw Error('The online sender is not connected yet.');const permission=await Notification.requestPermission();if(permission!=='granted')throw Error('Notifications were not allowed. You can enable them in your phone settings.');const reg=await navigator.serviceWorker.ready;const sub=await reg.pushManager.getSubscription()||await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:fromBase64(account.push.publicKey)});await api('/api/push/subscribe','POST',sub.toJSON());set('pushStatus','This device is connected. Send a test reminder to check delivery.');}catch(e){set('pushStatus',e.message);}};
$('testPush').onclick=async()=>{try{const sub=await registration?.pushManager.getSubscription();if(!sub)throw Error('Enable notifications on this device first.');await api('/api/push/test','POST',{endpoint:sub.endpoint});set('pushStatus','The notification service accepted the test. Check your phone.');}catch(e){set('pushStatus',e.message);}};
$('disablePush').onclick=async()=>{try{const sub=await registration?.pushManager.getSubscription();if(sub){await api('/api/push/unsubscribe','POST',{endpoint:sub.endpoint});await sub.unsubscribe();}set('pushStatus','Reminders are off on this device.');}catch(e){set('pushStatus',e.message);}};
async function workouts(){if(!account)return;const user=account.user.id;$('workoutList').setAttribute('aria-busy','true');set('recordsStatus','Updating your records…');try{const {items}=await api('/api/achievements');if(account?.user.id!==user)return;renderAchievements($('workoutList'),items);set('recordsStatus',items.length?'':'Finish a set to put your first record on the board.');}catch(e){set('recordsStatus',`Records could not refresh. ${e.message}`);}finally{$('workoutList').removeAttribute('aria-busy');}}
$('saveProfile').onclick=async()=>{try{const data=Object.fromEntries(keys.map(k=>[k,localStorage.getItem(k)]).filter(([,v])=>v!=null));const result=await api('/api/profile','PUT',{revision,data});revision=result.revision;await refresh();set('accountStatus','Appearance saved to your account.');}catch(e){set('accountStatus',e.message);}};
$('restoreProfile').onclick=async()=>{const value=await refresh();if(!value)return;for(const key of keys){const v=value.profile[key];if(v!=null){localStorage.setItem(key,v);window.dispatchEvent(new StorageEvent('storage',{key,newValue:v}));}}window.dispatchEvent(new Event('mominc-avatar-change'));set('accountStatus','Saved appearance restored.');};
$('refreshAccount').onclick=async()=>{await refresh();await workouts();};
$('exportData').onclick=async()=>{try{download(JSON.stringify(await api('/api/export'),null,2),'myr5-data.json');}catch(e){set('accountStatus',e.message);}};
$('signOut').onclick=async e=>{e.preventDefault();try{await flushSets();if(account&&pending(account.user.id).length)throw Error('A workout is waiting to sync. Reconnect before signing out.');const sub=await registration?.pushManager.getSubscription();if(sub){await api('/api/push/unsubscribe','POST',{endpoint:sub.endpoint});await sub.unsubscribe();}for(const k of [...keys,'myr5-workout-progress-v1'])localStorage.removeItem(k);location.assign(e.target.href);}catch(err){set('accountStatus',err.message);}};
$('deleteAccount').onclick=async()=>{try{await api('/api/account','DELETE',{confirm:$('deleteConfirm').value});if(account)localStorage.removeItem(pendingKey(account.user.id));for(const k of [...keys,'myr5-workout-progress-v1'])localStorage.removeItem(k);location.reload();}catch(e){set('accountStatus',e.message);}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('installApp').hidden=false;set('installStatus','Coach is ready to install on your home screen.');});window.addEventListener('appinstalled',()=>{set('installStatus','Coach is installed.');$('installApp').hidden=true;});
set('installStatus',matchMedia('(display-mode: standalone)').matches?'Coach is running as an installed app.':'Install Coach for a full-screen training pod.');
$('installApp').onclick=async()=>{if(installPrompt){await installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('installApp').hidden=true;}};
$('voiceStyle').value=localStorage.getItem('myr5-voice-style')||'robot';$('voiceStyle').onchange=()=>localStorage.setItem('myr5-voice-style',$('voiceStyle').value);
$('downloadVoice').onclick=async()=>{const b=$('downloadVoice');b.disabled=true;try{const manifest=await(await fetch('/voice/manifest.json')).json(),urls=Object.values(manifest.phrases),cache=await caches.open('myr5-voice-v1');let i=0;await cache.add('/voice/manifest.json');for(const url of urls){if(!await cache.match(url)){const response=await fetch(url);if(!response.ok)throw Error('Download interrupted. Tap again to resume.');await cache.put(url,response);}set('downloadStatus',`Downloaded ${++i} of ${urls.length} voice clips.`);}set('downloadStatus','Robot voice pack is available offline on this device.');}catch(e){set('downloadStatus',e.message);}finally{b.disabled=false;}};
if('serviceWorker'in navigator){navigator.serviceWorker.register('/sw.js').then(reg=>{registration=reg;const update=()=>{if(reg.waiting){$('applyUpdate').hidden=false;$('applyUpdate').onclick=()=>{reg.waiting.postMessage({type:'SKIP_WAITING'});};}};update();reg.addEventListener('updatefound',()=>reg.installing?.addEventListener('statechange',update));navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload());}).catch(()=>set('installStatus','Installation could not initialize. Refresh Coach and try again.'));}
for(const button of document.querySelectorAll('[data-panel]'))button.addEventListener('click',async()=>{if(button.dataset.panel==='meals')await meals();if(button.dataset.panel==='reminders'){await refresh();await reminders();}if(button.dataset.panel==='account'){await refresh();await workouts();}});
window.addEventListener('online',refresh);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});
await refresh();const panel=new URLSearchParams(location.search).get('panel');if(['meals','reminders','account','install'].includes(panel))document.querySelector(`[data-panel=${panel}]`).click();
