export function mountLaunch(){document.body.insertAdjacentHTML('beforeend',`
<span id="syncBadge" class="sync-badge" role="status" hidden>Connecting…</span>
<nav class="coach-dock" aria-label="Coach tools"><button data-panel="meals">Food</button><button data-panel="reminders">Reminders</button><button data-panel="account">Progress</button><button data-panel="install">Device</button></nav>
<dialog id="mealsPanel" class="launch-panel food-panel" aria-labelledby="mealsTitle"><header><h2 id="mealsTitle">Food</h2><button data-close>Close</button></header>
<button id="foodCamera" class="main-action food-camera" aria-label="Take a food photo"><svg viewBox="0 0 24 24" width="30" height="30" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M8 5l2-2h4l2 2h4a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2z"/><circle cx="12" cy="12" r="4"/></svg><span>Camera</span></button>
<input id="foodPhoto" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" hidden>
<p id="foodStatus" class="hint" role="status"></p>
<div id="mealScanStage" class="meal-scan-stage" hidden><img id="foodPreview" class="meal-preview" alt="Your selected meal"><div id="mealScanOverlay" class="meal-scan-overlay" data-state="ready"><div class="scan-grid" aria-hidden="true"></div><div class="scan-reticle" aria-hidden="true"></div><div class="scan-beam" aria-hidden="true"></div><div class="scan-heading"><span id="scanPhase">FOOD SCANNER</span><time id="scanElapsed" aria-label="Elapsed scan time">00:00</time></div><div class="scan-readout"><span id="scanDetail"></span><progress id="scanProgress" max="100" aria-label="Current model file download" hidden></progress></div></div></div>
<div class="actions scan-actions"><button id="recognizeFood" hidden>Retry scan</button><button id="cancelFoodScan" hidden>Stop scan</button></div>
<div id="foodSuggestions" class="actions" hidden></div>
<form id="mealForm">
 <div id="mealConfirmation" hidden><div class="fields"><label>Food<input name="name" id="mealName" required maxlength="160" autocomplete="off"></label><label>Portion (g)<input id="mealGrams" type="number" min="1" max="2000" step="1" value="100" required></label></div><label id="foodReferenceLabel">Food match<select id="foodReference"></select></label><p id="nutritionBasis" class="hint" role="status">Check food & portion</p></div>
 <section aria-labelledby="macroTitle"><h3 id="macroTitle">Macros</h3><div class="macro-grid"><div class="nutrient"><span>Calories</span><output id="nutrient-calories">—</output></div><div class="nutrient"><span>Protein</span><output id="nutrient-protein">—</output></div><div class="nutrient"><span>Carbs</span><output id="nutrient-carbs">—</output></div><div class="nutrient"><span>Fat</span><output id="nutrient-fat">—</output></div></div></section>
 <details><summary>More nutrients</summary><section aria-labelledby="microTitle"><h3 id="microTitle">Micros</h3><div class="micro-grid"><div class="nutrient"><span>Calcium</span><output id="nutrient-calcium">—</output></div><div class="nutrient"><span>Iron</span><output id="nutrient-iron">—</output></div><div class="nutrient"><span>Magnesium</span><output id="nutrient-magnesium">—</output></div><div class="nutrient"><span>Potassium</span><output id="nutrient-potassium">—</output></div><div class="nutrient"><span>Sodium</span><output id="nutrient-sodium">—</output></div><div class="nutrient"><span>Zinc</span><output id="nutrient-zinc">—</output></div><div class="nutrient"><span>Vitamin A</span><output id="nutrient-vitaminA">—</output></div><div class="nutrient"><span>Vitamin C</span><output id="nutrient-vitaminC">—</output></div><div class="nutrient"><span>Vitamin D</span><output id="nutrient-vitaminD">—</output></div><div class="nutrient"><span>Vitamin E</span><output id="nutrient-vitaminE">—</output></div><div class="nutrient"><span>Vitamin B12</span><output id="nutrient-vitaminB12">—</output></div><div class="nutrient"><span>Folate</span><output id="nutrient-folate">—</output></div></div><p class="hint nutrient-note">— unavailable</p></section></details>
 <div id="mealSaveControls" hidden><details id="nutritionAdjust"><summary>Edit nutrition & time</summary><label>Eaten at<input name="eatenAt" type="datetime-local" required></label><div class="nutrition manual-nutrition"><label>Calories (kcal)<input name="calories" type="number" min="0" max="20000" step="any"></label><label>Protein (g)<input name="protein" type="number" min="0" max="2000000" step="any"></label><label>Carbs (g)<input name="carbs" type="number" min="0" max="2000000" step="any"></label><label>Fat (g)<input name="fat" type="number" min="0" max="2000000" step="any"></label><label>Calcium (mg)<input name="calcium" type="number" min="0" max="2000000" step="any"></label><label>Iron (mg)<input name="iron" type="number" min="0" max="2000000" step="any"></label><label>Magnesium (mg)<input name="magnesium" type="number" min="0" max="2000000" step="any"></label><label>Potassium (mg)<input name="potassium" type="number" min="0" max="2000000" step="any"></label><label>Sodium (mg)<input name="sodium" type="number" min="0" max="2000000" step="any"></label><label>Zinc (mg)<input name="zinc" type="number" min="0" max="2000000" step="any"></label><label>Vitamin A (µg RAE)<input name="vitaminA" type="number" min="0" max="2000000" step="any"></label><label>Vitamin C (mg)<input name="vitaminC" type="number" min="0" max="2000000" step="any"></label><label>Vitamin D (µg)<input name="vitaminD" type="number" min="0" max="2000000" step="any"></label><label>Vitamin E (mg)<input name="vitaminE" type="number" min="0" max="2000000" step="any"></label><label>Vitamin B12 (µg)<input name="vitaminB12" type="number" min="0" max="2000000" step="any"></label><label>Folate (µg)<input name="folate" type="number" min="0" max="2000000" step="any"></label></div></details><input name="portion" type="hidden" value="100 g"><button type="submit" id="saveMeal" class="main-action">Save meal</button><p class="hint food-source">Estimates from <a href="https://www.ars.usda.gov/northeast-area/beltsville-md-bhnrc/beltsville-human-nutrition-research-center/methods-and-application-of-food-composition-laboratory/mafcl-site-pages/sr11-sr28/" target="_blank" rel="noreferrer">USDA SR28</a>. Photos stay on this device.</p></div>
</form><p id="mealStatus" role="status"></p><details class="recent-meals"><summary>Recent meals</summary><div id="mealList"></div></details></dialog>
<dialog id="remindersPanel" class="launch-panel" aria-labelledby="remindersTitle"><header><h2 id="remindersTitle">Reminders</h2><button data-close>Close</button></header><p id="pushStatus" class="status" role="status">Connecting…</p><p id="reminderLiveStatus" class="reminder-live" role="status"></p><div class="switch-plate"><div><strong>THIS DEVICE</strong></div><button id="notificationSwitch" class="hardware-toggle" role="switch" aria-checked="false" aria-label="Reminders and app updates on this device" disabled>OFF</button></div><div class="actions"><button id="testPush">Send a test</button></div><details><summary>Notification help</summary><p>Reminders and update alerts, even when Coach is closed. iPhone: install first.</p></details><form id="reminderForm"><div class="fields"><label>Reminder<select name="kind"><option value="workout">Workout</option><option value="meal">Meal logging</option><option value="water">Water</option><option value="motivation">Encouragement</option></select></label><label>At<input name="time" type="time" required value="17:00"></label></div><section class="reminder-tuning" aria-label="MOM reminder controls"><div class="tone-control"><label id="toneDialLabel">TONE</label><div class="tone-dial-row"><button type="button" id="gentlerTone" aria-label="Gentler wording">−</button><div id="toneDial" class="tone-dial" role="slider" tabindex="0" aria-labelledby="toneDialLabel" aria-valuemin="0" aria-valuemax="2" aria-valuenow="1" aria-valuetext="direct"><i aria-hidden="true"></i></div><button type="button" id="cheekierTone" aria-label="Cheekier wording">+</button></div><output id="toneValue">Direct</output><div class="tone-scale" aria-hidden="true">GENTLE · DIRECT · CHEEKY</div><input type="hidden" name="tone" value="direct"></div><div class="consistency-control"><label for="consistencySlider">FREQUENCY</label><output id="consistencyValue" for="consistencySlider">Every day</output><input id="consistencySlider" type="range" min="0" max="3" step="1" value="3" aria-valuetext="Every day"><div class="cadence-scale" aria-hidden="true"><span>1 / WK</span><span>3 / WK</span><span>5 / WK</span><span>DAILY</span></div><input type="hidden" name="daysPerWeek" value="7"></div><div class="message-preview"><small>MOM WILL SAY</small><p id="reminderPreview"></p></div></section><label>Time zone<input name="timezone" required></label><div class="fields"><label>Quiet hours begin<input name="quietStart" type="time" required value="22:00"></label><label>Quiet hours end<input name="quietEnd" type="time" required value="07:00"></label></div><label class="switch-label">Reminder on<input name="enabled" type="checkbox" role="switch" checked></label><button type="submit" id="saveReminder" class="main-action">Save reminder</button><button type="button" id="cancelReminderEdit" hidden>Cancel edit</button></form><p id="reminderStatus" role="status"></p><div id="reminderList"></div></dialog>
<dialog id="accountPanel" class="launch-panel accomplishments-panel" aria-labelledby="accountTitle">
 <header><div><h2 id="accountTitle">Progress</h2></div><button data-close>Close</button></header>
 <a id="signIn" class="action-link main-action" href="/signin.html?return_to=%2Fpose.html" target="_top">Sign in to Coach</a>
 <div id="accountContent" hidden>
  <section class="crew-invites" aria-labelledby="crewInviteTitle"><h3 id="crewInviteTitle">Invite friends</h3><div id="scoreboardCrew" class="scoreboard-crew"></div>
   <details id="crewInviteControls"><summary>Add friends</summary><p>Shares your name, look and best sets.</p><button type="button" id="createCrewInvite">Create invite code</button><button type="button" id="revokeCrewInvite" hidden>Cancel invite</button>
    <div id="crewInviteOutput" hidden><label>One-use code<input id="crewInviteCode" readonly autocomplete="off" spellcheck="false"></label><button type="button" id="copyCrewInvite">Copy code</button></div>
    <form id="crewJoinForm"><label>Have a friend’s code?<input id="crewJoinCode" autocomplete="off" spellcheck="false" placeholder="Paste their invite code" maxlength="40" required></label><button type="submit" id="crewJoin">Connect</button></form>
   </details><p id="crewStatus" role="status"></p>
  </section>
  <div class="progress-summary"><div><output id="accountLevel">Level 1</output><span id="accountSets">0 completed sets</span></div><button id="refreshAccount" aria-label="Refresh your records">↻ Refresh</button></div>
  <section class="goals-board" aria-labelledby="goalsTitle"><h3 id="goalsTitle">Goals</h3><p class="hint">Write your own small goal. Goals are saved to this account; they do not grant rewards.</p><form id="goalForm"><label>Title<input name="title" maxlength="160" required autocomplete="off"></label><label>Note (optional)<textarea name="note" maxlength="1000" rows="2"></textarea></label><button type="submit" class="main-action">Save goal</button></form><p id="goalStatus" role="status"></p><div id="goalList"></div></section>
  <div class="scoreboard-heading"><div><h3 id="scoreboardGroup">Chest</h3><p id="scoreboardSubtitle">Push-up progressions</p></div><div class="medal-key" aria-label="Rank colors"><span data-medal="gold">1 Gold</span><span data-medal="silver">2 Silver</span><span data-medal="bronze">3 Bronze</span></div></div>
  <p id="recordsStatus" class="hint" role="status">Loading your records…</p><div id="boardCanvas"><div id="workoutList"></div><div id="boardMovingPen" aria-hidden="true" hidden><i class="marker-eraser"></i><i class="marker-tip"></i></div></div>
  <section class="unlock-board" aria-labelledby="unlockTitle"><h3 id="unlockTitle">Game unlocks</h3><ul id="rewardList"></ul></section>
 </div>
 <details class="account-settings"><summary>Account & appearance</summary><p id="accountName"></p><p id="accountStatus" class="hint" role="status"></p>
  <div id="accountSettingsContent" hidden><div class="actions"><button id="saveProfile">Save appearance</button><button id="restoreProfile">Restore appearance</button></div>
   <h3>Your data</h3><div class="actions"><button id="exportData">Download my data</button><a id="signOut" class="action-link" href="/signout-with-chatgpt?return_to=%2Fpose.html" target="_top">Sign out</a></div>
   <details><summary>Delete Coach data</summary><p>This deletes your Coach progress, meals, reminders and saved appearance from this account.</p><label>Type DELETE<input id="deleteConfirm" autocomplete="off"></label><button id="deleteAccount" class="danger">Delete Coach data</button></details>
  </div><p class="hint"><a href="/privacy.html">Privacy</a> · <a href="/source.json" download>App source</a> · <a href="/LICENSE">License</a></p>
 </details>
 <nav id="scoreboardMarkers" class="marker-tray" aria-label="Exercise focus markers"></nav>
</dialog>
<dialog id="installPanel" class="launch-panel" aria-labelledby="installTitle"><header><h2 id="installTitle">Device</h2><button data-close>Close</button></header><p id="installStatus" class="status" role="status"></p><button id="installApp" class="main-action" hidden>Add to home screen</button><details><summary>Install steps</summary><p>iPhone: Safari → Share → Add to Home Screen.</p><p>Android: browser menu → Install app.</p></details><section class="install-transfer" aria-labelledby="installTransferTitle"><h3 id="installTransferTitle">Scan to install</h3><img src="/icons/coach-install-qr.png" width="160" height="160" alt="QR code for myr5.mominc.online/install.html"><button id="shareCoach" class="main-action">Share Coach</button><p id="installShareStatus" role="status"></p></section><div class="switch-plate"><div><strong>OFFLINE VOICE</strong><small>13 MB · robot</small></div><button id="downloadVoice">Download</button></div><button id="applyUpdate" hidden>Install ready update</button></dialog>
`);for(const close of document.querySelectorAll('[data-close]'))close.onclick=()=>close.closest('dialog').close();for(const button of document.querySelectorAll('[data-panel]')){const panel=document.getElementById(button.dataset.panel+'Panel');button.setAttribute('aria-haspopup','dialog');button.setAttribute('aria-expanded','false');panel.addEventListener('close',()=>button.setAttribute('aria-expanded','false'));button.onclick=()=>{document.getElementById('stop')?.click();panel.showModal();button.setAttribute('aria-expanded','true');};}}
