import {FIELDS,SITE_QUESTIONS,EXERCISES,missingFields,dailyTargets,calendarDay} from './onboarding-domain.mjs?v=quick-install-v1';
import {mountOfficeQuickForm} from './office-quick-form.mjs?v=office-short-v1';
import {OFFICE_SECTIONS,OFFICE_REQUIRED_FIELDS,withOfficeDefaults} from './office-domain.mjs?v=office-short-v1';
import {mountOfficeAppearance} from './office-form.mjs?v=office-short-v1';
import {mountQuickSetup} from './quick-setup-form.mjs';
import {QUICK_REQUIRED_FIELDS} from './quick-setup.mjs';
const node=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e;};
export function mountProfileForm(host,initial,{save,label='Unlock my Coach app',changed=()=>{},fullSettings=false}){
 if(!fullSettings)return mountQuickSetup(host,initial,{save,label,changed});
 const data=initial.entryRoute==='office'?withOfficeDefaults(initial):structuredClone(initial);data.profile??={};data.answers??={};const form=node('form');form.className='setup-form';const status=node('p');status.role='status';const sections=[];const office=data.entryRoute==='office',quick=data.setupMode==='quick',customizer=office?mountOfficeAppearance(form,data):null;
 const basics=node('fieldset'),legend=node('legend',office?'A. Applicant & training particulars':'Your coach, ready for day one');basics.append(legend);const grid=node('div');grid.className='setup-fields';
 for(const field of FIELDS){const wrap=node('label',field.label);let input;if(field.options){input=node('select');input.append(new Option('Choose…',''));for(const value of field.options)input.append(new Option(value[0].toUpperCase()+value.slice(1),value));}else{input=node('input');input.type=field.type||'text';if(field.min!=null){input.min=field.min;input.max=field.max;input.step=field.key==='goalWeightLbs'?'0.1':'1';}input.maxLength=field.max||160;}input.name=field.key;input.required=quick?QUICK_REQUIRED_FIELDS.includes(field.key):!office||OFFICE_REQUIRED_FIELDS.includes(field.key);input.value=data.profile[field.key]??'';wrap.append(input);grid.append(wrap);}
 basics.append(grid);const movement=node('fieldset');movement.append(node('legend','Choose movements for your starting plan'));const choices=node('div');choices.className='setup-choices';for(const [key,label] of Object.entries(EXERCISES)){const l=node('label'),i=node('input');i.type='checkbox';i.name='exercises';i.value=key;i.checked=data.profile.exercises?.includes(key)||false;l.append(i,document.createTextNode(label));choices.append(l);}movement.append(choices,node('p','Choose movements that fit your space and limits. You can change these later.'));basics.append(movement);form.append(basics);
 for(const group of SITE_QUESTIONS){const details=node('details'),summary=node('summary',group.title);details.append(summary);for(let i=0;i<group.questions.length;i++){const name='q'+(i+1),label=node('label',group.questions[i]),input=node('textarea');input.name=group.id+'.'+name;input.rows=2;input.maxLength=2000;input.required=(!office&&!quick)||group.id==='armie'&&name==='q3';input.value=data.answers[group.id]?.[name]||'';label.append(input);details.append(label);}sections.push({group,details,summary});form.append(details);}
 if(customizer)form.append(customizer.appearance);const targets=node('p');targets.className='setup-targets';form.append(targets,node('p','Your answers and coach will be saved to your Coach account when you unlock it. “None” is a complete answer where appropriate. Everything here can be changed later.'));
 const submit=node('button',label);submit.type='submit';submit.className='setup-submit';form.append(status,submit);host.replaceChildren(form);
 function collect(){for(const f of FIELDS){const value=form.elements.namedItem(f.key).value;data.profile[f.key]=f.type==='number'?(value===''?null:Number(value)):value;}data.profile.exercises=[...form.querySelectorAll('[name=exercises]:checked')].map(e=>e.value);for(const g of SITE_QUESTIONS){data.answers[g.id]??={};for(let i=0;i<g.questions.length;i++)data.answers[g.id]['q'+(i+1)]=form.elements.namedItem(g.id+'.q'+(i+1)).value.trim();}customizer?.collect();return data;}
 function paint(){collect();const missing=missingFields(data);status.textContent=missing.length?`${missing.length} answer${missing.length===1?'':'s'} still needed. ${missing[0]}`:'Everything is filled in. Your coach is ready.';submit.disabled=missing.length>0;for(const {group,details,summary} of sections){const n=office||quick?(group.id==='armie'&&!data.answers.armie.q3?.trim()?1:0):group.questions.filter((_,i)=>!data.answers[group.id]['q'+(i+1)]?.trim()).length;summary.textContent=(office?OFFICE_SECTIONS[group.id]:group.title)+((office||quick)&&group.id!=='armie'?' · Optional':n?` · ${n} to answer`:' · Complete');if(n)details.open=true;}try{const t=dailyTargets(data.profile,calendarDay(Date.now(),data.profile.timezone));targets.textContent=`Day 1: 3 reps per movement · 9-second holds · +1 rep / +1 second each day. ${t.proteinGrams?`Daily targets: ${t.proteinGrams} g protein · ${t.waterOz} oz water.`:'Weight-based targets are optional.'}`;}catch{targets.textContent='Day 1: 3 reps per movement · 9-second holds · +1 rep / +1 second each day.';}customizer?.paint(missing.length,FIELDS.length+SITE_QUESTIONS.reduce((n,g)=>n+g.questions.length,0)+2);changed(structuredClone(data));}
 form.addEventListener('input',paint);form.addEventListener('change',paint);form.addEventListener('invalid',e=>{const details=e.target.closest('details');if(details)details.open=true;},true);
 form.onsubmit=async e=>{e.preventDefault();collect();if(missingFields(data).length||!form.reportValidity()){paint();return;}submit.disabled=true;status.textContent='Saving your coach…';try{await save(structuredClone(data));}catch(error){status.textContent=error.message;submit.disabled=false;}};paint();return {form,collect};
}
