// Generated by scripts/pose-samples.mjs from pose-samples/*.samples.json. Do not edit by hand.
// Exercises listed here count reps with the k-NN pose classifier; every other exercise uses the rules.
export default {};
