import {BUILD_ID} from './release-build.mjs';
export const RELEASE=Object.freeze({id:'2026-10-01-release-17-'+BUILD_ID,title:'Release 17: Stable coach and portal views',date:'2026-10-01',url:'https://myr5.mominc.online/repair-coach',notes:[
 'See-through portals: while a portal opens, you can already see where it leads in the middle of the wormhole.',
 'Your coach keeps going offline: voice cues fall back to captions and the exercise hologram to a wireframe figure, and both come back when you reconnect.',
 'Camera workouts sit inside the same metal MOM Inc housing and light strip as the other rooms, with the camera view left clear.',
 'The pod galaxy tilts with your interaction, while the controls follow with a smaller, delayed movement.',
 'Shaped portal cuts keep a clean outline on both the opening and falling piece, without jagged mesh triangles.',
 'Achievements, Food, Reminders, the school whiteboard, and the coach customizer keep the metal housing and feathered light strip. Button-opened menus tilt too, and the customizer uses the current navigation.',
 'Coach motion is permanently set to full intensity, with no intensity slider. Animation no longer builds up across frames and sends body parts off the platform.',
 'The training pod sits inside a lit ship interior, with a nebula turning slowly through the open viewport behind your controls.',
 'The ship lamps blink gently, and the top banner is a translucent purple hologram. Reduced-motion mode keeps the backdrop still.',
 'The Grass grimoire colour picker changes flower petals, including flowers already growing on the tablet. Grass and foliage stay green.',
 'Jelly trails, Cog lights, and Crystal cracks follow their selected grimoire colour. Ice is now named Crystal.',
 'The metal portal housing stays visible and keeps one colour through entry, exit, and full-screen rooms. Its light strip has a separate colour control.',
 'Phones stay in portrait mode where supported; other browsers ask you to turn the phone upright. Desktop layouts remain flexible.',
 'Opening Reminders through an animated portal keeps the scrollable controls fitted to the computer monitor.',
 'Meditate on a platform before a monochrome pixel forest, with the large four-legged coach peeking over the trees.',
 'Your own Gala pixel character can sit or stand; pose choices share the breathing controls, and the circle visibly follows each inhale and exhale with larger guidance text.',
 'One 3:30 guided round uses original subtitles and optional holds. Tap the circle to end without saving and let the big coach bounce you back out. The Tub Flight Easter egg is still there.',
 'The Reminders computer measures its screen after its layout is ready, refreshes older room styles, and keeps the controls available when 3D cannot load.',
 'Hold your hand over your coach for about a second to pick him up by the head, and he wiggles while you hold him.',
 'Partway through a set your coach charges at you and falls over. He nods if you stood firm, and laughs if you wobbled.',
 'Four-legged coaches still do their kick instead.',
 'Account setup and profile changes save more safely when you sign in or switch accounts.',
 'Board and profile artwork refresh safely when you change boards or accounts.',
 'Wormhole colors now follow the chosen board material, with a softer edge in full-screen views.',
 'Portal settings live in the top-left Grimoire menu, with a collapsible Full menu for the rest; Grass flowers stay aligned when the board resizes.',
 '24 named coach surfaces now show clear texture, including locked previews.',
 'Reminders opens in a new interactive 3D computer room with larger, easier-to-read controls.',
 'If a saved download belongs to an older release, Update Coach can recover it without removing your saved work.',
 'Camera workouts run offline: the pose tracker is part of the Starter download, or is kept after your first camera set online.',
 'Without the tracker offline, the camera start says to download Starter in Settings, Downloads.',
 'Rep counting is steadier on fast phones, and exercises follow one shared set of rules.',
 'The food scanner shows real USDA FoodData Central numbers for a meal-sized serving of each recognized dish.',
 'Coach, hand and roster models download smaller, and look the same.',
 'Menu hand gestures share the workout tracker files instead of downloading their own copy.',
 '"Any injuries or movement limits?" in setup is optional; leave it empty if there are none.'
]});
