import {grantDailyPack,openRewardPack,openedPack,unopenedPacks} from './reward-packs.mjs';

const CSS=`
.reward-pack-launch{position:fixed;right:16px;bottom:calc(18px + env(safe-area-inset-bottom,0px));z-index:9000;border:2px solid #fff4bd;border-radius:999px;background:#21182f;color:#fff4bd;padding:11px 17px;font:800 14px system-ui;box-shadow:0 8px 30px #0009;cursor:pointer}
.reward-pack-dialog{position:fixed;inset:0;z-index:10101;display:grid;place-items:center;background:#090717e8;color:#fff7df;font:500 16px/1.4 system-ui;padding:18px}.reward-pack-dialog[hidden],.reward-pack-launch[hidden]{display:none}
.reward-pack-card{width:min(100%,390px);max-height:calc(100dvh - 36px);overflow:auto;text-align:center;border:2px solid var(--pack);border-radius:24px;background:radial-gradient(circle at 50% 27%,color-mix(in srgb,var(--pack) 26%,#21152e),#13101e 73%);box-shadow:0 0 55px color-mix(in srgb,var(--pack) 35%,transparent);padding:18px 20px 22px}
.reward-pack-card h2{margin:4px 0 0;font:900 26px/1.1 system-ui;text-transform:uppercase;letter-spacing:.04em}.reward-pack-card .eyebrow{margin:0;color:var(--pack);font:800 12px system-ui;letter-spacing:.2em;text-transform:uppercase}.reward-pack-stage{height:min(46dvh,330px);min-height:220px;display:grid;place-items:center;position:relative;overflow:hidden}.reward-pack-stage:before{content:'';position:absolute;width:170px;height:170px;background:var(--pack);filter:blur(65px);opacity:.45}.reward-pack-stage canvas{position:relative;width:min(66vw,270px);height:min(66vw,270px);image-rendering:pixelated;filter:drop-shadow(0 14px 10px #000a)}.reward-pack-stage.opened canvas{animation:pack-pop .55s ease-out forwards}.reward-pack-result{min-height:70px;margin:3px 0 14px}.reward-pack-result strong{display:block;color:var(--pack);font-size:21px}.reward-pack-actions{display:flex;gap:9px;justify-content:center}.reward-pack-actions button{min-height:44px;border:2px solid var(--pack);border-radius:12px;background:var(--pack);color:#15101c;font:800 15px system-ui;padding:8px 18px;cursor:pointer}.reward-pack-actions button.secondary{background:transparent;color:#fff7df}.reward-pack-actions button:focus-visible,.reward-pack-launch:focus-visible{outline:3px solid white;outline-offset:3px}@keyframes pack-pop{45%{transform:scale(1.3) rotate(-12deg);filter:brightness(2)}100%{transform:scale(.72) rotate(18deg);opacity:.14}}@media(prefers-reduced-motion:reduce){.reward-pack-stage.opened canvas{animation:none;opacity:.2}}
`;
const COLORS={uncommon:'#76e356',rare:'#4bafff',legendary:'#ff9c36'};
const tierOf=id=>id.startsWith('reward-pack:')?id.split(':')[1]:'uncommon';
function renderer(canvas,tier){
 let disposed=false,raf=0,model=null,scene=null,renderer=null;
 (async()=>{try{
  const THREE=await import('three');const {GLTFLoader}=await import('three/addons/loaders/GLTFLoader.js');if(disposed)return;
  scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(36,1,.01,100);camera.position.set(0,.55,3.1);
  renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:false,powerPreference:'low-power'});renderer.setSize(64,64,false);renderer.setPixelRatio(1);
  scene.add(new THREE.AmbientLight(0xffffff,1.15));const lamp=new THREE.DirectionalLight(0xffffff,1.8);lamp.position.set(2,3,4);scene.add(lamp);
  const gltf=await new GLTFLoader().loadAsync('/reward-assets/canister.glb');if(disposed)return;model=gltf.scene;model.traverse(object=>{if(object.isMesh){const materials=Array.isArray(object.material)?object.material:[object.material];for(const material of materials)material.color?.set(COLORS[tier]);}});
  const box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());model.position.sub(center);model.scale.multiplyScalar(1.65/Math.max(size.x,size.y,size.z));scene.add(model);
  let last=0;const frame=now=>{if(disposed)return;raf=requestAnimationFrame(frame);if(document.hidden||now-last<33)return;last=now;model.rotation.y=now*.0012;model.rotation.z=Math.sin(now*.002)*.08;renderer.render(scene,camera);};raf=requestAnimationFrame(frame);
 }catch{canvas.hidden=true;canvas.parentElement.dataset.fallback='Canister preview unavailable';}})();
 return ()=>{disposed=true;cancelAnimationFrame(raf);renderer?.dispose();scene?.traverse(object=>{object.geometry?.dispose?.();if(object.material){const materials=Array.isArray(object.material)?object.material:[object.material];materials.forEach(material=>material.dispose?.());}});};
}
export function mountRewardPacks(){
 const style=document.createElement('style');style.textContent=CSS;document.head.append(style);
 const launch=document.createElement('button');launch.type='button';launch.className='reward-pack-launch';launch.hidden=true;document.body.append(launch);
 const overlay=document.createElement('div');overlay.className='reward-pack-dialog';overlay.hidden=true;overlay.innerHTML='<section class="reward-pack-card" role="dialog" aria-modal="true" aria-labelledby="pack-title"><p class="eyebrow">MYR5 • REWARD DROP</p><h2 id="pack-title"></h2><div class="reward-pack-stage"><canvas width="64" height="64" aria-label="Spinning pixel canister"></canvas></div><p class="reward-pack-result" role="status" aria-live="polite"></p><div class="reward-pack-actions"><button type="button" data-open>Open pack</button><button type="button" class="secondary" data-close>Later</button></div></section>';document.body.append(overlay);
 const card=overlay.querySelector('.reward-pack-card'),stage=overlay.querySelector('.reward-pack-stage'),result=overlay.querySelector('.reward-pack-result'),open=overlay.querySelector('[data-open]'),close=overlay.querySelector('[data-close]');let current=null,disposeModel=()=>{},lastFocus=null;
 const available=()=>unopenedPacks();function update(){const count=available().length;launch.hidden=!count;launch.textContent=`🎁 ${count} reward pack${count===1?'':'s'}`;}
 function hide(){overlay.hidden=true;disposeModel();current=null;lastFocus?.focus?.();update();}
 function show(id){current={kind:'reward-pack',id,tier:tierOf(id)};lastFocus=document.activeElement;card.style.setProperty('--pack',COLORS[current.tier]);overlay.querySelector('h2').textContent=`${current.tier} pack`;stage.classList.remove('opened');result.textContent='One cosmetic inside. Tap to open.';open.hidden=false;close.textContent='Later';overlay.hidden=false;disposeModel();const canvas=stage.querySelector('canvas');canvas.hidden=false;disposeModel=renderer(canvas,current.tier);open.focus();}
 launch.onclick=()=>{const id=available()[0];if(id)show(id);};close.onclick=hide;overlay.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();hide();}if(event.key==='Tab'){const buttons=[open,close].filter(button=>!button.hidden);const next=buttons[(buttons.indexOf(document.activeElement)+(event.shiftKey?buttons.length-1:1))%buttons.length];event.preventDefault();next.focus();}});
 open.onclick=()=>{if(!current)return;const opened=openRewardPack(current);if(!opened){result.textContent='Could not save this pack. Try again.';return;}stage.classList.add('opened');result.replaceChildren();const title=document.createElement('strong');title.textContent=`${opened.reward.name} unlocked!`;result.append(title,document.createTextNode(`${opened.category} reward`));open.hidden=true;close.textContent='Done';update();};
 const onGrant=event=>{if(event.detail?.granted?.some(item=>item.kind==='reward-pack'))update();};
 const onReady=event=>{grantDailyPack({account:event.detail});update();};
 window.addEventListener('myr5:battle-pass',onGrant);window.addEventListener('myr5:account-ready',onReady);window.addEventListener('myr5:account-cleared',hide);update();
 return ()=>{hide();window.removeEventListener('myr5:battle-pass',onGrant);window.removeEventListener('myr5:account-ready',onReady);window.removeEventListener('myr5:account-cleared',hide);launch.remove();overlay.remove();style.remove();};
}
