const SHELL='myr5-shell-hand-companion-v17',VOICE='myr5-voice-v1';
const FILES=["/handborne/assets/fflate.module-BTK1vOXE.js","/handborne/assets/GLTFExporter-CL_WC7Dc.js","/handborne/assets/hand-entry-B7K7J180.js","/handborne/assets/hand-entry-BySRDxUO.css","/handborne/assets/OBJExporter-J3SdsgWZ.js",'/hand-companion.mjs','/hand-companion.css','/handborne/companion.mjs','/handborne/index.html','/auth-client.mjs','/auth-paths.mjs','/device-notifications.mjs','/nutrition.mjs','/nutrition-data.mjs','/meal-nutrition.mjs','/reminder-live.mjs','/food-live.css','/icons/myr5-alien-apple.png','/icons/myr5-alien-maskable.png','/office-quick-form.mjs','/office-domain.mjs','/office-form.mjs','/onboarding-domain.mjs','/onboarding-questions.mjs','/coach-profile.mjs','/pose.html','/manifest.webmanifest','/menu.css','/launch.css','/launch.mjs','/launch-shell.mjs','/flip-display.mjs','/flip-display.css','/achievements.mjs','/app.mjs','/coach.mjs','/robot-audio.mjs','/camera.mjs','/menu.mjs','/movement-engine.mjs','/pod/pod.mjs','/pod/pod.css','/pod/set-flow.mjs','/pod/identity.mjs','/pod/encouragement.mjs','/pod/gala-avatar.js','/icons/myr5-alien-192.png','/icons/myr5-alien-512.png'];
FILES.push('/pocket-hardware.css','/reminder-settings.mjs','/reminder-controls.mjs','/meal-scanner.mjs','/food-worker.mjs','/icons/coach-install-qr.png','/pod/hardware.css','/pod/hardware.mjs','/hardware-launch.css','/pod/whiteboard.css','/pod/fonts/hand-0.woff2','/pod/fonts/hand-2.woff2','/pod/fonts/hand-6.woff2');
self.addEventListener('install',event=>event.waitUntil(caches.open(SHELL).then(cache=>cache.addAll(FILES))));
self.addEventListener('activate',event=>event.waitUntil((async()=>{for(const key of await caches.keys())if(key.startsWith('myr5-shell-')&&key!==SHELL)await caches.delete(key);await self.clients.claim();})()));
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting();});
self.addEventListener('fetch',event=>{const request=event.request,url=new URL(request.url);if(request.method!=='GET'||url.origin!==self.location.origin||url.pathname.startsWith('/api/')||url.pathname.includes('with-chatgpt')||url.pathname==='/callback'||url.pathname.startsWith('/signin')||url.pathname==='/source.json')return;
 if(url.pathname.startsWith('/voice/')){event.respondWith((async()=>{const cache=await caches.open(VOICE),cached=await cache.match(request);if(cached)return cached;const response=await fetch(request);if(response.ok&&!response.redirected)await cache.put(request,response.clone());return response;})());return;}
 if(request.mode==='navigate'){event.respondWith((async()=>{try{const response=await fetch(request);if(response.ok&&!response.redirected&&url.pathname.startsWith('/handborne'))await(await caches.open(SHELL)).put(request,response.clone());return response;}catch{return (await caches.match(request))||(await caches.match(url.pathname.startsWith('/handborne')?'/handborne/index.html':'/pose.html'));}})());return;}
 if(/\.(mjs|js|css|png|glb|woff2|webmanifest)$/.test(url.pathname)){event.respondWith((async()=>{const cached=await caches.match(request);if(cached)return cached;const response=await fetch(request);if(response.ok&&!response.redirected){const size=Number(response.headers.get('content-length'));if(size>0&&size<8*1024*1024)await(await caches.open(SHELL)).put(request,response.clone());}return response;})());}
});
self.addEventListener('push',event=>{let data={title:'MYR5 Coach',body:'Your coach has a reminder.',url:'/pose.html'};try{data={...data,...event.data.json()};}catch{}event.waitUntil(self.registration.showNotification(String(data.title).slice(0,80),{body:String(data.body).slice(0,200),icon:'/icons/myr5-alien-192.png',badge:'/icons/myr5-alien-192.png',tag:data.tag||'myr5-reminder',data:{url:data.url},renotify:false}));});
self.addEventListener('notificationclick',event=>{event.notification.close();event.waitUntil((async()=>{const url=new URL(event.notification.data?.url||'/pose.html',self.location.origin);if(url.origin!==self.location.origin)return;const all=await self.clients.matchAll({type:'window',includeUncontrolled:true});for(const client of all)if(new URL(client.url).origin===url.origin){await client.navigate(url.href);return client.focus();}return self.clients.openWindow(url.href);})());});
