import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {generateKeyPairSync,sign} from 'node:crypto';
import {readFile,readdir} from 'node:fs/promises';
import {Miniflare} from 'miniflare';
import worker from '../server/worker.mjs';
import {safeReturn} from '../auth-paths.mjs';
const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048});
const origin='https://coach.test',issuer='https://clerk.coach.test';
let mf,env;
before(async()=>{mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("ok")}}',d1Databases:['DB']});env={DB:await mf.getD1Database('DB'),CLERK_FRONTEND_URL:issuer,CLERK_AUTHORIZED_PARTIES:origin,CLERK_PUBLISHABLE_KEY:'pk_live_'+Buffer.from('clerk.coach.test$').toString('base64url'),CLERK_JWT_KEY:publicKey.export({type:'spki',format:'pem'})};for(const f of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())await env.DB.batch((await readFile('drizzle/'+f,'utf8')).split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean).map(s=>env.DB.prepare(s)));});
after(()=>mf?.dispose());
function token(sub='user_alice',claims={},key=privateKey){const now=Math.floor(Date.now()/1000);const data=[{alg:'RS256',typ:'JWT',kid:'test'},{v:2,sub,sid:'sess_test',iss:issuer,azp:origin,iat:now,nbf:now-2,exp:now+60,...claims}].map(x=>Buffer.from(JSON.stringify(x)).toString('base64url')).join('.');return data+'.'+sign('RSA-SHA256',Buffer.from(data),key).toString('base64url');}
async function request(path,{bearer,legacy,method='GET',data,requestOrigin=origin}={}){const r=await worker.fetch(new Request(origin+path,{method,headers:{...(bearer?{Authorization:'Bearer '+bearer}:{}),...(legacy?{'oai-authenticated-user-id':legacy}:{}),...(method!=='GET'?{'Content-Type':'application/json',Origin:requestOrigin}:{})},body:data?JSON.stringify(data):undefined}),env);return {status:r.status,data:await r.json()};}
test('valid Clerk sessions access their own saved data',async()=>{const r=await request('/api/account',{bearer:token()});assert.equal(r.status,200,JSON.stringify(r.data));assert.equal(r.data.user.id,'clerk:user_alice');assert.equal(r.data.user.provider,'clerk');await env.DB.prepare('INSERT INTO profiles(user_id,data,revision,updated_at) VALUES(?,?,1,1)').bind(r.data.user.id,JSON.stringify({saved:'alice'})).run();assert.deepEqual((await request('/api/account',{bearer:token('user_bob')})).data.profile,{});});
test('forged, expired, wrong issuer/origin, pending and incomplete tokens never fall back to an old session',async()=>{const wrong=generateKeyPairSync('rsa',{modulusLength:2048}).privateKey;for(const bearer of ['forged',token('user_alice',{},wrong),token('user_alice',{exp:1}),token('user_alice',{iss:'https://other.clerk.test'}),token('user_alice',{azp:'https://evil.test'}),token('user_alice',{azp:undefined}),token('user_alice',{sts:'pending'}),token('user_alice',{sid:null})])assert.equal((await request('/api/account',{bearer,legacy:'legacy_victim'})).status,401);});
test('legacy account access remains available',async()=>{assert.equal((await request('/api/account',{legacy:'legacy_kept'})).data.user.id,'legacy_kept');assert.equal((await request('/api/account')).status,401);});
test('linking requires both authenticated identities and same-origin confirmation',async()=>{for(const opts of [{legacy:'old_only'},{bearer:token('user_only')},{bearer:token('user_csrf'),legacy:'old_csrf',requestOrigin:'https://evil.test'}])assert.notEqual((await request('/api/auth/link',{method:'POST',data:{confirm:true},...opts})).status,200);assert.equal((await request('/api/auth/link',{method:'POST',bearer:token('user_no_confirm'),legacy:'old_no_confirm',data:{}})).status,400);});
test('linking keeps the original owner and data with repeat and concurrent requests',async()=>{await env.DB.prepare('INSERT INTO profiles(user_id,data,revision,updated_at) VALUES(?,?,1,1)').bind('old_coach',JSON.stringify({saved:'original coach'})).run();const opts={method:'POST',data:{confirm:true},bearer:token('user_linked'),legacy:'old_coach'};const replies=await Promise.all([request('/api/auth/link',opts),request('/api/auth/link',opts)]);assert(replies.every(r=>r.status===200));const account=await request('/api/account',{bearer:token('user_linked')});assert.equal(account.data.user.id,'old_coach');assert.equal(account.data.profile.saved,'original coach');assert.equal((await request('/api/auth/link',{...opts,bearer:token('user_thief')})).status,409);assert.equal((await request('/api/auth/link',{...opts,legacy:'different_old'})).status,409);});
test('existing separate accounts are never silently merged or overwritten',async()=>{await request('/api/account',{bearer:token('user_separate')});assert.equal((await request('/api/auth/link',{method:'POST',data:{confirm:true},bearer:token('user_separate'),legacy:'old_separate'})).status,409);});
test('return paths cannot redirect sign-in outside the app or into a login loop',()=>{for(const p of ['https://evil.test','//evil.test','/\\evil.test','/signin.html','/signout-with-chatgpt','/callback','/a\n'])assert.equal(safeReturn(p),'/pose.html');assert.equal(safeReturn('/onboarding.html?quick=1'),'/onboarding.html?quick=1');});
