import test from 'node:test';
import assert from 'node:assert/strict';
import {createPhoneMotionSource,screenGravity} from '../character-phone-sensor.mjs';
function fixture(permission=false){const events=new EventTarget(),doc=new EventTarget();doc.hidden=false;let time=0,calls=[];const store=new Map();const view={document:doc,performance:{now:()=>time},screen:{orientation:{angle:0}},localStorage:{getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)},addEventListener:events.addEventListener.bind(events),removeEventListener:events.removeEventListener.bind(events),DeviceMotionEvent:permission?{requestPermission:()=>{calls.push('motion');return Promise.resolve('granted');}}:{},DeviceOrientationEvent:permission?{requestPermission:()=>{calls.push('orientation');return Promise.resolve('granted');}}:{}};return {view,doc,calls,advance:n=>time+=n,send(type,values){const e=new Event(type);Object.assign(e,values);events.dispatchEvent(e);}};}
test('screen gravity follows screen rotation including upside down',()=>{assert.deepEqual(screenGravity(0,1),{gx:0,gy:1});assert.ok(Math.abs(screenGravity(0,1,90).gx-1)<1e-9);assert.ok(screenGravity(0,1,180).gy<-.99);});
test('gyroscope speed preserves a quick flip even after delayed sensor delivery',()=>{const f=fixture(),samples=[],off=createPhoneMotionSource(f.view,f.doc).subscribe(s=>samples.push(s));f.send('devicemotion',{accelerationIncludingGravity:{x:0,y:9.81,z:0}});f.advance(5000);f.send('devicemotion',{accelerationIncludingGravity:{x:-9.81,y:0,z:0},rotationRate:{alpha:900,beta:0,gamma:0}});assert.ok(samples[1].angularSpeed>15);off();});
test('motion detects full rotation and acceleration; orientation does not override fresh gravity',()=>{const f=fixture(),samples=[],off=createPhoneMotionSource(f.view,f.doc).subscribe(s=>samples.push(s));f.send('devicemotion',{accelerationIncludingGravity:{x:0,y:9.81,z:0},acceleration:{x:0,y:0,z:0}});f.advance(100);f.send('devicemotion',{accelerationIncludingGravity:{x:10.19,y:0,z:0},acceleration:{x:20,y:0,z:0}});assert.equal(samples[1].gx,1);assert.equal(samples[1].shake,20);assert.ok(samples[1].angularSpeed>10);f.send('deviceorientation',{beta:90,gamma:0});assert.equal(samples.length,2);off();f.send('devicemotion',{accelerationIncludingGravity:{x:0,y:-9,z:0}});assert.equal(samples.length,2);});
test('flat phone retains its gravity heading while still reporting shake and gyro',()=>{const f=fixture(),samples=[],off=createPhoneMotionSource(f.view,f.doc).subscribe(s=>samples.push(s));f.send('devicemotion',{accelerationIncludingGravity:{x:0,y:9.81,z:0},acceleration:{x:0,y:0,z:0}});f.advance(100);f.send('devicemotion',{accelerationIncludingGravity:{x:20,y:0,z:9.81},acceleration:{x:20,y:0,z:0},rotationRate:{alpha:0,beta:0,gamma:900}});assert.equal(samples.length,2);assert.equal(samples[1].gx,0);assert.equal(samples[1].gy,1);assert.equal(samples[1].shake,20);assert.ok(samples[1].angularSpeed>15);off();});
test('iOS requests both sensors synchronously in the existing Enable tilt tap',async()=>{const f=fixture(true),source=createPhoneMotionSource(f.view,f.doc),samples=[],off=source.subscribe(s=>samples.push(s));f.send('deviceorientation',{beta:90,gamma:0});assert.equal(samples.length,0);const result=source.request();assert.deepEqual(f.calls,['orientation','motion']);assert.equal(await result,true);f.send('deviceorientation',{beta:90,gamma:0});assert.equal(samples.length,1);f.doc.hidden=true;f.doc.dispatchEvent(new Event('visibilitychange'));f.send('deviceorientation',{beta:0,gamma:90});assert.equal(samples.length,1);off();});
