import test from 'node:test';
import assert from 'node:assert/strict';
import {GestureConfirmation,ExerciseRecognizer,handShape} from '../exercise-gestures.mjs';
function propose(g){for(let t=0;t<=800;t+=200)g.update({mode:'pushup'},t);}
test('a held thumbs-up cannot choose an exercise without a proposal',()=>{const g=new GestureConfirmation();for(let t=0;t<4000;t+=200)assert.notEqual(g.update({thumb:true},t).event,'confirmed');});
test('a stable proposal followed by a continuous held thumb confirms once',()=>{const g=new GestureConfirmation();propose(g);let confirmed=0;for(let t=1000;t<=4000;t+=200){const e=g.update({thumb:true},t);if(e.event==='confirmed'){confirmed++;assert.equal(e.mode,'pushup');}}assert.equal(confirmed,1);});
test('tracking loss or a released thumb resets confirmation progress',()=>{const g=new GestureConfirmation();propose(g);g.update({thumb:true},1000);g.update({thumb:true},1800);assert.equal(g.update({},2000).progress,0);assert.equal(g.update({thumb:true},2200).progress,0);assert.equal(g.update({thumb:true},4000).progress,0);});
test('ambiguous switching never proposes, and a proposal expires',()=>{const g=new GestureConfirmation();for(let t=0;t<2000;t+=200)assert.notEqual(g.update({mode:t%400?'tree':'horse'},t).event,'proposed');g.reset();propose(g);assert.equal(g.update({thumb:true},13000).event,'expired');});
function body(){const p=Array.from({length:33},()=>({x:.5,y:.5,visibility:1}));for(const [i,x,y] of [[11,.4,.35],[12,.6,.35],[13,.3,.45],[14,.7,.45],[15,.3,.6],[16,.7,.6],[23,.4,.7],[24,.6,.7]])p[i]={x,y,visibility:1};for(let i=25;i<33;i++)p[i]={x:.5,y:1.3,visibility:0};return p;}
const set=(p,i,x,y)=>p[i]={x,y,visibility:1};
test('distinct static gestures work with feet cropped out',()=>{for(const mode of ['squat','tree','jumping','warrior','horse']){const p=body();if(mode==='squat'){set(p,15,.4,.7);set(p,16,.6,.7);}if(mode==='tree'){set(p,15,.47,.1);set(p,16,.53,.1);}if(mode==='jumping'){set(p,15,.25,.1);set(p,16,.75,.1);}if(mode==='warrior'){set(p,15,.05,.35);set(p,16,.95,.35);}if(mode==='horse'){set(p,15,.47,.45);set(p,16,.53,.45);}assert.equal(new ExerciseRecognizer().update(p,[],0).mode,mode);}});
function fist(){const p=Array.from({length:21},()=>({x:.65,y:.47}));p[0]={x:.65,y:.58};for(const i of [5,9,13,17])p[i]={x:.65+(i-9)*.002,y:.48};for(const i of [6,10,14,18])p[i]={x:.65+(i-10)*.002,y:.45};for(const i of [8,12,16,20])p[i]={x:.65+(i-12)*.002,y:.50};p[3]={x:.69,y:.48};p[4]={x:.7,y:.49};return p;}
test('thumb shape distinguishes a fist and rejects clipped hands',()=>{const p=fist();assert.equal(handShape(p).thumb,false);p[4]={x:.69,y:.35};assert.equal(handShape(p).thumb,true);p[4].y=-.1;assert.equal(handShape(p),null);});
test('raised arm plus other index pointing at upper arm proposes push-ups',()=>{const p=body();set(p,13,.28,.32);set(p,15,.27,.15);set(p,16,.57,.4);const hand=fist().map(v=>({x:v.x-.08,y:v.y-.18}));hand[6]={x:.50,y:.36};hand[8]={x:.37,y:.34};assert.equal(handShape(hand).point,true);assert.equal(new ExerciseRecognizer().update(p,[hand],0).mode,'pushup');});
test('two raised fists propose boxing and alternating arm pumps propose jogging',()=>{const p=body();set(p,15,.35,.3);set(p,16,.65,.3);assert.equal(new ExerciseRecognizer().update(p,[fist(),fist()],0).mode,'boxing');const r=new ExerciseRecognizer();let result;for(let i=0;i<6;i++){const b=body();set(b,15,.3,i%2?.55:.3);set(b,16,.7,i%2?.3:.55);result=r.update(b,[],i*300);}assert.equal(result.mode,'jogging');});
