import test from 'node:test';
import assert from 'node:assert/strict';
import {mountGuestHistoryChoice} from '../guest-history-choice.mjs';
class Element{constructor(tag){this.tag=tag;this.children=[];this.listeners={};}append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=nodes;}setAttribute(){}addEventListener(name,fn){this.listeners[name]=fn;}click(){if(!this.disabled)this.listeners.click?.();}}
const all=node=>[node,...node.children.flatMap(all)];
const settle=()=>new Promise(resolve=>setTimeout(resolve,0));
function setup(t){const prior=globalThis.document;globalThis.document={createElement:tag=>new Element(tag),createTextNode:text=>Object.assign(new Element('text'),{textContent:text})};t.after(()=>globalThis.document=prior);const host=new Element('section'),calls=[],listeners=new Set(),selected={user:{id:'A'},dataEpoch:1},rows=[{workout:{clientWorkoutId:'one',mode:'squat',completedAt:1000},selectable:true,status:'unassigned'}];const adapter={history:async()=>rows,stop(){},choose:async(...args)=>calls.push(args),upload:async()=>calls.push('upload'),reconcileDeletedTarget:async()=>calls.push('proof')};const transitions={subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn);}};return{host,calls,adapter,selected,rows,transitions,listeners};}
test('history mount and dismissal create no choice or upload; selection sends displayed destination',async t=>{const f=setup(t),view=mountGuestHistoryChoice({...f,getAccount:()=>f.selected});await view.render();assert.deepEqual(f.calls,[]);const checkbox=all(f.host).find(n=>n.tag==='input');checkbox.checked=true;checkbox.listeners.change();all(f.host).find(n=>n.textContent==='Save import choice for selected workouts').click();await settle();assert.deepEqual(f.calls,[['import',['one'],f.selected]]);assert.equal(all(f.host).some(n=>n.textContent==='Import saved choices'),false);view.close();assert.equal(f.host.children.length,0);assert.equal(f.calls.length,1);});
test('transition invalidates delayed rendering and removes clickable old account choices',async t=>{const f=setup(t);let resolve;f.adapter.history=()=>new Promise(r=>resolve=r);const view=mountGuestHistoryChoice({...f,getAccount:()=>f.selected}),pending=view.render();f.listeners.forEach(fn=>fn());resolve(f.rows);await pending;assert.equal(f.host.children.length,0);assert.equal(f.calls.length,0);view.close();});
test('empty selection never commits and keep-local remains available without account',async t=>{const f=setup(t),view=mountGuestHistoryChoice({...f,getAccount:()=>null});await view.render();all(f.host).find(n=>n.textContent==='Keep selected workouts local').click();await settle();assert.equal(f.calls.length,0);assert(all(f.host).some(n=>n.textContent==='Select between one and 100 workouts.'));const box=all(f.host).find(n=>n.tag==='input');box.checked=true;box.listeners.change();all(f.host).find(n=>n.textContent==='Keep selected workouts local').click();await settle();assert.deepEqual(f.calls,[['keep_local',['one'],null]]);view.close();});
