import test from 'node:test';
import assert from 'node:assert/strict';
import {PinchGesture,cursorPoint} from '../hand-gesture.mjs';
function hand(closed=false,aspect=1){const p=Array.from({length:21},()=>({x:.5,y:.6}));for(const [i,x,y] of [[0,.5,.8],[5,.43,.58],[9,.49,.55],[13,.55,.58],[17,.60,.63],[8,.4,.5],[12,.49,.25],[16,.55,.3],[20,.63,.4],[4,closed?.401:.25,closed?.50:.6]])p[i]={x:x/aspect,y};return p;}
test('arriving already pinched cannot click until an open hand is observed',()=>{const g=new PinchGesture();for(let t=100;t<1000;t+=66){const p=g.update(hand(true),t);assert.equal(p.pinched,false);assert.equal(p.down,false);}g.update(hand(),1100);const p=g.update(hand(true),1166);assert.equal(p.down,true);});
test('one pinch cycle creates one down and one release, including held frames',()=>{const g=new PinchGesture();g.update(hand(),100);let down=0,up=0;for(let t=166;t<=760;t+=66){const p=g.update(hand(true),t);down+=+p.down;up+=+p.up;}const p=g.update(hand(),826);up+=+p.up;assert.equal(down,1);assert.equal(up,1);assert.equal(p.pinched,false);});
test('lost tracking cancels the pinch and requires rearming',()=>{const g=new PinchGesture();g.update(hand(),100);g.update(hand(true),166);assert.equal(g.update(null,232),null);const p=g.update(hand(true),298);assert.equal(p.down,false);assert.equal(p.up,false);assert.equal(p.armed,false);});
test('a long camera gap cancels an in-progress pinch',()=>{const g=new PinchGesture();g.update(hand(),100);g.update(hand(true),166);const p=g.update(hand(true),1000);assert.equal(p.pinched,false);assert.equal(p.up,false);});
test('a pinch folding into a fist is canceled without a click release',()=>{const g=new PinchGesture();g.update(hand(),100);g.update(hand(true),166);const fist=hand(true);for(const i of [4,8,12,16,20])fist[i]={x:.49,y:.68};let p;for(let t=232;t<=430;t+=66)p=g.update(fist,t);assert.equal(p.pinched,false);assert.equal(p.canceled,true);assert.equal(p.up,false);});
test('portrait and landscape aspect give the same pinch decisions',()=>{for(const aspect of [.75,1,1.78]){const g=new PinchGesture();g.update(hand(false,aspect),100,aspect);assert.equal(g.update(hand(true,aspect),166,aspect).down,true);}});
test('cursor mapping mirrors the front camera and remains within menu bounds',()=>{const rect={left:10,top:20,width:400,height:800};assert.equal(cursorPoint({x:.12,y:.08},rect).x,10);assert.equal(cursorPoint({x:.12,y:.08},rect,true).x,410);assert.deepEqual(cursorPoint({x:2,y:-1},rect),{x:410,y:20});});
