import test from 'node:test';
import assert from 'node:assert/strict';
import {indexedDB,IDBKeyRange,IDBObjectStore} from 'fake-indexeddb';
import {openLocalCoach,LocalCoachStorageError} from '../local-coach/repository.mjs';
import {openGuestWorkoutAdapter,probeOptionalAccount,probeOptionalTransfer} from '../local-coach/browser-runtime.mjs';
import {ManualActiveClock,ManualStartGate} from '../local-coach/manual-clock.mjs';
import {SetFlow} from '../pod/set-flow.mjs';
import {WorkoutSessionOwner} from '../pod/workout-session-owner.mjs';
import {restoreInstall} from '../install-transfer.mjs';
import {authSettings} from '../auth-client.mjs';
import {completeCoach} from './onboarding-fixture.mjs';
import {readFile} from 'node:fs/promises';

let sequence=0;
const name=()=>`myr5-chunk2-${++sequence}`;
const ids=prefix=>{let value=0;return {randomUUID:()=>`${prefix}-${++value}`};};
const cryptos=new Map(),open=nameValue=>options=>openLocalCoach({name:nameValue,indexedDB,IDBKeyRange,cryptoObject:cryptos.get(nameValue)??(cryptos.set(nameValue,ids('row')),cryptos.get(nameValue)),...options});
const memory=()=>{const values=new Map();return {getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,String(value)),removeItem:key=>values.delete(key)};};
class Bus{constructor(){this.channels=[];}open(){const listeners=new Set(),channel={addEventListener:(type,fn)=>listeners.add(fn),removeEventListener:(type,fn)=>listeners.delete(fn),postMessage:value=>{if(channel.closed)return;for(const peer of this.channels)if(peer!==channel&&!peer.closed)for(const fn of peer.listeners)fn({data:value});},close(){this.closed=true;listeners.clear();},listeners};this.channels.push(channel);return channel;}}
const adapter=({db,storage=memory(),bus=new Bus(),clock={value:1_000},wait=async()=>{},setIntervalFn=()=>1,clearIntervalFn=()=>{},tabId=`tab-${++sequence}`,openRepository=open(db??name())}={})=>openGuestWorkoutAdapter({exerciseKeys:['squat','tree','knee-pushup'],open:openRepository,storage,channelFactory:()=>bus.open(),now:()=>clock.value,wait,setIntervalFn,clearIntervalFn,tabId});

test('local setup is atomic and preserves the first local start day across edits',async()=>{
 const db=name(),repo=await open(db)(),scope=repo.forOwner(repo.guestOwnerId),first=completeCoach();
 assert.equal((await scope.saveSetup(first,{startDay:'2026-09-20'})).settings.startDay,'2026-09-20');
 const edited=completeCoach();edited.profile.name='Edited';assert.equal((await scope.saveSetup(edited,{startDay:'2030-01-01'})).settings.startDay,'2026-09-20');assert.equal((await scope.getIntake()).profile.name,'Edited');repo.close();
 const failed=await open(name())(),failedScope=failed.forOwner(failed.guestOwnerId),original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,key){if(this.name==='settings')throw new DOMException('full','QuotaExceededError');return original.call(this,value,key);};
 try{await assert.rejects(()=>failedScope.saveSetup(completeCoach(),{startDay:'2026-09-20'}),error=>error instanceof LocalCoachStorageError&&error.code==='quota');}finally{IDBObjectStore.prototype.put=original;}
 assert.equal(await failedScope.getIntake(),null);failed.close();
});

test('manual workout pauses, resumes the same id, completes once, and persists history and outbox',async()=>{
 const db=name(),client=await adapter({db});const started=await client.start({mode:'knee-pushup',goal:2,restSeconds:60,control:'manual',metadata:{name:'Knee push-up'}});await client.update(started.id,{value:1});await client.pause(started.id,{value:1});
 const resumed=await client.start({mode:'knee-pushup',goal:2,restSeconds:60,control:'manual'});assert.equal(resumed.id,started.id);assert.equal(resumed.resumed,true);await client.complete(started.id,{value:2,elapsedSeconds:4,earned:true,progress:{value:2}});client.close();
 const reopened=await open(db)(),scope=reopened.forOwner(reopened.guestOwnerId),rows=await scope.listWorkouts(),events=await scope.listEvents(started.id);assert.equal(rows.length,1);assert.equal(rows[0].status,'completed');assert.deepEqual(events.map(event=>event.type),['started','updated','updated','paused','resumed','completed']);assert.equal((await scope.listOutbox()).length,1);reopened.close();
});

test('manual active clock excludes hidden and paused time',()=>{let now=0,visible=true;const clock=new ManualActiveClock({now:()=>now,visible:()=>visible});clock.start();now=5_000;assert.equal(clock.sample(),5);visible=false;now=25_000;assert.equal(clock.sample(),5);visible=true;now=27_000;assert.equal(clock.sample(),7);clock.pause();now=37_000;assert.equal(clock.sample(),7);});

test('fresh foreign heartbeat blocks all mutation and recovery while stale active recovers and paused remains',async()=>{
 const db=name(),storage=memory(),bus=new Bus(),clock={value:100_000},first=await adapter({db,storage,bus,clock}),active=await first.start({mode:'squat',goal:3,restSeconds:60,control:'camera'}),second=await adapter({db,storage,bus,clock});await assert.rejects(()=>second.start({mode:'tree',goal:9,restSeconds:60,control:'manual'}),error=>error.code==='lease');await assert.rejects(()=>second.complete(active.id,{value:3}),error=>error.code==='lease');assert.equal((await open(db)()).forOwner(first.ownerId).ownerId,first.ownerId);second.close();first.close();
 const seed=await open(db)(),scope=seed.forOwner(seed.guestOwnerId),paused=await scope.startWorkout({mode:'tree',goal:9,metadata:{control:'manual'}});await scope.pauseWorkout(paused.id);const stale=await scope.startWorkout({mode:'squat',goal:3,metadata:{control:'camera'}});seed.close();storage.setItem(`myr5-local-workout-heartbeat:${scope.ownerId}:${scope.deviceId}`,JSON.stringify({tabId:'old',at:1}));clock.value=1_000_000;const recovered=await adapter({db,storage,bus:new Bus(),clock}),check=await open(db)(),checkScope=check.forOwner(check.guestOwnerId);assert.equal((await checkScope.getWorkout(stale.id)).status,'interrupted');assert.equal((await checkScope.getWorkout(paused.id)).status,'paused');recovered.close();check.close();
});

test('a lower-id zombie cannot mutate after a stale takeover by a higher-id winner',async()=>{
 const db=name(),storage=memory(),bus=new Bus(),clock={value:100_000},timers=new Map();let timerId=0;
 const setIntervalFn=fn=>{const id=++timerId;timers.set(id,fn);return id;},clearIntervalFn=id=>timers.delete(id);
 const zombie=await adapter({db,storage,bus,clock,setIntervalFn,clearIntervalFn,tabId:'tab-a-zombie'}),w1=await zombie.start({mode:'squat',goal:3,restSeconds:60,control:'manual'}),heartbeatKey=`myr5-local-workout-heartbeat:${zombie.ownerId}:${zombie.deviceId}`;
 assert.equal(JSON.parse(storage.getItem(heartbeatKey)).tabId,'tab-a-zombie');timers.clear();bus.channels[0].close();
 clock.value=159_999;const early=await adapter({db,storage,bus,clock,tabId:'tab-z-early'});await assert.rejects(()=>early.start({mode:'tree',goal:9,restSeconds:60,control:'manual'}),error=>error.code==='lease');early.close();
 clock.value=160_001;const winner=await adapter({db,storage,bus,clock,tabId:'tab-z-winner'}),w2=await winner.start({mode:'tree',goal:9,restSeconds:60,control:'manual'});assert.equal(JSON.parse(storage.getItem(heartbeatKey)).tabId,'tab-z-winner');assert.equal(winner.snapshot().held,true);
 for(const mutate of [()=>zombie.update(w1.id,{value:1}),()=>zombie.pause(w1.id,{value:1}),()=>zombie.resume(w1.id),()=>zombie.complete(w1.id,{value:3}),()=>zombie.interrupt(w1.id,{value:1}),()=>zombie.start({mode:'squat',goal:3,restSeconds:60,control:'manual'})])await assert.rejects(mutate,error=>error.code==='lease');
 await winner.update(w2.id,{value:1});winner.close();zombie.close();const check=await open(db)(),scope=check.forOwner(check.guestOwnerId);assert.equal((await scope.getWorkout(w1.id)).status,'interrupted');assert.deepEqual((await scope.listEvents(w1.id)).map(event=>event.type),['started','interrupted']);assert.equal((await scope.getWorkout(w2.id)).progress.value,1);assert.deepEqual((await scope.listEvents(w2.id)).map(event=>event.type),['started','updated']);assert.deepEqual(await scope.listOutbox(),[]);check.close();
});

test('a held completion revalidates its durable fence after takeover and cannot commit',async()=>{
 const db=name(),storage=memory(),bus=new Bus(),clock={value:100_000},timers=new Map();let timerId=0,releaseCompletion,completionEntered;const held=new Promise(resolve=>releaseCompletion=resolve),entered=new Promise(resolve=>completionEntered=resolve),baseOpen=open(db);
 const heldOpen=async options=>{const repository=await baseOpen(options);return {...repository,forOwner(ownerId){const scope=repository.forOwner(ownerId);return {...scope,async completeWorkout(...args){completionEntered();await held;return scope.completeWorkout(...args);}};}};};
 const zombie=await adapter({db,storage,bus,clock,openRepository:heldOpen,setIntervalFn:fn=>{const id=++timerId;timers.set(id,fn);return id;},clearIntervalFn:id=>timers.delete(id),tabId:'tab-a-zombie'}),w1=await zombie.start({mode:'squat',goal:3,restSeconds:60,control:'manual'}),delayed=zombie.complete(w1.id,{value:3});await entered;timers.clear();bus.channels[0].close();clock.value=160_001;
 const winner=await adapter({db,storage,bus,clock,tabId:'tab-z-winner'}),w2=await winner.start({mode:'tree',goal:9,restSeconds:60,control:'manual'});releaseCompletion();await assert.rejects(()=>delayed,error=>error.code==='lease');await winner.update(w2.id,{value:1});
 const check=await open(db)(),scope=check.forOwner(check.guestOwnerId);assert.equal((await scope.getWorkout(w1.id)).status,'interrupted');assert.deepEqual((await scope.listEvents(w1.id)).map(event=>event.type),['started','interrupted']);assert.deepEqual(await scope.listOutbox(),[]);assert.equal((await scope.getWorkout(w2.id)).status,'active');assert.equal((await scope.getWorkout(w2.id)).progress.value,1);assert.equal(winner.snapshot().held,true);check.close();winner.close();zombie.close();
});

test('simultaneous claims elect exactly one holder and the loser remains live after release',async()=>{
 const db=name(),storage=memory(),bus=new Bus(),clock={value:5_000};let racing=false;const counts=new Map(),arrivals=[[],[]];
 const waitFor=tab=>async()=>{if(!racing)return;const phase=counts.get(tab)||0;counts.set(tab,phase+1);if(phase>1)return;await new Promise(resolve=>{arrivals[phase].push(resolve);if(arrivals[phase].length===2){const batch=arrivals[phase].splice(0);queueMicrotask(()=>batch.forEach(done=>done()));}});};
 const a=await adapter({db,storage,bus,clock,wait:waitFor('tab-a'),tabId:'tab-a'}),b=await adapter({db,storage,bus,clock,wait:waitFor('tab-b'),tabId:'tab-b'});racing=true;
 const results=await Promise.allSettled([a.start({mode:'squat',goal:3,restSeconds:60,control:'manual'}),b.start({mode:'tree',goal:9,restSeconds:60,control:'manual'})]),fulfilled=results.filter(result=>result.status==='fulfilled'),rejected=results.filter(result=>result.status==='rejected');assert.equal(fulfilled.length,1);assert.equal(rejected.length,1);assert.equal(rejected[0].reason.code,'lease');assert.equal(a.snapshot().held,true);assert.equal(b.snapshot().held,false);
 const winnerWorkout=fulfilled[0].value;await a.update(winnerWorkout.id,{value:1});await assert.rejects(()=>b.update(winnerWorkout.id,{value:2}),error=>error.code==='lease');await a.interrupt(winnerWorkout.id,{value:1});const later=await b.start({mode:'tree',goal:9,restSeconds:60,control:'manual'});assert.equal(b.snapshot().held,true);await b.interrupt(later.id,{value:0});a.close();b.close();
 const check=await open(db)(),scope=check.forOwner(check.guestOwnerId),rows=await scope.listWorkouts();assert.equal(rows.length,2);assert.equal(rows.filter(row=>row.status==='active').length,0);assert.deepEqual(await scope.listOutbox(),[]);check.close();
});

test('a second tab cannot complete or create a second outbox row',async()=>{const db=name(),storage=memory(),bus=new Bus(),clock={value:2_000},first=await adapter({db,storage,bus,clock}),second=await adapter({db,storage,bus,clock}),workout=await first.start({mode:'squat',goal:3,restSeconds:60,control:'manual'});await assert.rejects(()=>second.complete(workout.id,{value:3}),error=>error.code==='lease');await first.complete(workout.id,{value:3});first.close();second.close();const repo=await open(db)(),scope=repo.forOwner(repo.guestOwnerId);assert.equal((await scope.listEvents(workout.id)).filter(event=>event.type==='completed').length,1);assert.equal((await scope.listOutbox()).length,1);repo.close();});

test('camera interruption is durable and produces no completion or outbox',async()=>{const db=name(),client=await adapter({db}),workout=await client.start({mode:'squat',goal:3,restSeconds:60,control:'camera'});await client.interrupt(workout.id,{value:0});client.close();const repo=await open(db)(),scope=repo.forOwner(repo.guestOwnerId);assert.equal((await scope.getWorkout(workout.id)).status,'interrupted');assert.deepEqual((await scope.listEvents(workout.id)).map(event=>event.type),['started','updated','interrupted']);assert.deepEqual(await scope.listOutbox(),[]);repo.close();});

test('completion write failure never becomes local success, history, or an outbox row',async()=>{const db=name(),client=await adapter({db}),workout=await client.start({mode:'squat',goal:3,restSeconds:60,control:'manual'}),original=IDBObjectStore.prototype.add;IDBObjectStore.prototype.add=function(value,key){if(this.name==='outbox')throw new DOMException('full','QuotaExceededError');return original.call(this,value,key);};try{await assert.rejects(()=>client.complete(workout.id,{value:3}),error=>error instanceof LocalCoachStorageError&&error.code==='quota');}finally{IDBObjectStore.prototype.add=original;}assert.deepEqual(await client.history(),[]);client.close();const repo=await open(db)(),scope=repo.forOwner(repo.guestOwnerId);assert.equal((await scope.getWorkout(workout.id)).status,'active');assert.deepEqual(await scope.listOutbox(),[]);repo.close();});

test('cold offline reopen reads completed history through a new database handle',async()=>{const db=name(),first=await adapter({db}),workout=await first.start({mode:'squat',goal:3,restSeconds:60,control:'manual',metadata:{name:'Squats'}});await first.complete(workout.id,{value:3});first.close();const freshPage=await adapter({db,storage:memory(),bus:new Bus()});const history=await freshPage.history();assert.equal(history.length,1);assert.equal(history[0].id,workout.id);assert.equal(history[0].completion.value,3);freshPage.close();});

test('fully offline auth and install probes fall through while 4xx and local DB errors remain blocking',async()=>{const originalFetch=globalThis.fetch,session=memory(),local=memory();session.setItem('keep','draft');try{globalThis.fetch=async()=>{throw new TypeError('Failed to fetch');};assert.equal(await probeOptionalAccount(()=>authSettings()),null);assert.equal(await probeOptionalTransfer(()=>restoreInstall(globalThis.fetch,session,local)),null);assert.equal(session.getItem('keep'),'draft');globalThis.fetch=async()=>new Response(JSON.stringify({error:'unavailable'}),{status:503,headers:{'content-type':'application/json'}});assert.equal(await probeOptionalAccount(()=>authSettings()),null);assert.equal(await probeOptionalTransfer(()=>restoreInstall(globalThis.fetch,session,local)),null);globalThis.fetch=async()=>new Response(JSON.stringify({error:'denied'}),{status:403,headers:{'content-type':'application/json'}});await assert.rejects(()=>probeOptionalAccount(()=>authSettings()),error=>error.status===403&&error.code==='auth-config');await assert.rejects(()=>probeOptionalTransfer(()=>restoreInstall(globalThis.fetch,session,local)),error=>error.status===403);await assert.rejects(()=>probeOptionalAccount(()=>Promise.reject(Object.assign(Error('account denied'),{status:403}))),error=>error.status===403);const localError=new LocalCoachStorageError('unavailable','local-db-open-failed');await assert.rejects(()=>probeOptionalAccount(()=>Promise.reject(localError)),error=>error===localError);}finally{globalThis.fetch=originalFetch;}const source=await readFile(new URL('../onboarding.mjs',import.meta.url),'utf8');assert.match(source,/account=await probeOptionalAccount\(\(\{signal\}\)=>api\('\/api\/account\?core=1','GET',undefined,\{\},signal\)\);\s*localCoach=await openLocalCoach\(\)/);assert.match(source,/account\?await restoreInstall\(\):await probeOptionalTransfer\(\(\{signal\}\)=>restoreInstall\(fetch,sessionStorage,localStorage,\{signal\}\)\)/);assert.match(source,/catch\(error\)\{localCoach\.close\(\);localCoach=null;throw error;\}/);});

test('hide and pagehide during manual begin serialize one durable pause before close and resume the same id',async()=>{const db=name(),client=await adapter({db}),gate=new ManualStartGate();let releaseBegin,releasePause,rowReady,activeId=null,pauseCalls=0,closeCalls=0;const beginBarrier=new Promise(resolve=>releaseBegin=resolve),pauseBarrier=new Promise(resolve=>releasePause=resolve),durableRow=new Promise(resolve=>rowReady=resolve);const starting=gate.run(async()=>{const workout=await client.start({mode:'squat',goal:3,restSeconds:60,control:'manual'});activeId=workout.id;rowReady();await beginBarrier;return workout;});await durableRow;const pause=()=>gate.pause(async()=>{pauseCalls++;await pauseBarrier;await client.pause(activeId,{value:1});});const hidden=pause(),pagehide=pause().finally(()=>{closeCalls++;client.close();});assert.equal(pauseCalls,0);assert.equal(closeCalls,0);releaseBegin();await starting;await new Promise(resolve=>queueMicrotask(resolve));assert.equal(pauseCalls,1);assert.equal(closeCalls,0);releasePause();await Promise.all([hidden,pagehide]);assert.equal(pauseCalls,1);assert.equal(closeCalls,1);const fresh=await adapter({db,storage:memory(),bus:new Bus()}),resumed=await fresh.start({mode:'squat',goal:3,restSeconds:60,control:'manual'});assert.equal(resumed.id,activeId);fresh.close();const check=await open(db)(),scope=check.forOwner(check.guestOwnerId);assert.deepEqual((await scope.listEvents(activeId)).map(event=>event.type),['started','updated','paused','resumed']);assert.equal((await scope.getWorkout(activeId)).status,'active');assert.deepEqual(await scope.listOutbox(),[]);check.close();const app=await readFile(new URL('../app.mjs',import.meta.url),'utf8');assert.match(app,/state\.phase='manual-starting'/);assert.match(app,/state\.phase==='manual'\|\|state\.phase==='manual-starting'\)void pauseManualWhenReady\(\)/);});

test('rejected cross-movement manual start preserves the paused workout owner and same-id resume',async()=>{
 const db=name(),client=await adapter({db}),flow=new SetFlow(),owner=new WorkoutSessionOwner({storage:memory()}),modes={squat:{name:'Squats'},tree:{name:'Tree pose'}};let pausedLocal=null;
 const interruptCurrent=async()=>{const id=flow.active?.localId;if(id)await client.interrupt(id,flow.active.savedProgress??{});if(flow.phase==='set')flow.leave();pausedLocal=null;owner.stop();};
 const beginSet=async mode=>{pausedLocal=await client.paused();if(pausedLocal&&pausedLocal.mode!==mode)throw Error('Resume or complete the paused manual workout first.');const ownerStarted=!pausedLocal;if(ownerStarted&&!owner.start())throw Error('Workout activation is in progress. Try again.');let ticket=null;try{ticket=await client.start({mode,goal:mode==='tree'?9:3,restSeconds:60,progress:pausedLocal?.progress??{},metadata:{name:modes[mode].name},control:'manual'});flow.start(mode,ticket.goal,60);flow.active.localId=ticket.id;flow.active.savedProgress=ticket.progress??{};pausedLocal=null;return ticket;}catch(error){if(ticket){await client.interrupt(ticket.id,ticket.progress??{}).catch(()=>{});if(flow.phase==='set'&&flow.active?.localId===ticket.id)flow.leave();pausedLocal=null;}if(ownerStarted||ticket)owner.stop();throw error;}};
 const startManual=async mode=>{let ticket=null;try{ticket=await beginSet(mode);return ticket;}catch(error){if(ticket)await interruptCurrent();throw error;}};
 const started=await startManual('squat');await client.update(started.id,{value:1});await client.pause(started.id,{value:1});flow.leave();pausedLocal=await client.paused();assert.equal(owner.snapshot().phase,'active');
 await assert.rejects(()=>startManual('tree'),/Resume or complete the paused manual workout first/);assert.equal((await client.paused()).id,started.id);assert.equal(owner.snapshot().phase,'active');assert.equal(owner.acquireIdleLease(),null);
 const resumed=await startManual('squat');assert.equal(resumed.id,started.id);await interruptCurrent();client.close();
 const check=await open(db)(),scope=check.forOwner(check.guestOwnerId);assert.equal((await scope.getWorkout(started.id)).status,'interrupted');assert.deepEqual((await scope.listEvents(started.id)).map(event=>event.type),['started','updated','updated','paused','resumed','updated','interrupted']);assert.deepEqual(await scope.listOutbox(),[]);check.close();
 const app=await readFile(new URL('../app.mjs',import.meta.url),'utf8');assert.match(app,/let ticket=null;try\{ticket=await pod\.beginSet[\s\S]*?if\(ticket\)await pod\.interruptCurrent/);
});

test('camera hide and pagehide during held begin interrupt the new row before adapter close',async()=>{
 const db=name(),client=await adapter({db}),flow=new SetFlow(),owner=new WorkoutSessionOwner({storage:memory()});let releaseStart,startEntered;const held=new Promise(resolve=>releaseStart=resolve),entered=new Promise(resolve=>startEntered=resolve),workouts={...client,async start(options){startEntered();await held;return client.start(options);}};let generation=0,phase='idle',cameraStartTransition=Promise.resolve(),closed=false;
 const beginSet=async()=>{if(!owner.start())throw Error('Workout activation is in progress. Try again.');try{const ticket=await workouts.start({mode:'squat',goal:3,restSeconds:60,control:'camera'});flow.start('squat',3,60);flow.active.localId=ticket.id;flow.active.savedProgress=ticket.progress??{};return ticket;}catch(error){owner.stop();throw error;}};
 const interruptCurrent=async()=>{const id=flow.active?.localId;if(id)await client.interrupt(id,flow.active.savedProgress??{});if(flow.phase==='set')flow.leave();owner.stop();};
 const startCamera=async()=>{const run=++generation;phase='camera';let settleCameraStart;cameraStartTransition=new Promise(resolve=>{settleCameraStart=resolve;});try{await beginSet();if(run!==generation){await interruptCurrent();return;}phase='tracking';}catch(error){if(run!==generation){await interruptCurrent().catch(()=>{});return;}throw error;}finally{settleCameraStart();}};
 const stop=()=>{const unfinished=['camera','model','tracking'].includes(phase);generation++;phase='idle';return unfinished?interruptCurrent():Promise.resolve();};
 const starting=startCamera();await entered;const hidden=stop(),pagehide=Promise.allSettled([stop(),cameraStartTransition]).then(()=>{closed=true;client.close();});assert.equal(closed,false);releaseStart();await Promise.all([starting,hidden,pagehide]);assert.equal(closed,true);assert.equal(phase,'idle');assert.equal(owner.snapshot().phase,'idle');assert.equal(flow.phase,'pod');
 const check=await open(db)(),scope=check.forOwner(check.guestOwnerId),rows=await scope.listWorkouts();assert.equal(rows.length,1);assert.equal(rows[0].status,'interrupted');assert.deepEqual((await scope.listEvents(rows[0].id)).map(event=>event.type),['started','updated','interrupted']);assert.deepEqual(await scope.listOutbox(),[]);check.close();
 const app=await readFile(new URL('../app.mjs',import.meta.url),'utf8');assert.match(app,/if\(run!==generation\)\{await pod\.interruptCurrent\(state\.motion\);return;\}/);assert.match(app,/Promise\.allSettled\(\[stopped,cameraStartTransition\]\)\.then\(\(\)=>workouts\.close\(\)\)/);
});

test('manual branch bypasses camera, tracker import, WebGL, voice, packs, and network',async()=>{const app=await readFile(new URL('../app.mjs',import.meta.url),'utf8'),pod=await readFile(new URL('../pod/pod.mjs',import.meta.url),'utf8'),manual=app.slice(app.indexOf('function startManual(){'),app.indexOf('async function activateManual(){'));assert.match(app,/if\(\$\('camera'\)\.value==='manual'\)return startManual\(\);/);assert.match(app,/\$\('camera'\)\.value==='manual'\?start\(\):library\.introduce\(\)/);assert.match(pod,/if\(!manual\)warmVoice/);assert.ok(app.indexOf("if($('camera').value==='manual')return startManual();")<app.indexOf('navigator.mediaDevices?.getUserMedia'));for(const forbidden of ['getUserMedia','openCamera','import(','WebGL','voice.','fetch(','library.','packs/'])assert.equal(manual.includes(forbidden),false,forbidden);assert.match(app,/catch\(error\)\{[\s\S]*?await pod\.interruptCurrent\(state\.motion\)/);});
