import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { webcrypto } from 'node:crypto';
import { createRequire } from 'node:module';
const { chromium } = createRequire(import.meta.url)('C:/Users/ianmy/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');

const root = path.resolve(import.meta.dirname, '..');
const enc = new TextEncoder();
const hex = b => [...new Uint8Array(b)].map(x => x.toString(16).padStart(2, '0')).join('');
const stable = x => Array.isArray(x) ? x.map(stable) : x && typeof x === 'object' ? Object.fromEntries(Object.keys(x).sort().map(k => [k, stable(x[k])])) : x;
const canonicalMaterial = m => JSON.stringify(stable({ schema:m.schema,packId:m.packId,version:m.version,minAppVersion:m.minAppVersion,sha256:m.sha256,alg:m.alg,keyId:m.keyId,materialId:m.materialId,runtimeType:m.runtimeType,parameters:m.parameters,assets:m.assets.map(({path,bytes,sha256})=>({path,bytes,sha256})) }));
const canonicalChunks = m => JSON.stringify(stable({ schema:'mom-material-chunks-v1',packId:m.packId,version:m.version,keyId:m.keyId,assets:m.assets.map(a=>({path:a.path,bytes:a.bytes,sha256:a.sha256,chunks:a.chunks.map(c=>({index:c.index,offset:c.offset,bytes:c.bytes,sha256:c.sha256,url:c.url,etag:c.etag}))})) }));
const b64 = b => Buffer.from(b).toString('base64');

async function fixture(origin, { large = false, chunks = 1, version = '1.0.0', config = { hue: 286, strength: .8 } } = {}) {
  const keys = await webcrypto.subtle.generateKey({ name:'Ed25519', namedCurve:'Ed25519' }, true, ['sign','verify']);
  const publicKey = await webcrypto.subtle.exportKey('jwk', keys.publicKey);
  const bytes = large ? new Uint8Array(32 * 1024 * 1024) : enc.encode(JSON.stringify(config));
  const digest = hex(await webcrypto.subtle.digest('SHA-256', bytes));
  const packId = 'liquid-amethyst', keyId = 'mom-material-production-v1', url = `${origin}/materials/${packId}/${version}/config.json`;
  const manifest = { schema:'mom-material-pack-v1', packId, version, minAppVersion:'1.0.0', sha256:digest, alg:'Ed25519', keyId, materialId:packId, runtimeType:'liquid-v1', parameters:{ hue:278, strength:.6 }, assets:[{path:'assets/config.json',bytes:bytes.byteLength,sha256:digest}] };
  manifest.signature = b64(await webcrypto.subtle.sign('Ed25519', keys.privateKey, enc.encode(canonicalMaterial(manifest))));
  const size=Math.ceil(bytes.byteLength/chunks), records=[]; for(let offset=0,index=0;offset<bytes.byteLength;offset+=size,index++){const part=bytes.slice(offset,Math.min(bytes.byteLength,offset+size));records.push({index,offset,bytes:part.byteLength,sha256:hex(await webcrypto.subtle.digest('SHA-256',part)),url,etag:'"fixture-v1"'});}
  const chunkManifest = { schema:'mom-material-chunks-v1',packId,version,keyId,assets:[{path:'assets/config.json',bytes:bytes.byteLength,sha256:digest,chunks:records}] };
  chunkManifest.signature = b64(await webcrypto.subtle.sign('Ed25519', keys.privateKey, enc.encode(canonicalChunks(chunkManifest))));
  return { source:'browser-fixture', manifest, chunkManifest, testTrust:{purpose:'test-only-signed-material',publicKey}, policy:{maxChunkBytes: bytes.byteLength, maxAssetBytes:64*1024*1024, maxPackBytes:64*1024*1024, maxAssets:16, maxChunksPerAsset:256, trustedOrigins:[origin], allowedProtocols:['http:'], pathPrefix:'/materials/'}, bytes };
}

function server() {
  const counters = { requests:0, bytes:0, ranges:[] }; let payload = new Uint8Array(), delayStart = -1;
  const s = http.createServer((req,res) => { if (req.url === '/test.html') { res.writeHead(200,{'content-type':'text/html'}); return res.end('<!doctype html><main><section id="materialControls"><output data-material-status></output><button data-material-download>Download</button><button data-material-cancel>Cancel</button><button data-material-equip>Equip</button></section><div id="materialRuntime"></div></main>'); } if (req.url.startsWith('/modules/') || req.url.startsWith('/packs/') || req.url.startsWith('/public-access.mjs')) { const file=path.join(root,req.url.replace(/^\//,'')); if(fs.existsSync(file)){res.writeHead(200,{'content-type':'text/javascript'});return res.end(fs.readFileSync(file));} } if (!req.url.startsWith('/materials/')) { res.writeHead(404); return res.end(); } const range=/bytes=(\d+)-(\d+)/.exec(req.headers.range||'');const start=Number(range?.[1]||0),end=Number(range?.[2]||payload.byteLength-1),part=payload.slice(start,end+1); counters.requests++; counters.ranges.push(req.headers.range || ''); const send=()=>{res.writeHead(206, {'content-type':'application/octet-stream','content-length':part.byteLength,'content-range':`bytes ${start}-${end}/${payload.byteLength}`,'etag':'"fixture-v1"','access-control-allow-origin':'*'}); counters.bytes += part.byteLength; res.end(part);}; if(start===delayStart)return setTimeout(send,150);send(); });
  return { s, counters, setPayload(v){payload=v}, delayAt(v){delayStart=v} };
}

const account = id => ({user:{id},entitlements:{coachArmy:{status:'completed',completedAt:1}},ownedPacks:[{packId:'liquid-amethyst',status:'owned',grantedAt:1}]});
const idleOwner = () => ({snapshot:()=>({phase:'idle',revision:1}),save:async()=>true,acquireIdleLease:()=>({revision:1}),releaseIdleLease:()=>{}});

test('IndexedDB partial resume equips only after an actual later page boot and restores active on a third boot', async t => {
  const h=server(); await new Promise(r=>h.s.listen(0,'127.0.0.1',r)); t.after(()=>h.s.close()); const origin=`http://127.0.0.1:${h.s.address().port}`,fx=await fixture(origin,{chunks:2}); h.setPayload(fx.bytes);
  const browser=await chromium.launch({channel:'msedge',headless:true}); t.after(()=>browser.close()); const context=await browser.newContext(); t.after(()=>context.close()); const p=await context.newPage();
  const boot=async()=>{await p.evaluate(f=>window.__fx=f,fx);return p.evaluate(async()=>{const m=await import('/modules/materials/material-controller.mjs'),d=await import('/modules/materials/chunk-delivery.mjs');window.__c=new m.MaterialController({account:{user:{id:'acct-a'},entitlements:{coachArmy:{status:'completed',completedAt:1}},ownedPacks:[{packId:'liquid-amethyst',status:'owned',grantedAt:1}]},workoutOwner:{snapshot:()=>({phase:'idle',revision:1}),save:async()=>true,acquireIdleLease:()=>({revision:1}),releaseIdleLease:()=>{}},host:document.getElementById('materialRuntime'),storage:localStorage,chunkStore:d.indexedDbChunkStore({database:'p13n-resume'}),fetchImpl:fetch,policy:window.__fx.policy});await window.__c.load({fixture:window.__fx,testTrust:window.__fx.testTrust});return window.__c.bootId})};
  await p.goto(`${origin}/test.html`); const first=await boot(); h.delayAt(fx.chunkManifest.assets[0].chunks[1].offset);
  const cancelled=await p.evaluate(async()=>{const pending=window.__c.download();setTimeout(()=>window.__c.cancel(),25);try{await pending;return ''}catch(e){return e.message}}); assert.match(cancelled,/cancelled/i);
  h.delayAt(-1); await p.reload(); const second=await boot(); assert.notEqual(second,first); await p.evaluate(async()=>{await window.__c.download();await window.__c.equipAfterRestart();await window.__c.restorePending({fixture:window.__fx,testTrust:window.__fx.testTrust})});
  assert.equal(await p.locator('#materialRuntime canvas').count(),0, 'a pending candidate cannot activate in its creating document');
  await p.reload(); const third=await boot(); assert.notEqual(third,second); await p.evaluate(()=>window.__c.restorePending({fixture:window.__fx,testTrust:window.__fx.testTrust})); assert.equal(await p.locator('#materialRuntime canvas').count(),1);
  await p.reload(); const fourth=await boot(); assert.notEqual(fourth,third); await p.evaluate(()=>window.__c.restoreActive({fixture:window.__fx,testTrust:window.__fx.testTrust})); assert.equal(await p.locator('#materialRuntime canvas').count(),1);
  assert.equal(h.counters.requests,3); assert.ok(h.counters.bytes <= fx.bytes.byteLength*2); assert.match(h.counters.ranges[0],/bytes=0-/);
});

test('actual IndexedDB corrupt replacement preserves installed runtime and reload restores the old active material', async t => {
  const h=server(); await new Promise(r=>h.s.listen(0,'127.0.0.1',r));t.after(()=>h.s.close());const origin=`http://127.0.0.1:${h.s.address().port}`,good=await fixture(origin,{config:{hue:286,strength:.8}}),candidate=await fixture(origin,{version:'2.0.0',config:{hue:302,strength:.3}}); const browser=await chromium.launch({channel:'msedge',headless:true});t.after(()=>browser.close());const p=await browser.newPage();
  await p.goto(`${origin}/test.html`); await p.evaluate(x=>window.__fx=x,good); h.setPayload(good.bytes);
  const installed=await p.evaluate(async()=>{const m=await import('/modules/materials/material-controller.mjs'),d=await import('/modules/materials/chunk-delivery.mjs');const c=new m.MaterialController({account:{user:{id:'acct-a'},entitlements:{coachArmy:{status:'completed',completedAt:1}},ownedPacks:[{packId:'liquid-amethyst',status:'owned',grantedAt:1}]},workoutOwner:{snapshot:()=>({phase:'idle',revision:1}),save:async()=>true,acquireIdleLease:()=>({revision:1}),releaseIdleLease:()=>{}},host:document.getElementById('materialRuntime'),storage:localStorage,chunkStore:d.indexedDbChunkStore({database:'p13n-corrupt'}),fetchImpl:fetch,policy:window.__fx.policy});await c.load({fixture:window.__fx,testTrust:window.__fx.testTrust});await c.download();await c.equipAfterRestart();return c.bootId});
  await p.reload();await p.evaluate(x=>window.__fx=x,good);const before=await p.evaluate(async()=>{const m=await import('/modules/materials/material-controller.mjs'),d=await import('/modules/materials/chunk-delivery.mjs');window.__c=new m.MaterialController({account:{user:{id:'acct-a'},entitlements:{coachArmy:{status:'completed',completedAt:1}},ownedPacks:[{packId:'liquid-amethyst',status:'owned',grantedAt:1}]},workoutOwner:{snapshot:()=>({phase:'idle',revision:1}),save:async()=>true,acquireIdleLease:()=>({revision:1}),releaseIdleLease:()=>{}},host:document.getElementById('materialRuntime'),storage:localStorage,chunkStore:d.indexedDbChunkStore({database:'p13n-corrupt'}),fetchImpl:fetch,policy:window.__fx.policy});await window.__c.load({fixture:window.__fx,testTrust:window.__fx.testTrust});await window.__c.restorePending({fixture:window.__fx,testTrust:window.__fx.testTrust});return window.__c.runtime.getDebug().hue});assert.equal(before,286);
  const corrupt=new Uint8Array(candidate.bytes);corrupt[0]^=1;h.setPayload(corrupt);await p.evaluate(x=>window.__candidate=x,candidate);const failure=await p.evaluate(async()=>{try{await window.__c.load({fixture:window.__candidate,testTrust:window.__candidate.testTrust});await window.__c.download();return ''}catch(e){return e.message}});assert.match(failure,/hash/i);assert.equal(await p.evaluate(()=>window.__c.runtime.getDebug().hue),286);
  await p.reload();await p.evaluate(x=>window.__fx=x,good);const restored=await p.evaluate(async()=>{const m=await import('/modules/materials/material-controller.mjs'),d=await import('/modules/materials/chunk-delivery.mjs');const c=new m.MaterialController({account:{user:{id:'acct-a'},entitlements:{coachArmy:{status:'completed',completedAt:1}},ownedPacks:[{packId:'liquid-amethyst',status:'owned',grantedAt:1}]},host:document.getElementById('materialRuntime'),storage:localStorage,chunkStore:d.indexedDbChunkStore({database:'p13n-corrupt'}),fetchImpl:fetch,policy:window.__fx.policy});await c.load({fixture:window.__fx,testTrust:window.__fx.testTrust});await c.restoreActive({fixture:window.__fx,testTrust:window.__fx.testTrust});return c.runtime.getDebug().hue});assert.equal(restored,286);
});

test('offline and cancelled replacements retain an installed runtime; account switch and revoke dispose it', async t => {
  const h=server();await new Promise(r=>h.s.listen(0,'127.0.0.1',r));t.after(()=>h.s.close());const origin=`http://127.0.0.1:${h.s.address().port}`,fx=await fixture(origin,{chunks:2}),replacement=await fixture(origin,{chunks:2,version:'2.0.0',config:{hue:302,strength:.3}});h.setPayload(fx.bytes);const browser=await chromium.launch({channel:'msedge',headless:true});t.after(()=>browser.close());const p=await browser.newPage();await p.goto(`${origin}/test.html`);await p.evaluate(x=>window.__fx=x,fx);
  const initial=await p.evaluate(async replacement=>{const m=await import('/modules/materials/material-controller.mjs'),d=await import('/modules/materials/chunk-delivery.mjs');const a={user:{id:'acct-a'},entitlements:{coachArmy:{status:'completed',completedAt:1}},ownedPacks:[{packId:'liquid-amethyst',status:'owned',grantedAt:1}]},store=d.memoryChunkStore(),owner={snapshot:()=>({phase:'idle',revision:1}),save:async()=>true,acquireIdleLease:()=>({revision:1}),releaseIdleLease:()=>{}},c=new m.MaterialController({account:a,workoutOwner:owner,host:document.getElementById('materialRuntime'),chunkStore:store,fetchImpl:fetch,policy:window.__fx.policy});await c.load({fixture:window.__fx,testTrust:window.__fx.testTrust});await c.download();await c.activate(c.bundle,c.record().candidate);const offline=new m.MaterialController({account:a,host:document.getElementById('materialRuntime'),chunkStore:store,fetchImpl:fetch,policy:window.__fx.policy});await offline.load({fixture:replacement,testTrust:replacement.testTrust});offline.downloader=()=>new d.ChunkDownloader({store,fetchImpl:fetch,policy:window.__fx.policy,expectedVersion:replacement.manifest.version,manifestPublicKey:replacement.testTrust.publicKey,ownership:async()=>a.user.id,online:()=>false});let offlineError='';try{await offline.download()}catch(e){offlineError=e.message}window.__c=c;window.__a=a;window.__store=store;window.__replacement=replacement;return {installed:c.runtime.getDebug().hue,offlineError}},replacement);
  h.setPayload(replacement.bytes);h.delayAt(replacement.chunkManifest.assets[0].chunks[1].offset);
  const result=await p.evaluate(async()=>{const c=window.__c;await c.load({fixture:window.__replacement,testTrust:window.__replacement.testTrust});const pending=c.download();setTimeout(()=>c.cancel(),25);let cancelError='';try{await pending}catch(e){cancelError=e.message}const survives=c.runtime.getDebug().hue;window.__a.user.id='acct-b';let switched='';try{c.assertLive()}catch(e){switched=e.message}const canvasAfterSwitch=document.querySelectorAll('#materialRuntime canvas').length;const {MaterialController}=await import('/modules/materials/material-controller.mjs');const revoking=new MaterialController({account:{user:{id:'acct-a'},entitlements:{coachArmy:{status:'completed',completedAt:1}},ownedPacks:[{packId:'liquid-amethyst',status:'owned',grantedAt:1}]},host:document.getElementById('materialRuntime'),chunkStore:window.__store,fetchImpl:fetch,policy:window.__fx.policy});await revoking.load({fixture:window.__fx,testTrust:window.__fx.testTrust});await revoking.restoreActive({fixture:window.__fx,testTrust:window.__fx.testTrust});const revokeHue=revoking.runtime.getDebug().hue;revoking.revoke();return {cancelError,survives,switched,canvasAfterSwitch,owner:c.owner,revokeHue,revokeCanvas:document.querySelectorAll('#materialRuntime canvas').length,oldRecord:revoking.record().active}});
  result.installed=initial.installed;result.offlineError=initial.offlineError;
  assert.equal(result.installed,286);assert.match(result.offlineError,/offline/i);assert.match(result.cancelError,/cancelled/i);assert.equal(result.survives,286);assert.match(result.switched,/revoked|changed/i);assert.equal(result.canvasAfterSwitch,0);assert.equal(result.owner,'acct-a');assert.equal(result.revokeHue,286);assert.equal(result.revokeCanvas,0);assert.equal(result.oldRecord,null);
});

test('trusted signed config bytes visibly change the renderer, while oversized config is rejected before download allocation', async t => {
  const h=server();await new Promise(r=>h.s.listen(0,'127.0.0.1',r));t.after(()=>h.s.close());const origin=`http://127.0.0.1:${h.s.address().port}`,first=await fixture(origin,{config:{hue:286,strength:.8}}),second=await fixture(origin,{version:'2.0.0',config:{hue:302,strength:.3}}),oversized=await fixture(origin,{large:true});const browser=await chromium.launch({channel:'msedge',headless:true});t.after(()=>browser.close());const p=await browser.newPage();await p.goto(`${origin}/test.html`);h.setPayload(first.bytes);
  const hues=await p.evaluate(async fixtures=>{const m=await import('/modules/materials/material-controller.mjs'),d=await import('/modules/materials/chunk-delivery.mjs'),a={user:{id:'acct-a'},entitlements:{coachArmy:{status:'completed',completedAt:1}},ownedPacks:[{packId:'liquid-amethyst',status:'owned',grantedAt:1}]},owner={snapshot:()=>({phase:'idle',revision:1}),save:async()=>true,acquireIdleLease:()=>({revision:1}),releaseIdleLease:()=>{}};const install=async fixture=>{const c=new m.MaterialController({account:a,workoutOwner:owner,host:document.getElementById('materialRuntime'),chunkStore:d.memoryChunkStore(),fetchImpl:fetch,policy:fixture.policy});await c.load({fixture,testTrust:fixture.testTrust});await c.download();await c.activate(c.bundle,c.record().candidate);return c.runtime.getDebug().hue};const one=await install(fixtures.first);window.__next=fixtures.second;return {one}} ,{first,second});assert.equal(hues.one,286);h.setPayload(second.bytes);
  const changed=await p.evaluate(async fixture=>{const m=await import('/modules/materials/material-controller.mjs'),d=await import('/modules/materials/chunk-delivery.mjs'),a={user:{id:'acct-a'},entitlements:{coachArmy:{status:'completed',completedAt:1}},ownedPacks:[{packId:'liquid-amethyst',status:'owned',grantedAt:1}]},c=new m.MaterialController({account:a,workoutOwner:{snapshot:()=>({phase:'idle',revision:1}),save:async()=>true,acquireIdleLease:()=>({revision:1}),releaseIdleLease:()=>{}},host:document.getElementById('materialRuntime'),chunkStore:d.memoryChunkStore(),fetchImpl:fetch,policy:fixture.policy});await c.load({fixture,testTrust:fixture.testTrust});await c.download();await c.activate(c.bundle,c.record().candidate);return c.runtime.getDebug().hue},second);assert.equal(changed,302);
  const before=h.counters.requests;const tooLarge=await p.evaluate(async fixture=>{const {MaterialController}=await import('/modules/materials/material-controller.mjs');const c=new MaterialController({account:{user:{id:'acct-a'},entitlements:{coachArmy:{status:'completed',completedAt:1}},ownedPacks:[{packId:'liquid-amethyst',status:'owned',grantedAt:1}]},host:document.getElementById('materialRuntime'),fetchImpl:fetch,policy:fixture.policy});try{await c.load({fixture,testTrust:fixture.testTrust});return ''}catch(e){return e.message}},oversized);assert.match(tooLarge,/manifest signature/i);assert.equal(h.counters.requests,before,'oversized config is rejected before any response buffer is allocated');
});
