import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {runInNewContext} from 'node:vm';
import {MessageChannel} from 'node:worker_threads';
const source=await readFile('sw.js','utf8'),core={url:'/core.mjs',integrity:'sha256-test',bytes:4},optional={url:'/creature/model.glb',integrity:'sha256-model',bytes:16};
function fixture(fetcher=async()=>new Response('core')){
 const handlers={},stores=new Map(),calls=[],name=(source.match(/const SHELL='([^']+)'/)||[])[1];let skips=0,clients=[];
 const caches={async keys(){return [...stores.keys()];},async delete(key){return stores.delete(key);},async open(key){if(!stores.has(key))stores.set(key,new Map());const map=stores.get(key),path=value=>typeof value==='string'?new URL(value,'https://test').pathname:new URL(value.url).pathname;return{async match(k){return map.get(path(k))?.clone();},async put(k,v){map.set(path(k),v.clone());},async delete(k){return map.delete(path(k));},async keys(){return [...map.keys()].map(k=>new Request('https://test'+k));}};}};
 const self={location:{origin:'https://test'},addEventListener:(k,fn)=>handlers[k]=fn,skipWaiting:async()=>skips++,clients:{matchAll:async()=>clients,claim:async()=>{}},registration:{}};
 runInNewContext(source.replace('/* OFFLINE_ASSETS */ []',JSON.stringify([core])).replace('/* OPTIONAL_ASSETS */ []',JSON.stringify([optional])),{self,caches,URL,Request,Response,Headers,crypto,MessageChannel,setTimeout:(fn,ms)=>setTimeout(fn,Math.min(ms,20)),clearTimeout,fetch:async request=>{calls.push(request);return fetcher(request);}});
 return{handlers,caches,stores,calls,name,setClients:value=>clients=value,get skips(){return skips;},async event(type,input={}){let pending;handlers[type]({...input,waitUntil:p=>pending=p});await pending;}};
}
test('failed atomic core install removes candidate and retains prior complete shell',async()=>{const f=fixture(async()=>new Response('fail',{status:503})),old=await f.caches.open('myr5-shell-old');await old.put('/__myr5_offline_assets__',Response.json([{...core,integrity:'sha256-old'}]));await old.put('/core.mjs',new Response('old'));await assert.rejects(f.event('install'));assert.equal(f.stores.has(f.name),false);assert.equal(await(await old.match('/core.mjs')).text(),'old');});
test('core install requests no optional model; activation retains one prior complete generation',async()=>{const f=fixture();for(const id of ['ancient','prior'])await(await f.caches.open('myr5-shell-'+id)).put('/__myr5_offline_assets__',Response.json([]));await f.event('install');assert.deepEqual(f.calls.map(r=>new URL(r.url).pathname),['/core.mjs']);await f.event('activate');assert(f.stores.has('myr5-shell-prior'));assert(!f.stores.has('myr5-shell-ancient'));});
test('unverified core failure returns503 and never retries without integrity',async()=>{const f=fixture(async()=>{throw Error('SRI mismatch');});let response;f.handlers.fetch({request:new Request('https://test/core.mjs'),respondWith:p=>response=p,waitUntil(){}});assert.equal((await response).status,503);assert.equal(f.calls.length,1);assert.equal(f.calls[0].integrity,core.integrity);});
test('force messages never activate while old windows remain, even if every window claims safe',async()=>{const f=fixture();f.setClients([{id:'a',postMessage(){}}]);await f.event('message',{data:{type:'SKIP_WAITING'}});let reply;await f.event('message',{data:{type:'PREPARE_UPDATE'},ports:[{postMessage:value=>reply=value}]});assert.equal(f.skips,0);assert.equal(reply.reason,'busy');});
test('optional resources are intercepted on demand, cached separately and do not enter core',async()=>{const f=fixture();let response,pending;f.handlers.fetch({request:new Request('https://test/creature/model.glb'),respondWith:p=>response=p,waitUntil:p=>pending=p});assert(response);assert.equal((await response).status,200);await pending;assert(f.stores.has('myr5-optional-'+f.name.slice('myr5-shell-'.length)));assert.equal(f.stores.has(f.name),false);assert.equal(f.calls[0].integrity,optional.integrity);});

function readyClient(id,{safe=true,onConfirm=()=>{}}={}){return {id,url:'https://test/pose.html',postMessage(data,ports){if(data.type==='UPDATE_ABORT')return;if(data.type==='UPDATE_CONFIRM')onConfirm();ports[0].postMessage({safe,protocol:2,id:data.id});ports[0].close();}};}
test('idle prepared clients activate together without closing windows',async()=>{const f=fixture(),a=readyClient('a'),b=readyClient('b');f.setClients([a,b]);let reply;await f.event('message',{data:{type:'PREPARE_UPDATE'},source:a,ports:[{postMessage:v=>reply=v}]});assert.equal(f.skips,1);assert.equal(reply.activated,true);});
test('an active or unresponsive client blocks automatic activation',async()=>{for(const b of [readyClient('b',{safe:false}),{id:'b',url:'https://test/pose.html',postMessage(){}}]){const f=fixture(),a=readyClient('a');f.setClients([a,b]);let reply;await f.event('message',{data:{type:'PREPARE_UPDATE'},source:a,ports:[{postMessage:v=>reply=v}]});assert.equal(f.skips,0);assert.equal(reply.activated,false);}});
test('a window arriving during preparation prevents activation',async()=>{const f=fixture(),b=readyClient('b'),a=readyClient('a',{onConfirm:()=>f.setClients([a,b])});f.setClients([a]);await f.event('message',{data:{type:'PREPARE_UPDATE'},source:a,ports:[{postMessage(){}}]});assert.equal(f.skips,0);});
