import test from 'node:test';
import assert from 'node:assert/strict';
import {savedPerformanceRecords,reconcilePerformanceWorkouts} from '../performance-reconcile.mjs';
import {recordPerformanceSession,recordDailyActivity} from '../performance-progress.mjs';
const day='2026-10-04';
const completion=(id='one',changes={})=>({id,mode:'shallow-squat',status:'completed',completedAt:new Date(`${day}T12:00:00`).getTime(),completion:{earned:true},progress:{performanceOwner:'account:one:1',performance:{id,mode:'shallow-squat',kind:'reps',difficulty:'easy',value:1,xpBase:1,performanceOwner:'account:one:1'}},...changes});
function context(){const map=new Map();return {owner:'account:one:1',storage:{getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)}};}
test('committed completion missing reward cache repairs once, preserving daily multipliers',()=>{const o=context();recordDailyActivity('meditation',{day},o);recordDailyActivity('food',{day},o);let result=reconcilePerformanceWorkouts([completion()],o);assert.equal(result.replayed,1);assert.equal(result.progress.totalXp,502);result=reconcilePerformanceWorkouts([completion(),completion()],o);assert.equal(result.replayed,0);assert.equal(result.progress.totalXp,502);});
test('legacy, foreign, previous epoch, prep, unfinished and unearned rows never mint rewards',()=>{const foreign=completion('foreign');foreign.progress.performance.performanceOwner='account:two:1';const epoch=completion('epoch');epoch.progress.performance.performanceOwner='account:one:0';const prep=completion('prep');prep.progress.performance.preparation=true;const unearned=completion('unearned',{completion:{earned:false}});const rows=[completion('legacy',{progress:{}}),foreign,epoch,prep,completion('unfinished',{status:'active'}),unearned];assert.deepEqual(savedPerformanceRecords(rows,{owner:'account:one:1'}),[]);});
test('saved timestamp supplies actual completion day rather than reconciliation day',()=>{const record=savedPerformanceRecords([completion()],{owner:'account:one:1'})[0];assert.equal(record.day,day);});
test('failed storage writes remain retryable without losing durable completions',()=>{const o=context(),write=o.storage.setItem;o.storage.setItem=()=>{throw Error('full');};let result=reconcilePerformanceWorkouts([completion()],o);assert.equal(result.failed.length,1);assert.equal(result.replayed,0);o.storage.setItem=write;result=reconcilePerformanceWorkouts([completion()],o);assert.equal(result.replayed,1);assert.equal(result.progress.totalXp,1);});
test('already credited sessions and mismatched embedded IDs cannot double credit',()=>{const o=context(),row=completion();recordPerformanceSession({...row.progress.performance,day},o);const mismatch=completion('other');mismatch.progress.performance.id='forged';assert.equal(reconcilePerformanceWorkouts([row,mismatch],o).replayed,0);});
test('requested owner is mandatory and account changes cannot retarget repair',()=>{assert.throws(()=>savedPerformanceRecords([completion()]));const o=context(),prior=globalThis.myr5AuthenticatedAccount;try{globalThis.myr5AuthenticatedAccount={user:{id:'different'},dataEpoch:3};assert.equal(reconcilePerformanceWorkouts([completion()],o).replayed,1);}finally{globalThis.myr5AuthenticatedAccount=prior;}});
