import test from 'node:test';
import assert from 'node:assert/strict';
import {createPerformanceAccountSync} from '../performance-account-sync.mjs';
const actor=(id='alice',epoch=1)=>({user:{id},dataEpoch:epoch});
function row(owner='account:alice:1'){const id=crypto.randomUUID();return {id,clientWorkoutId:id,schemaVersion:1,mode:'shallow-squat',goal:8,restSeconds:30,status:'completed',startedAt:1000,completedAt:31000,completion:{value:8,activeSeconds:30,elapsedSeconds:30,earned:true},progress:{performance:{performanceOwner:owner,kind:'reps',difficulty:'easy',value:8,activeSeconds:30,xpBase:9,earned:true}}};}
function storage(){const map=new Map();return {getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)};}
const receipt=(body,headers)=>({workout:{user_id:headers['X-Target-Account'],client_workout_id:body.snapshot.clientWorkoutId,source:'guest_import',competitive_status:'not_eligible'},receipt:{targetAccountId:headers['X-Target-Account'],targetDataEpoch:body.targetDataEpoch,digestVersion:body.digestVersion,fingerprint:body.fingerprint,idempotencyKey:headers['Idempotency-Key']}});
test('only account-started workouts upload automatically and valid receipts are retry-safe',async()=>{const rows=[row(),row('guest:any'),row('account:bob:1'),row('account:alice:0')],original=structuredClone(rows),requests=[],cache=storage();let published=0;const sync=createPerformanceAccountSync({getAccount:()=>actor(),getRows:async()=>rows,storage:cache,api:async(path,method,body,headers)=>{requests.push({path,body,headers});return path.startsWith('/api/account')?actor():receipt(body,headers);},onAccount:()=>published++});assert.equal((await sync.flush()).synced,1);assert.equal((await sync.flush()).synced,0);assert.equal(requests.filter(r=>r.body).length,1);assert.equal(requests[0].body.digestVersion,2);assert.equal(published,1);assert.deepEqual(rows,original);});
test('identity changes during repository read or hashing never post to another account',async()=>{let account=actor(),posts=0;const sync=createPerformanceAccountSync({getAccount:()=>account,getRows:async()=>{account=actor('bob');return [row()];},storage:storage(),api:async()=>posts++});assert.equal((await sync.flush()).aborted,true);assert.equal(posts,0);});
test('late success after logout cannot acknowledge an old account receipt',async()=>{let account=actor(),posts=0;const rows=[row()],cache=storage();const sync=createPerformanceAccountSync({getAccount:()=>account,getRows:async()=>rows,storage:cache,api:async(path,method,body,headers)=>{posts++;account=null;return receipt(body,headers);}});assert.equal((await sync.flush()).aborted,true);account=actor();const retry=createPerformanceAccountSync({getAccount:()=>account,getRows:async()=>rows,storage:cache,api:async(path,method,body,headers)=>path.startsWith('/api/account')?account:(posts++,receipt(body,headers))});assert.equal((await retry.flush()).synced,1);assert.equal(posts,2);});
test('lost responses remain pending and replay the same canonical idempotency key',async()=>{const rows=[row()],keys=[],cache=storage();let lost=true;const sync=createPerformanceAccountSync({getAccount:()=>actor(),getRows:async()=>rows,storage:cache,api:async(path,method,body,headers)=>{if(!body)return actor();keys.push(headers['Idempotency-Key']);if(lost){lost=false;throw Error('Lost response');}return receipt(body,headers);}});assert.equal((await sync.flush()).failed.length,1);assert.equal((await sync.flush()).synced,1);assert.equal(keys[0],keys[1]);});
test('overlapping flushes share a flight and durable newly completed rows are drained',async()=>{const rows=[row()];let release;const gate=new Promise(r=>release=r),calls=0;let posts=0;const sync=createPerformanceAccountSync({getAccount:()=>actor(),getRows:async()=>{await gate;return rows;},storage:storage(),api:async(path,method,body,headers)=>body?(posts++,receipt(body,headers)):actor()});const first=sync.flush(),second=sync.flush();assert.equal(first,second);rows.push(row());release();assert.equal((await first).synced,2);assert.equal(posts,2);});
test('malformed or foreign receipts never cache successful credit',async()=>{const rows=[row()];let posts=0;const sync=createPerformanceAccountSync({getAccount:()=>actor(),getRows:async()=>rows,storage:storage(),api:async(path,method,body,headers)=>{posts++;return {...receipt(body,headers),receipt:{targetAccountId:'bob'}};}});assert.equal((await sync.flush()).failed.length,1);assert.equal((await sync.flush()).failed.length,1);assert.equal(posts,2);});
test('backlogs drain exactly once per record even with missing receipt storage',async()=>{const rows=Array.from({length:125},()=>row());let posts=0;const sync=createPerformanceAccountSync({getAccount:()=>actor(),getRows:async()=>rows,storage:{getItem(){throw Error('denied');},setItem(){throw Error('full');}},maxUploads:120,api:async(path,method,body,headers)=>body?(posts++,receipt(body,headers)):actor()});assert.equal((await sync.flush()).synced,125);assert.equal(posts,125);assert.equal((await sync.flush()).synced,0);assert.equal(posts,125);});
test('failed uploads are tried once per flush, without an infinite failing batch loop',async()=>{const rows=Array.from({length:5},()=>row());let posts=0;const sync=createPerformanceAccountSync({getAccount:()=>actor(),getRows:async()=>rows,storage:null,maxUploads:2,api:async()=>{posts++;throw Error('offline');}});assert.equal((await sync.flush()).failed.length,5);assert.equal(posts,5);});
test('account refresh after accepted import remains retryable without reposting credited data',async()=>{const rows=[row()];let posts=0,gets=0,fail=true,published=0;const sync=createPerformanceAccountSync({getAccount:()=>actor(),getRows:async()=>rows,storage:storage(),api:async(path,method,body,headers)=>{if(body){posts++;return receipt(body,headers);}gets++;if(fail){fail=false;throw Error('offline');}return actor();},onAccount:()=>published++});assert.equal((await sync.flush()).failed.length,1);assert.equal((await sync.flush()).synced,0);assert.equal(posts,1);assert.equal(gets,2);assert.equal(published,1);});
