import test from 'node:test';
import assert from 'node:assert/strict';
import {recordPerformanceSession,recordDailyActivity,readPerformanceProgress,workoutEligibility,performanceOwner,PERFORMANCE_KEY} from '../performance-progress.mjs';
import {matchingCoaches,COACHES} from '../performance-catalog.mjs';
function context(owner='test'){const map=new Map();return {owner,storage:{getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)}};}
const reps=(id,day='2026-10-04')=>({id,mode:'shallow-squat',kind:'reps',difficulty:'easy',value:15,day,xpBase:100});
test('daily XP is retroactive, order independent, and trio bonus is once and not doubled',()=>{
 for(const order of [['workout','meditation','food'],['food','meditation','workout']]){const o=context();for(const kind of order)kind==='workout'?recordPerformanceSession(reps('one'),o):recordDailyActivity(kind,{day:'2026-10-04'},o);assert.equal(readPerformanceProgress(o).totalXp,700);recordDailyActivity('meditation',{day:'2026-10-04'},o);recordPerformanceSession(reps('one'),o);assert.equal(readPerformanceProgress(o).totalXp,700);recordPerformanceSession({...reps('two','2026-10-05'),value:1},o);assert.equal(readPerformanceProgress(o).totalXp,825);}
});
test('saved owner namespace never spills across accounts or deletion epochs',()=>{const o=context();recordPerformanceSession(reps('one'),o);assert.equal(readPerformanceProgress({...o,owner:'second'}).totalXp,0);assert.notEqual(performanceOwner(o.storage,{user:{id:'abc'},dataEpoch:1}),performanceOwner(o.storage,{user:{id:'abc'},dataEpoch:2}));});
test('preparation sets earn nothing and do not enter history',()=>{const o=context();recordPerformanceSession({...reps('prep'),preparation:true},o);assert.equal(readPerformanceProgress(o).totalXp,0);assert.deepEqual(readPerformanceProgress(o).sessions,{});});
test('gold needs actual uninterrupted hold; all owned starter coaches support gold',()=>{const o=context();recordPerformanceSession({id:'hold1',mode:'high-horse',kind:'hold',difficulty:'easy',activeSeconds:600,maxContinuousSeconds:300,value:600,coachId:'myr5',xpBase:10},o);assert.deepEqual(readPerformanceProgress(o).goldenCoaches,[]);recordPerformanceSession({id:'hold2',mode:'high-horse',kind:'hold',difficulty:'easy',activeSeconds:600,maxContinuousSeconds:600,value:600,coachId:'myr5',xpBase:10},o);assert.ok(readPerformanceProgress(o).goldenCoaches.includes('myr5'));assert.ok(matchingCoaches('stances','easy').every(c=>readPerformanceProgress(o).goldenCoaches.includes(c.id)));});
test('performance unlocks coach and weapon while XP alone cannot',()=>{const o=context();recordPerformanceSession({...reps('below'),value:1,xpBase:1000000},o);const state=readPerformanceProgress(o);assert.equal(state.ships.length,0);assert.deepEqual(state.weapons,{});recordPerformanceSession(reps('target'),o);assert.ok(readPerformanceProgress(o).weapons.greatsword>=1);assert.ok(matchingCoaches('legs','easy').every(c=>readPerformanceProgress(o).coaches.includes(c.id)));});
test('recovery shares muscle group across holds/reps but allows both kinds same day',()=>{const o=context();recordPerformanceSession(reps('one','2026-10-02'),o);assert.equal(workoutEligibility('wall-sit',{...o,day:'2026-10-02',kind:'hold'}).allowed,true);assert.equal(workoutEligibility('squat',{...o,day:'2026-10-02',kind:'reps'}).allowed,false);recordPerformanceSession(reps('two','2026-10-03'),o);assert.equal(workoutEligibility('wall-sit',{...o,day:'2026-10-04'}).allowed,false);assert.equal(workoutEligibility('wall-sit',{...o,day:'2026-10-05'}).allowed,true);});
test('catalog approved real coach IDs are unique and golden eligible without invented assets',()=>{assert.equal(COACHES.length,67);assert.equal(new Set(COACHES.map(c=>c.id)).size,67);});
test('cadence unlocks use completed performance, not awarded XP',()=>{const o=context();recordPerformanceSession({id:'short',mode:'jogging',kind:'sprint',difficulty:'easy',rounds:4,value:4,xpBase:10000},o);assert.ok(matchingCoaches('cardio','easy').every(c=>!readPerformanceProgress(o).coaches.includes(c.id)));recordPerformanceSession({id:'five',mode:'jogging',kind:'sprint',difficulty:'easy',rounds:5,value:5,xpBase:1},o);assert.ok(matchingCoaches('cardio','easy').every(c=>readPerformanceProgress(o).coaches.includes(c.id)));});
test('meditation day repetition cannot speed up provisional coach milestones',()=>{const o=context();for(let i=0;i<20;i++)recordDailyActivity('meditation',{day:'2026-10-01'},o);assert.ok(matchingCoaches('meditation','easy').every(c=>!readPerformanceProgress(o).coaches.includes(c.id)));for(const day of ['2026-10-02','2026-10-03'])recordDailyActivity('meditation',{day},o);assert.ok(matchingCoaches('meditation','easy').every(c=>readPerformanceProgress(o).coaches.includes(c.id)));});
test('re-clearing a coach advances one weapon tier and golden hold finishes its block',()=>{const o=context();recordPerformanceSession(reps('one'),o);assert.equal(readPerformanceProgress(o).weapons.greatsword,2);recordPerformanceSession(reps('two'),o);assert.equal(readPerformanceProgress(o).weapons.greatsword,3);recordPerformanceSession({id:'gold',mode:'high-horse',kind:'hold',difficulty:'expert',value:600,activeSeconds:600,maxContinuousSeconds:600,xpBase:1},o);assert.equal(readPerformanceProgress(o).weapons.dagger,20);});
test('malformed persisted ledgers fail closed and derived total ignores stale values',()=>{const o=context(),key=`${PERFORMANCE_KEY}/${o.owner}`;o.storage.setItem(key,JSON.stringify({version:2,sessions:{},days:{}}));assert.doesNotThrow(()=>recordDailyActivity('food',{day:'2026-10-04'},o));recordPerformanceSession(reps('one'),o);const state=JSON.parse(o.storage.getItem(key));state.totalXp=999999;o.storage.setItem(key,JSON.stringify(state));assert.equal(readPerformanceProgress(o).totalXp,100);state.days['2026-10-04'].workoutXp='broken';o.storage.setItem(key,JSON.stringify(state));assert.equal(readPerformanceProgress(o).totalXp,0);});
test('cold imports and denied storage reads stay usable; explicit guest stays guest after account switch',()=>{assert.equal(performanceOwner(null,null),'guest:unavailable');assert.doesNotThrow(()=>readPerformanceProgress({storage:null,account:null}));const bad={getItem(){throw Error('denied');}};assert.equal(readPerformanceProgress({storage:bad,account:null}).totalXp,0);const o=context();const old=globalThis.myr5AuthenticatedAccount;try{globalThis.myr5AuthenticatedAccount={user:{id:'other'}};const options={storage:o.storage,account:null};recordDailyActivity('food',{day:'2026-10-04'},options);assert.equal(readPerformanceProgress(options).days['2026-10-04'].food,true);assert.deepEqual(readPerformanceProgress({storage:o.storage}).days,{});}finally{globalThis.myr5AuthenticatedAccount=old;}});
test('invalid calendar dates and prototype IDs cannot corrupt ledger',()=>{const o=context();assert.throws(()=>recordPerformanceSession({...reps('__proto__')},o));assert.throws(()=>recordDailyActivity('food',{day:'2026-02-31'},o));});
test('controller XP cannot exceed expert repetition or active hold cap',()=>{const o=context();recordPerformanceSession({...reps('huge'),xpBase:1e10},o);assert.ok(readPerformanceProgress(o).totalXp<300);});
test('retrying one completed daily activity after midnight cannot mint another day',()=>{const o=context();recordDailyActivity('meditation',{id:'saved-breathing-id',day:'2026-10-04'},o);recordDailyActivity('meditation',{id:'saved-breathing-id',day:'2026-10-05'},o);assert.equal(readPerformanceProgress(o).days['2026-10-04'].meditation,true);assert.equal(readPerformanceProgress(o).days['2026-10-05'],undefined);});
test('durable coach count preserves original bonus when reward cache is repaired later',()=>{const o=context();recordPerformanceSession(reps('later-coach'),o);const before=readPerformanceProgress(o).totalXp;recordPerformanceSession({...reps('earlier-uncredited','2026-10-03'),earnedCoachCount:0},o);assert.equal(readPerformanceProgress(o).totalXp-before,100);assert.equal(readPerformanceProgress(o).sessions['earlier-uncredited'].day,'2026-10-03');assert.throws(()=>recordPerformanceSession({...reps('invalid-count'),earnedCoachCount:50},o));});
test('mixed hold difficulty milestones credit only their own uninterrupted best',()=>{const o=context();const record={id:'mixed',mode:'high-horse',kind:'hold',difficulty:'expert',value:600,activeSeconds:600,maxContinuousSeconds:595,xpBase:10,earnedCoachCount:0,perDifficultyContinuous:{easy:595,expert:5},coachId:'myr5'};recordPerformanceSession(record,o);const p=readPerformanceProgress(o);assert.equal(p.totalXp,10);assert.ok(matchingCoaches('stances','easy').every(c=>p.coaches.includes(c.id)));assert.ok(matchingCoaches('stances','expert').every(c=>!p.coaches.includes(c.id)));assert.deepEqual(p.goldenCoaches,[]);assert.equal(p.weapons.dagger,2);assert.equal(p.completions['stances/hold/easy'],1);assert.equal(p.completions['stances/hold/expert'],undefined);recordPerformanceSession(record,o);assert.equal(readPerformanceProgress(o).totalXp,10);});
test('one mixed hold can separately achieve multiple difficulties without minting XP twice',()=>{const o=context();recordPerformanceSession({id:'two-holds',mode:'high-horse',kind:'hold',difficulty:'expert',value:900,activeSeconds:900,maxContinuousSeconds:600,xpBase:10,earnedCoachCount:0,perDifficultyContinuous:{easy:600,expert:300},coachId:'myr5'},o);const p=readPerformanceProgress(o);assert.equal(p.totalXp,10);assert.ok(p.goldenCoaches.includes('myr5'));assert.ok(matchingCoaches('stances','expert').every(c=>p.coaches.includes(c.id)&&!p.goldenCoaches.includes(c.id)));assert.equal(p.weapons.dagger,17);assert.throws(()=>recordPerformanceSession({id:'impossible',mode:'high-horse',kind:'hold',value:600,activeSeconds:600,perDifficultyContinuous:{easy:595,expert:600},xpBase:1},o));});
