import test from 'node:test';
import assert from 'node:assert/strict';
import {captureRestBossContext,readRestBossRewards,recordRestBossDefeat,hasRestBossDefeat} from '../rest-boss-rewards.mjs';
import {grantedIds} from '../unlock-ledger.mjs';
import {SetFlow} from '../pod/set-flow.mjs';
import {bossHp,dailyCap,maxKitDamage} from '../combat-config.mjs';
const memory=()=>{const data=new Map();return {getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,String(v))};};
function fixture(){globalThis.localStorage=memory();globalThis.myr5AuthenticatedAccount=null;return captureRestBossContext({day:'2026-10-04'});}
test('first and fifth distinct defeats award one uncommon and legendary; replay cannot grant again',()=>{const c=fixture();for(let i=1;i<=5;i++){const r=recordRestBossDefeat('workout:'+i,c);assert.equal(r.count,i);assert.equal(r.granted.length,i===1||i===5?1:0);}assert.deepEqual(grantedIds('reward-pack',{account:null}).map(x=>x.split(':')[1]),['uncommon','legendary']);assert.equal(recordRestBossDefeat('workout:5',c).recorded,false);assert.equal(readRestBossRewards(c).count,5);});
test('all three preparation/working phases count once, but reopening and next-day replay cannot',()=>{const c=fixture();for(const phase of ['preparation-1','preparation-2','working'])recordRestBossDefeat('workout:one:'+phase,c);assert.equal(readRestBossRewards(c).count,3);const tomorrow={...c,day:'2026-10-05'};assert.equal(recordRestBossDefeat('workout:one:working',tomorrow).count,0);assert(hasRestBossDefeat('workout:one:working',tomorrow));assert.equal(recordRestBossDefeat('workout:two:working',tomorrow).count,1);});
test('captured guest, account and deletion epoch ownership survive later auth changes',()=>{const guest=fixture(),accountA={user:{id:'alpha'},dataEpoch:0};const a=captureRestBossContext({account:accountA,day:guest.day});globalThis.myr5AuthenticatedAccount={user:{id:'beta'},dataEpoch:0};recordRestBossDefeat('guest-fight',guest);recordRestBossDefeat('account-fight',a);assert.equal(readRestBossRewards(guest).count,1);assert.equal(readRestBossRewards(a).count,1);assert.equal(grantedIds('reward-pack',{account:accountA}).length,1);assert.equal(grantedIds('reward-pack',{account:globalThis.myr5AuthenticatedAccount}).length,0);assert.equal(readRestBossRewards(captureRestBossContext({account:{...accountA,dataEpoch:1},day:guest.day})).count,0);});
test('failed reward ledger write repairs without a second defeat',()=>{const c=fixture(),write=localStorage.setItem;let block=true;localStorage.setItem=(k,v)=>{if(k.includes('battle-pass-ledger')&&block)throw Error('quota');write(k,v);};assert.equal(recordRestBossDefeat('repair',c).granted.length,0);block=false;const r=recordRestBossDefeat('repair',c);assert.equal(r.count,1);assert.equal(r.recorded,false);assert.equal(r.granted.length,1);});
test('SetFlow actual health crossing callback includes taps and preparation; defeated encounter stops damage',()=>{const now=Date.now(),f=new SetFlow(null,{now});let kills=0;f.previewRest(now,30);f.beforeRestAttack=()=>{f.restBossId='stable';};f.onRestDamage=()=>{if(f.coachHealth===0)kills++;};f.damage=bossHp(1)-1;const hit=f.tap(now,true);assert(hit.damage>0);assert.equal(kills,1);assert.equal(f.tap(now+300,true),null);assert.equal(kills,1);assert.equal(dailyCap(1),Math.round(5*maxKitDamage(1)));});
import {recordRestBossDefeatExclusive} from '../rest-boss-rewards.mjs';
test('queued cross-tab grant keeps captured owner even when authentication changes before lock runs',async()=>{const c=fixture();let release;const original=Object.getOwnPropertyDescriptor(globalThis,'navigator');Object.defineProperty(globalThis,'navigator',{configurable:true,value:{locks:{request:(key,callback)=>new Promise(resolve=>{release=()=>resolve(callback());})}}});try{const pending=recordRestBossDefeatExclusive('locked',c);globalThis.myr5AuthenticatedAccount={user:{id:'other'}};release();assert.equal((await pending).count,1);assert.equal(grantedIds('reward-pack',{account:null}).length,1);assert.equal(grantedIds('reward-pack',{account:globalThis.myr5AuthenticatedAccount}).length,0);}finally{if(original)Object.defineProperty(globalThis,'navigator',original);else delete globalThis.navigator;}});
test('preparation attack invokes the same boss-defeat hook without completing the workout',()=>{const now=Date.now(),f=new SetFlow(null,{now});f.phase='set';f.workout={stage:'preparation-rest',nextStage:'working'};f.damage=bossHp(1)-1;let kills=0;f.beforeRestAttack=()=>{f.restBossId='workout:preparation-2';};f.onRestDamage=()=>{if(f.coachHealth===0)kills++;};assert(f.preparationTap(now));assert.equal(kills,1);assert.equal(f.phase,'set');assert.equal(f.progress.completedSets,0);});
