import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {Miniflare} from 'miniflare';
import {readFile,readdir} from 'node:fs/promises';
import {prepareWorkoutImport,snapshotFromCompletedWorkout} from '../workout-import-codec.mjs';
import {importWorkout} from '../server/workout-import.mjs';
import {readAccountPerformance,deriveAccountPerformance} from '../server/performance-progress.mjs';
import {warRoomApi} from '../server/war-room.mjs';
import {mergeVerifiedPerformance,recordPerformanceSession,readPerformanceProgress} from '../performance-progress.mjs';
import {holdXp} from '../progression-rules.mjs';
let mf,db;before(async()=>{mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("ok")}}',d1Databases:['DB']});db=await mf.getD1Database('DB');for(const name of(await readdir('drizzle')).filter(n=>n.endsWith('.sql')).sort())await db.batch((await readFile(`drizzle/${name}`,'utf8')).split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean).map(s=>db.prepare(s)));});after(()=>mf?.dispose());
const completedAt=Date.parse('2026-10-04T12:00:00Z');
function snapshot(mode='shallow-squat',performance={}){const kind=mode==='high-horse'?'hold':'reps',active=kind==='hold'?600:30;return {schemaVersion:1,clientWorkoutId:crypto.randomUUID(),mode,goal:kind==='hold'?600:8,restSeconds:30,startedAt:completedAt-active*1000,completedAt,value:kind==='hold'?active:8,activeSeconds:active,elapsedSeconds:active,performance:{version:2,kind,difficulty:'easy',maxContinuousSeconds:kind==='hold'?600:0,perDifficultyContinuous:kind==='hold'?{easy:600}:{},holdBlocks:kind==='hold'?Array.from({length:40},(_,i)=>({difficulty:'easy',activeStart:i*15,continuousStart:i*15})):[],coachId:'myr5',rounds:0,...performance}};}
async function importFor(owner,s){const p=await prepareWorkoutImport(s,{targetAccountId:owner,targetDataEpoch:1});return importWorkout(db,{ownerId:owner,targetAccountId:owner,idempotencyKey:p.idempotencyKey,body:{digestVersion:p.digestVersion,targetDataEpoch:1,snapshot:p.snapshot,fingerprint:p.fingerprint},now:completedAt});}
test('v2 canonical metadata persists, server recomputes XP, and imported history authorizes earned weapons only',async()=>{const s=snapshot();const prepared=await prepareWorkoutImport(s,{targetAccountId:'v2-owner',targetDataEpoch:1});assert.equal(prepared.digestVersion,2);await importFor('v2-owner',s);await importFor('v2-owner',s);const p=await readAccountPerformance(db,'v2-owner');assert.equal(p.totalXp,9);assert.equal(Object.keys(p.sessions).length,1);assert.equal(p.weapons.greatsword,1);assert.equal((await warRoomApi(db,'v2-owner','/api/war-room/loadout','PUT',{revision:0,loadout:{type:'greatsword',tier:1}},completedAt)).state.loadout.tier,1);await assert.rejects(warRoomApi(db,'v2-owner','/api/war-room/loadout','PUT',{revision:1,loadout:{type:'greatsword',tier:20}},completedAt),/workout milestones/);assert.equal((await readAccountPerformance(db,'other-owner')).totalXp,0);});
test('real persisted meditation and food double previous workouts then add one separate 500 bonus',async()=>{await db.prepare('INSERT INTO breathing_sessions(id,user_id,started_at,completed_at) VALUES(?,?,?,?)').bind(crypto.randomUUID(),'v2-owner',completedAt-180000,completedAt).run();await db.prepare('INSERT INTO meals(id,user_id,name,portion,calories,protein,carbs,fat,micros,eaten_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),'v2-owner','Lunch','one',100,10,10,1,'{}','2026-10-04T13:00:00Z',completedAt).run();assert.equal((await readAccountPerformance(db,'v2-owner')).totalXp,518);assert.equal((await readAccountPerformance(db,'v2-owner')).totalXp,518);});
test('hold gold requires reported uninterrupted difficulty evidence, never active seconds alone',async()=>{const s=snapshot('high-horse');await importFor('gold-owner',s);const p=await readAccountPerformance(db,'gold-owner');assert.ok(p.goldenCoaches.includes('myr5'));assert.equal(p.totalXp,holdXp({difficulty:'easy',to:600}));assert.equal(p.weapons.dagger,5);const legacy=deriveAccountPerformance({workouts:[{id:'legacy',mode:'high-horse',source:'server',value:600,active:600,completed_at:completedAt}]});assert.deepEqual(legacy.goldenCoaches,[]);assert.deepEqual(legacy.weapons,{});});
test('codec rejects arbitrary XP, excessive gold evidence and noncontiguous paid blocks',async()=>{await assert.rejects(prepareWorkoutImport({...snapshot(),performance:{...snapshot().performance,xpBase:999999}},{targetAccountId:'bad',targetDataEpoch:1}));const s=snapshot('high-horse');s.performance.perDifficultyContinuous.easy=601;await assert.rejects(prepareWorkoutImport(s,{targetAccountId:'bad',targetDataEpoch:1}));const wrong=snapshot('high-horse');wrong.performance.holdBlocks[1].activeStart=0;await assert.rejects(prepareWorkoutImport(wrong,{targetAccountId:'bad',targetDataEpoch:1}));});
test('projection ignores client XP/coach claims and v2 carries fractional active tracking without changing v1',async()=>{const s=snapshot('high-horse');s.activeSeconds=600.5;s.elapsedSeconds=600.5;s.value=600.5;s.startedAt-=500;s.performance.maxContinuousSeconds=600.5;s.performance.perDifficultyContinuous.easy=600.5;const row={schemaVersion:1,status:'completed',clientWorkoutId:s.clientWorkoutId,mode:s.mode,goal:s.goal,restSeconds:s.restSeconds,startedAt:s.startedAt,completedAt:s.completedAt,completion:{value:s.value,activeSeconds:s.activeSeconds,elapsedSeconds:s.elapsedSeconds},progress:{performance:{...s.performance,xpBase:1e10,earnedCoachCount:49}}};const projected=snapshotFromCompletedWorkout(row);assert.equal(projected.activeSeconds,600.5);assert.equal(projected.performance.xpBase,undefined);assert.equal((await prepareWorkoutImport(projected,{targetAccountId:'fraction',targetDataEpoch:1})).digestVersion,2);});
test('verified sync deduplicates remote IDs, preserves pending locals, and isolates account epochs',async()=>{const remote=await readAccountPerformance(db,'v2-owner'),map=new Map(),storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)},account={user:{id:'v2-owner'},dataEpoch:1,progress:{performance:remote}};recordPerformanceSession({id:'pending',mode:'knee-pushup',kind:'reps',difficulty:'easy',value:1,xpBase:1,day:'2026-10-05'},{storage,account});const once=mergeVerifiedPerformance(account,{storage}),twice=mergeVerifiedPerformance(account,{storage});assert.equal(once.totalXp,519);assert.equal(twice.totalXp,519);assert.equal(Object.keys(twice.sessions).length,2);assert.equal(readPerformanceProgress({storage,account:{user:account.user,dataEpoch:2}}).totalXp,0);assert.throws(()=>mergeVerifiedPerformance({...account,progress:{performance:{version:2}}},{storage}));});
