import test from 'node:test';
import assert from 'node:assert/strict';
import {createUpdateParticipant} from '../update-session.mjs';
import {WorkoutSessionOwner} from '../pod/workout-session-owner.mjs';
function fixture(save=async()=>{},canPrepare=()=>true){const owner=new WorkoutSessionOwner({storage:{getItem:()=>null,setItem(){}}});let frozen=false,reloads=0;const participant=createUpdateParticipant({canPrepare,acquire:()=>{const lease=owner.acquireIdleLease();return lease?()=>owner.releaseIdleLease(lease):null;},save,freeze:()=>{frozen=true;return ()=>{frozen=false;};},reload:()=>reloads++});return{owner,participant,get frozen(){return frozen;},get reloads(){return reloads;}};}
const prepare={type:'UPDATE_SAFETY_CHECK',id:'attempt-1'};
test('update saves before acknowledging and holds the workout lock until reload',async()=>{let finish;const f=fixture(()=>new Promise(r=>finish=r));const result=f.participant.message(prepare);await Promise.resolve();assert.equal(f.owner.start(),false);assert.equal(f.frozen,true);assert.equal((await f.participant.message({type:'UPDATE_CONFIRM',id:prepare.id})).safe,false);finish();assert.equal((await result).safe,true);assert.equal((await f.participant.message({type:'UPDATE_CONFIRM',id:prepare.id})).safe,true);assert.equal(f.participant.activated(),true);assert.equal(f.reloads,1);});
test('active workout and unsaved form decline without changing the session',async()=>{const f=fixture();f.owner.start();assert.equal((await f.participant.message(prepare)).safe,false);assert.equal(f.owner.snapshot().phase,'active');const editing=fixture(async()=>{},()=>false);assert.equal((await editing.participant.message(prepare)).safe,false);assert.equal(editing.frozen,false);});
test('failed saving or explicit abort releases the lock and overlay',async()=>{const failed=fixture(async()=>{throw Error('save failed');});assert.equal((await failed.participant.message(prepare)).safe,false);assert.equal(failed.owner.canStart(),true);assert.equal(failed.frozen,false);const f=fixture();await f.participant.message(prepare);await f.participant.message({type:'UPDATE_ABORT',id:'wrong'});assert.equal(f.owner.canStart(),false);await f.participant.message({type:'UPDATE_ABORT',id:prepare.id});assert.equal(f.owner.canStart(),true);assert.equal(f.frozen,false);assert.equal(f.participant.activated(),false);});
test('an aborted pending save cannot later claim readiness',async()=>{let finish;const f=fixture(()=>new Promise(r=>finish=r));const result=f.participant.message(prepare);await Promise.resolve();await f.participant.message({type:'UPDATE_ABORT',id:prepare.id});finish();assert.equal((await result).safe,false);assert.equal(f.participant.prepared,false);});
