import {TONES,CADENCES,scheduledDay} from '../reminder-settings.mjs';
import {EXERCISES} from '../exercise-library.mjs';
export const MODES={...Object.fromEntries(Object.values(EXERCISES).map(m=>[m.id,m.kind==='hold'||m.kind==='pace'?[15,20,30,45,60]:[5,10,15,20]])),squat:[5,10,15,20],pushup:[5,10,15,20],tree:[15,20,30,45,60],warrior:[15,20,30,45,60],horse:[15,20,30,45,60],boxing:[30,60,90,120,180],jogging:[20,40,60,100],jumping:[5,10,15,20]};
export const KINDS={workout:'Time for your workout. Your coach is ready.',meal:'Pause and log your meal.',water:'Time for a water break.',motivation:'A small step counts. Move at your own pace.'};
export function fail(message,status=400){throw Object.assign(new Error(message),{status});}
export const cleanText=(v,max=160)=>typeof v==='string'&&v.trim().length&&v.trim().length<=max?v.trim():fail('Please check the highlighted information.');
export const uuid=v=>typeof v==='string'&&/^[a-f0-9-]{36}$/.test(v)?v:fail('Invalid record.');
export function nutrition(v,max=20000){if(v==null||v==='')return null;return typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=max?v:fail('Check the nutrition amounts.');}
export function mealInput(v){const eatenAt=cleanText(v.eatenAt,40);if(!/^\d{4}-\d\d-\d\dT/.test(eatenAt)||!Number.isFinite(Date.parse(eatenAt)))fail('Choose a valid meal time.');if(v.micros!=null&&(typeof v.micros!=='object'||Array.isArray(v.micros)))fail('Invalid micronutrients.');const micros=Object.fromEntries(['calcium','iron','magnesium','potassium','sodium','zinc','vitaminA','vitaminC','vitaminD','vitaminE','vitaminB12','folate'].map(k=>[k,nutrition(v.micros?.[k],2000000)]));return {id:uuid(v.id),name:cleanText(v.name),portion:cleanText(v.portion,120),calories:nutrition(v.calories),protein:nutrition(v.protein),carbs:nutrition(v.carbs),fat:nutrition(v.fat),micros,nutritionSource:v.nutritionSource==null?null:cleanText(v.nutritionSource,120),eatenAt:new Date(eatenAt).toISOString()};}
export function reminderInput(v){const tone=v.tone??'direct',daysPerWeek=v.daysPerWeek??7;if(!TONES.includes(tone))fail('Choose gentle, direct or cheeky.');if(!CADENCES.includes(daysPerWeek))fail('Choose 1, 3, 5 or 7 reminder days.');if(!Object.hasOwn(KINDS,v.kind))fail('Choose a reminder type.');for(const k of ['time','quietStart','quietEnd'])if(typeof v[k]!=='string'||!/^([01]\d|2[0-3]):[0-5]\d$/.test(v[k]))fail('Choose a valid reminder time.');try{new Intl.DateTimeFormat('en',{timeZone:v.timezone}).format();}catch{fail('Choose a valid time zone.');}return {id:uuid(v.id),tone,daysPerWeek,kind:v.kind,time:v.time,timezone:v.timezone,enabled:v.enabled===true?1:0,quietStart:v.quietStart,quietEnd:v.quietEnd};}
export function localTime(now,timezone){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(now)).map(x=>[x.type,x.value]));return {day:`${p.year}-${p.month}-${p.day}`,time:`${p.hour}:${p.minute}`};}
const minutes=s=>Number(s.slice(0,2))*60+Number(s.slice(3));
export function isDue(r,now){if(!r.enabled)return false;const l=localTime(now,r.timezone),a=minutes(r.quiet_start),b=minutes(r.quiet_end),t=minutes(l.time);if(!scheduledDay(l.day,r.days_per_week??7))return false;if(a!==b&&(a<b?t>=a&&t<b:t>=a||t<b))return false;const delta=t-minutes(r.time);return delta>=0&&delta<10?l.day:false;}
export function progress(count){return {completedSets:count,xp:count*25,level:1+Math.floor(count/4),unlocks:{shieldBreak:count>=196,ember:count>=4,arc:count>=16,frost:count>=36}};}
export function validateCompletion(w,input,now){const elapsed=(now-w.started_at)/1000,kind=EXERCISES[w.mode]?.kind,min=['hold','pace'].includes(kind)?w.goal:Math.max(2,w.goal*.3);if(elapsed<min||elapsed>7200)fail('This set expired or finished too quickly. Begin a new set.');if(!Number.isFinite(input.value)||input.value<w.goal||input.value>100000)fail('Complete the selected goal first.');if(kind==='pace'&&(!Number.isFinite(input.active)||input.active<w.goal))fail('Hand movement is needed to complete this round.');return true;}
