import {readExerciseRoute,assertRoundAvailable,completeRound,maximumRoundGoal} from './workout-route.mjs';
import {scoreboardApi,exportScoreboard,deleteScoreboard} from './scoreboard.mjs';
import {authConfig,identity,accountOwner,linkLegacy} from './auth.mjs';
import {galaApi} from './gala.mjs';
import {installDraft} from './install-draft.mjs';
import {readOnboarding,saveOnboarding} from './onboarding.mjs';
import {db} from './db.mjs';
import {remoteReminders,reminderService,ensureReminderMigration} from './remote-reminders.mjs';
import {MODES,uuid,cleanText,fail,mealInput,reminderInput,progress,} from './domain.mjs';
import {subscriptionInput,sendPush,runReminders} from './push.mjs';
import {RELEASE} from '../release-info.mjs';
import {trainingFromDaily} from '../weapon-training.mjs';
import {combatProgress,startBreathing,completeBreathing} from './combat.mjs';
import {readCoachPlan,saveCoachPlan,syncTrainingStatus} from './reminder-plan.mjs';
import {emailSubscription,emailLinkAction,emailLinkPage} from './release-email.mjs';
import {readEntitlements,recordCoachArmyCompletion,createCoachArmyBinding,claimCoachArmyBinding} from './entitlements.mjs';
import {startCoachArmyRun,readCoachArmyRun,recordBrowserCoachArmyEvent,recordVerifiedCoachArmyEvent,startDjscratchChallenge,recordDjscratchControl,deliverCoachArmyOutbox} from './coach-army-runs.mjs';
import {warRoomApi} from './war-room.mjs';
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
async function body(request){if(!request.headers.get('content-type')?.startsWith('application/json'))fail('Send JSON.',415);const reader=request.body?.getReader();if(!reader)fail('Empty request.');const chunks=[];let size=0;for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>60000){await reader.cancel();fail('Request too large.',413);}chunks.push(value);}const bytes=new Uint8Array(size);let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.byteLength;}let v;try{v=JSON.parse(new TextDecoder().decode(bytes));}catch{fail('Invalid request.');}if(!v||typeof v!=='object'||Array.isArray(v))fail('Invalid request.');return v;}
async function count(database,user){return Number((await database.prepare('SELECT count(*) AS total FROM workouts WHERE user_id=? AND completed_at IS NOT NULL').bind(user).first()).total);}
async function workoutProgress(database,user,now=Date.now(),includeCombat=true,onboarding=null){const rows=(await database.prepare('SELECT mode,CAST(completed_at/86400000 AS INTEGER) AS day,COUNT(*) AS sets FROM workouts WHERE user_id=? AND completed_at IS NOT NULL GROUP BY mode,day').bind(user).all()).results;return {exerciseRoute:await readExerciseRoute(database,user,onboarding,now),...progress(rows.reduce((sum,row)=>sum+Number(row.sets),0)),activeDays:new Set(rows.map(row=>row.day)).size,trainingVersion:1,training:trainingFromDaily(rows),trainingStatus:{startedDay:rows.length?rows.reduce((value,r)=>Math.min(value,r.day),Infinity):Math.floor(now/86400000),lastCompletedDay:rows.length?rows.reduce((value,r)=>Math.max(value,r.day),-Infinity):null},...(includeCombat?{combat:await combatProgress(database,user,now)}:{})};}
async function api(request,env){const u=new URL(request.url),p=u.pathname,method=request.method,database=db(env);
 if(p.startsWith('/api/gala/'))return galaApi(request,database,body);
 if(p==='/api/integrations/coach-army/completion'&&method==='POST'){
  if(!env.COACH_ARMY_COMPLETION_SECRET||request.headers.get('Authorization')!==`Bearer ${env.COACH_ARMY_COMPLETION_SECRET}`)fail('Unauthorized.',401);
  return json({entitlements:await recordCoachArmyCompletion(database,await body(request))});
 }
 if(p==='/api/integrations/coach-army/binding'&&method==='POST'){
  if(!env.COACH_ARMY_COMPLETION_SECRET||request.headers.get('Authorization')!==`Bearer ${env.COACH_ARMY_COMPLETION_SECRET}`)fail('Unauthorized.',401);
  return json({binding:await createCoachArmyBinding(database,await body(request))});
 }
 if(p==='/api/integrations/coach-army/run-events'&&method==='POST'){
  if(!env.COACH_ARMY_COMPLETION_SECRET||request.headers.get('Authorization')!==`Bearer ${env.COACH_ARMY_COMPLETION_SECRET}`)fail('Unauthorized.',401);
  const result=await recordVerifiedCoachArmyEvent(database,await body(request),Date.now());
  return json({run:result.run,accepted:true,outbox:result.outbox||null});
 }
 if(p==='/api/releases/current'&&method==='GET')return json(RELEASE);
 if(['/api/updates/confirm','/api/updates/unsubscribe'].includes(p)){
  const action=p.split('/').at(-1),token=u.searchParams.get('token');
  if(method==='GET')return emailLinkPage(action,token);
  if(method!=='POST')fail('Method not allowed.',405);
  if(action==='confirm'&&request.headers.get('Origin')!==u.origin)fail('Confirm from the email link page.',403);
  if(!/^[a-f0-9]{64}$/.test(token||''))fail('This email link is invalid.');
  const result=remoteReminders(env)?await reminderService(env,'email-link',`/internal/release-email/${action}`,'POST',{token}):await emailLinkAction(env,action,token);
  return emailLinkPage(action,token,result.message);
 }
 if(p==='/api/cron'&&method==='POST'){if(!env.CRON_SECRET||request.headers.get('Authorization')!==`Bearer ${env.CRON_SECRET}`)fail('Unauthorized.',401);if(remoteReminders(env))fail('The independent reminder service owns scheduling.',409);return json(await runReminders(env));}
 if(!['GET','HEAD'].includes(method)&&request.headers.get('Origin')!==u.origin)fail('Open this action from Coach.',403);
 if(p==='/api/auth/config'&&method==='GET')return json(authConfig(env));
 if(p==='/api/auth/link'&&method==='POST'){const v=await body(request);if(v.confirm!==true)fail('Confirm the account connection.');return json(await linkLegacy(database,await identity(request,env)));}
 if(p==='/api/install-draft')return installDraft(request,database,body);
 const id=await identity(request,env),user=await accountOwner(database,id),now=Date.now(),onboarding=env.REMINDER_INTERNAL===true?null:await readOnboarding(database,user,now);
 if(p==='/api/war-room'&&method==='GET')return json(await warRoomApi(database,user,p,method,null,now));
 if(p==='/api/war-room/loadout'&&method==='PUT')return json(await warRoomApi(database,user,p,method,await body(request),now));
 if(p==='/api/war-room/recipes'&&method==='POST')return json(await warRoomApi(database,user,p,method,await body(request),now));
 if(p==='/api/war-room/import/profile'&&method==='POST')return json(await warRoomApi(database,user,p,method,await body(request),now));
 if(/^\/api\/war-room\/recipes\/[A-Za-z0-9_-]{1,80}$/.test(p)&&method==='DELETE')return json(await warRoomApi(database,user,p,method,await body(request),now));
 if(p==='/api/coach-army/runs'&&method==='POST')return json({run:await startCoachArmyRun(database,user,now)},201);
 const coachArmyRun=p.match(/^\/api\/coach-army\/runs\/([0-9a-f-]{36})(?:\/events)?$/i);
 if(coachArmyRun&&method==='GET'&&!p.endsWith('/events'))return json({run:await readCoachArmyRun(database,coachArmyRun[1],user)});
 if(coachArmyRun&&method==='POST'&&p.endsWith('/events')){const result=await recordBrowserCoachArmyEvent(database,{...(await body(request)),runId:coachArmyRun[1]},user,now);return json({run:result.run,accepted:true,evidence:result.evidence||null,replay:result.replay});}
 const djscratch=p.match(/^\/api\/coach-army\/runs\/([0-9a-f-]{36})\/djscratch(?:\/controls)?$/i);
 if(djscratch&&method==='POST'&&!p.endsWith('/controls'))return json({challenge:await startDjscratchChallenge(database,djscratch[1],user,now)});
 if(djscratch&&method==='POST'&&p.endsWith('/controls'))return json(await recordDjscratchControl(database,{...(await body(request)),runId:djscratch[1]},user,now));
 if(p==='/api/coach-army/claim'&&method==='POST')return json({entitlements:await claimCoachArmyBinding(database,{...(await body(request)),accountId:user},now)});
 if(p==='/api/scoreboard'||p.startsWith('/api/scoreboard/'))return json(await scoreboardApi(database,user,p,method,method==='POST'?await body(request):{},now));
 if(p==='/api/updates/subscription'){const input=method==='POST'?await body(request):{};return json(remoteReminders(env)?await reminderService(env,user,p,method,method==='POST'?input:undefined):await emailSubscription(env,user,method,input,now));}
 if(p==='/api/onboarding'&&method==='PUT')return json(await saveOnboarding(database,user,await body(request),now));
 if(env.REMINDER_INTERNAL!==true&&!onboarding&&method!=='GET'&&(p==='/api/workouts/start'||p.startsWith('/api/breathing/')||p==='/api/meals'||p.startsWith('/api/reminders')||p==='/api/push/subscribe'))fail('Answer the three setup questions to start Coach.',403);
 if(remoteReminders(env)&&(p==='/api/reminders'||p.startsWith('/api/reminders/')||p.startsWith('/api/push/'))){await ensureReminderMigration(env,user);return json(await reminderService(env,user,p,method,['POST','PUT','PATCH'].includes(method)?await body(request):undefined));}
 if(p==='/api/account'&&method==='GET'){const [profile,total,tick,entitlements]=await Promise.all([database.prepare('SELECT * FROM profiles WHERE user_id=?').bind(user).first(),workoutProgress(database,user,now,env.REMINDER_INTERNAL!==true,onboarding),database.prepare("SELECT value FROM system WHERE key='scheduler_tick'").first(),readEntitlements(database,user)]);let push={configured:!!env.VAPID_PUBLIC_KEY,publicKey:env.VAPID_PUBLIC_KEY||null,schedulerActive:!!tick&&now-Number(tick.value)<300000};if(remoteReminders(env)){try{push=await reminderService(env,user,'/internal/status');await reminderService(env,user,'/internal/training-status','POST',total.trainingStatus);}catch{push={configured:false,publicKey:null,schedulerActive:false};}}if(!remoteReminders(env))await syncTrainingStatus(database,user,total.trainingStatus,now);return json({user:{id:user,email:id.email,provider:id.clerk?'clerk':'chatgpt'},profile:profile?JSON.parse(profile.data):{},revision:profile?.revision||0,onboarding,progress:total,entitlements,push:{...push,environment:env.LOCAL_PREVIEW?'preview':'live'},syncedAt:now});}
 if(p==='/api/goals'&&method==='GET')return json({items:(await database.prepare('SELECT id,title,note,status,created_at,updated_at FROM goals WHERE user_id=? ORDER BY updated_at DESC').bind(user).all()).results});
 if(p==='/api/goals'&&method==='POST'){const v=await body(request),title=cleanText(v.title,160),note=v.note==null||v.note===''?'':cleanText(v.note,1000);if(!title)fail('Add a title for this goal.');const id=uuid(v.id||crypto.randomUUID());await database.prepare('INSERT INTO goals(id,user_id,title,note,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').bind(id,user,title,note,'active',now,now).run();return json({saved:true,id});}
 if(p.startsWith('/api/goals/')&&method==='PATCH'){const id=uuid(p.split('/').at(-1)),v=await body(request),changes=[];if(v.title!==undefined){const title=cleanText(v.title,160);if(!title)fail('Add a title for this goal.');changes.push(['title',title]);}if(v.note!==undefined)changes.push(['note',v.note===''?'':cleanText(v.note,1000)]);if(v.status!==undefined){if(!['active','completed','archived'].includes(v.status))fail('Choose active, completed, or archived.');changes.push(['status',v.status]);}if(!changes.length)fail('Nothing to save.');const sets=changes.map(([key])=>`${key}=?`).join(','),saved=await database.prepare(`UPDATE goals SET ${sets},updated_at=? WHERE id=? AND user_id=? RETURNING id`).bind(...changes.map(([,value])=>value),now,id,user).first();if(!saved)fail('Goal not found.',404);return json({saved:true});}
 if(p==='/api/reminders/plan'&&method==='GET')return json(await readCoachPlan(database,user));
 if(p==='/api/reminders/plan'&&method==='PUT')return json(await saveCoachPlan(database,user,await body(request)));
 if(p==='/api/profile'&&method==='PUT'){const v=await body(request);if(!Number.isSafeInteger(v.revision)||!v.data||typeof v.data!=='object'||Array.isArray(v.data))fail('Invalid profile.');const allowed=['myr5-recipe-v1','myr5-motion-v1','mominc-avatar-v1','myr5-pod-power-v1','handborne-recipe-v4','mbs-dj-identity-v1'];const safe={};for(const k of allowed){if(v.data[k]!=null){if(typeof v.data[k]!=='string'||v.data[k].length>30000)fail('Appearance is too large.');safe[k]=v.data[k];}}const result=await database.prepare('INSERT INTO profiles(user_id,data,revision,updated_at) VALUES(?,?,1,?) ON CONFLICT(user_id) DO UPDATE SET data=excluded.data,revision=profiles.revision+1,updated_at=excluded.updated_at WHERE profiles.revision=? RETURNING revision').bind(user,JSON.stringify(safe),now,v.revision).first();if(!result)fail('Appearance changed on another device. Restore it before saving again.',409);return json(result);}
 if(env.REMINDER_INTERNAL!==true&&p==='/api/breathing/start'&&method==='POST')return json(await startBreathing(database,user,now));
 if(env.REMINDER_INTERNAL!==true&&p==='/api/breathing/complete'&&method==='POST')return json({combat:await completeBreathing(database,user,await body(request),now)});
 if(p==='/api/workouts/start'&&method==='POST'){const v=await body(request);if(!Object.hasOwn(MODES,v.mode)||(!Number.isSafeInteger(v.goal)||v.goal<1||v.goal>await maximumRoundGoal(database,user,v.mode,onboarding.targets.goals[v.mode]??0)))fail('Choose a valid exercise and goal.');await assertRoundAvailable(database,user,v.mode,onboarding?.data?.profile?.timezone||'UTC',now);const recent=await database.prepare('SELECT count(*) AS n FROM workouts WHERE user_id=? AND started_at>?').bind(user,now-60000).first();if(recent.n>=12)fail('Please wait a moment before starting again.',429);const id=crypto.randomUUID();await database.prepare('INSERT INTO workouts(id,user_id,mode,goal,started_at) VALUES(?,?,?,?,?)').bind(id,user,v.mode,v.goal,now).run();return json({id,startedAt:now});}
 if(p==='/api/workouts/complete'&&method==='POST'){const v=await body(request),id=uuid(v.id),w=await database.prepare('SELECT * FROM workouts WHERE id=? AND user_id=?').bind(id,user).first();if(!w)fail('Workout not found.',404);await completeRound(database,user,w,v,onboarding?.data?.profile?.timezone||'UTC',now);const progress=await workoutProgress(database,user,now,env.REMINDER_INTERNAL!==true,onboarding);if(remoteReminders(env))try{await reminderService(env,user,'/internal/training-status','POST',progress.trainingStatus);}catch{console.warn('Reminder training sync will retry on account refresh.');}else await syncTrainingStatus(database,user,progress.trainingStatus,now);return json({progress});}
 if(p==='/api/workouts'&&method==='GET')return json({items:(await database.prepare('SELECT id,mode,goal,value,completed_at FROM workouts WHERE user_id=? AND completed_at IS NOT NULL ORDER BY completed_at DESC LIMIT 100').bind(user).all()).results});
 if(p==='/api/achievements'&&method==='GET')return json({items:(await database.prepare('SELECT mode,COUNT(*) AS sets,MAX(value) AS best,SUM(value) AS total FROM workouts WHERE user_id=? AND completed_at IS NOT NULL GROUP BY mode').bind(user).all()).results});
 if(p==='/api/meals'&&method==='GET')return json({items:(await database.prepare('SELECT * FROM meals WHERE user_id=? ORDER BY eaten_at DESC LIMIT 100').bind(user).all()).results});
 if(p==='/api/meals'&&method==='POST'){const v=mealInput(await body(request));await database.prepare('INSERT INTO meals(id,user_id,name,portion,calories,protein,carbs,fat,micros,nutrition_source,eaten_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(v.id,user,v.name,v.portion,v.calories,v.protein,v.carbs,v.fat,JSON.stringify(v.micros),v.nutritionSource,v.eatenAt,now).run();return json({saved:true});}
 if(p.startsWith('/api/meals/')&&method==='DELETE'){await database.prepare('DELETE FROM meals WHERE id=? AND user_id=?').bind(uuid(p.split('/').at(-1)),user).run();return json({deleted:true});}
 if(p==='/api/reminders'&&method==='GET')return json({items:(await database.prepare('SELECT * FROM reminders WHERE user_id=? ORDER BY time').bind(user).all()).results});
 if(p==='/api/reminders'&&method==='POST'){const v=reminderInput(await body(request));const n=await database.prepare('SELECT count(*) AS n FROM reminders WHERE user_id=?').bind(user).first();if(n.n>=16)fail('Keep up to 16 reminders. Remove one before adding another.');await database.prepare('INSERT INTO reminders(id,user_id,kind,time,timezone,enabled,quiet_start,quiet_end,tone,days_per_week) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(v.id,user,v.kind,v.time,v.timezone,v.enabled,v.quietStart,v.quietEnd,v.tone,v.daysPerWeek).run();return json({saved:true});}
 if(p.startsWith('/api/reminders/')&&method==='DELETE'){const id=uuid(p.split('/').at(-1));await database.prepare('DELETE FROM reminders WHERE id=? AND user_id=?').bind(id,user).run();return json({deleted:true});}
 if(p.startsWith('/api/reminders/')&&method==='PUT'){const id=uuid(p.split('/').at(-1)),v=reminderInput({...await body(request),id});const saved=await database.prepare('UPDATE reminders SET kind=?,time=?,timezone=?,enabled=?,quiet_start=?,quiet_end=?,tone=?,days_per_week=? WHERE id=? AND user_id=? RETURNING id').bind(v.kind,v.time,v.timezone,v.enabled,v.quietStart,v.quietEnd,v.tone,v.daysPerWeek,id,user).first();if(!saved)fail('Reminder not found.',404);return json({saved:true});}
 if(p.startsWith('/api/reminders/')&&method==='PATCH'){const id=uuid(p.split('/').at(-1)),v=await body(request);if(typeof v.enabled!=='boolean')fail('Choose on or off.');const saved=await database.prepare('UPDATE reminders SET enabled=? WHERE id=? AND user_id=? RETURNING id').bind(v.enabled?1:0,id,user).first();if(!saved)fail('Reminder not found.',404);return json({enabled:v.enabled});}
 if(p==='/api/push/subscribe'&&method==='POST'){if(!env.VAPID_PRIVATE_KEY)fail('Notification sending is not connected yet.',503);const s=subscriptionInput(await body(request));const existing=await database.prepare('SELECT user_id FROM subscriptions WHERE endpoint=?').bind(s.endpoint).first();if(existing&&existing.user_id!==user)await database.prepare('DELETE FROM subscriptions WHERE endpoint=?').bind(s.endpoint).run();await database.prepare('INSERT INTO subscriptions(endpoint,user_id,data,created_at) VALUES(?,?,?,?) ON CONFLICT(endpoint) DO UPDATE SET data=excluded.data').bind(s.endpoint,user,JSON.stringify(s),now).run();return json({subscribed:true});}
 if(p==='/api/push/unsubscribe'&&method==='POST'){const v=await body(request);await database.prepare('DELETE FROM subscriptions WHERE endpoint=? AND user_id=?').bind(cleanText(v.endpoint,2048),user).run();return json({unsubscribed:true});}
 if(p==='/api/push/test'&&method==='POST'){const v=await body(request);const s=await database.prepare('SELECT data,created_at FROM subscriptions WHERE endpoint=? AND user_id=?').bind(cleanText(v.endpoint,2048),user).first();if(!s)fail('Enable notifications on this device first.');const key=`test:${user}`;const recent=await database.prepare('SELECT value FROM system WHERE key=?').bind(key).first();if(recent&&now-Number(recent.value)<30000)fail('Wait 30 seconds between test reminders.',429);await database.prepare('INSERT INTO system(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(key,String(now)).run();await sendPush(env,JSON.parse(s.data),{title:'MYR5 Coach',body:'Your phone is connected to Coach reminders.',url:'/pose.html?panel=reminders',tag:'myr5-test'});return json({accepted:true});}
  if(p==='/api/export'&&method==='GET'){const tables=['profiles','onboarding','workouts','meals','reminders','goals','war_room_arsenals'].filter(t=>t!=='onboarding'||env.REMINDER_INTERNAL!==true);const data={};for(const table of tables)data[table]=(await database.prepare(`SELECT * FROM ${table} WHERE user_id=?`).bind(user).all()).results;if(remoteReminders(env)){await ensureReminderMigration(env,user);data.reminders=(await reminderService(env,user,'/api/reminders')).items;data.releaseEmails=await reminderService(env,user,'/api/updates/subscription');}if(env.REMINDER_INTERNAL!==true){data.scoreboard=await exportScoreboard(database,user);data.combat=await combatProgress(database,user,now);for(const table of ['login_days','breathing_sessions'])data[table]=(await database.prepare(`SELECT * FROM ${table} WHERE user_id=?`).bind(user).all()).results;}if(!remoteReminders(env))data.releaseEmails=await emailSubscription(env,user,'GET');return json(data);}
  if(p==='/api/account'&&method==='DELETE'){const v=await body(request);if(v.confirm!=='DELETE')fail('Type DELETE to clear your Coach data.');if(remoteReminders(env)){await ensureReminderMigration(env,user);await reminderService(env,user,'/api/account','DELETE',{confirm:'DELETE'});}await database.batch([...(env.REMINDER_INTERNAL===true?[]:deleteScoreboard(database,user)),database.prepare('DELETE FROM deliveries WHERE endpoint IN (SELECT endpoint FROM subscriptions WHERE user_id=?) OR reminder_id IN (SELECT id FROM reminders WHERE user_id=?)').bind(user,user),database.prepare('DELETE FROM coach_army_bindings WHERE account_id=?').bind(user),database.prepare('DELETE FROM coach_army_completion_outbox WHERE account_id=?').bind(user),database.prepare('DELETE FROM coach_army_run_events WHERE account_id=?').bind(user),database.prepare('DELETE FROM coach_army_runs WHERE account_id=?').bind(user),...['test:','training:','coach-plan:'].map(prefix=>database.prepare('DELETE FROM system WHERE key=?').bind(prefix+user)),database.prepare('DELETE FROM system WHERE substr(key,1,?)=?').bind(('notify-budget:'+user+':').length,'notify-budget:'+user+':'),...['profiles','onboarding','workouts','meals','reminders','goals','war_room_arsenals','subscriptions','release_subscribers','release_deliveries','login_days','breathing_sessions','account_entitlements','coach_army_completions'].filter(t=>!['onboarding','login_days','breathing_sessions'].includes(t)||env.REMINDER_INTERNAL!==true).map(t=>database.prepare(`DELETE FROM ${t} WHERE user_id=?`).bind(user))]);return json({deleted:true});}
 return json({error:'Not found.'},404);
}
export default {
 async fetch(request,env){try{const url=new URL(request.url);if(url.pathname.startsWith('/api/'))return await api(request,env);if(url.pathname==='/health'){let reminders=null;if(remoteReminders(env)){try{const status=await reminderService(env,'health','/internal/status');reminders={available:true,configured:status.configured,schedulerActive:status.schedulerActive};}catch{reminders={available:false,configured:false,schedulerActive:false};}}return json({ok:true,app:'MYR5 Coach',reminders});}if(url.pathname==='/')return Response.redirect(new URL('/pose.html',url),302);if(env.ASSETS)return env.ASSETS.fetch(request);return new Response('Not found',{status:404});}catch(e){if(!e.status)console.error('Coach request failed',e.message);return json({error:e.status?e.message:'Could not complete this request. Please try again.',...(e.status&&e.code?{code:e.code}:{})},e.status||500);}},
 async scheduled(event,env,ctx){if(!remoteReminders(env))ctx.waitUntil(runReminders(env));ctx.waitUntil(deliverCoachArmyOutbox(db(env),env));}
};
