import {sqliteTable,text,integer,real,index,uniqueIndex,primaryKey} from 'drizzle-orm/sqlite-core';
export const profiles=sqliteTable('profiles',{userId:text('user_id').primaryKey(),data:text('data').notNull().default('{}'),revision:integer('revision').notNull().default(0),updatedAt:integer('updated_at').notNull()});
export const workouts=sqliteTable('workouts',{id:text('id').primaryKey(),userId:text('user_id').notNull(),mode:text('mode').notNull(),goal:real('goal').notNull(),startedAt:integer('started_at').notNull(),completedAt:integer('completed_at'),value:real('value'),active:real('active')},t=>[index('workouts_user_completed').on(t.userId,t.completedAt)]);
export const meals=sqliteTable('meals',{id:text('id').primaryKey(),userId:text('user_id').notNull(),name:text('name').notNull(),portion:text('portion').notNull(),calories:real('calories'),protein:real('protein'),carbs:real('carbs'),fat:real('fat'),micros:text('micros').notNull().default('{}'),nutritionSource:text('nutrition_source'),eatenAt:text('eaten_at').notNull(),createdAt:integer('created_at').notNull()},t=>[index('meals_user_date').on(t.userId,t.eatenAt)]);
export const reminders=sqliteTable('reminders',{id:text('id').primaryKey(),userId:text('user_id').notNull(),kind:text('kind').notNull(),time:text('time').notNull(),timezone:text('timezone').notNull(),enabled:integer('enabled').notNull().default(1),quietStart:text('quiet_start').notNull().default('22:00'),quietEnd:text('quiet_end').notNull().default('07:00'),tone:text('tone').notNull().default('direct'),daysPerWeek:integer('days_per_week').notNull().default(7)},t=>[index('reminders_user').on(t.userId)]);
export const subscriptions=sqliteTable('subscriptions',{endpoint:text('endpoint').primaryKey(),userId:text('user_id').notNull(),data:text('data').notNull(),createdAt:integer('created_at').notNull()},t=>[index('subscriptions_user').on(t.userId)]);
export const deliveries=sqliteTable('deliveries',{reminderId:text('reminder_id').notNull(),day:text('day').notNull(),endpoint:text('endpoint').notNull(),status:text('status').notNull(),updatedAt:integer('updated_at').notNull()},t=>[primaryKey({columns:[t.reminderId,t.day,t.endpoint]})]);
export const system=sqliteTable('system',{key:text('key').primaryKey(),value:text('value').notNull()});
export const scoreboardInvites=sqliteTable('scoreboard_invites',{ownerId:text('owner_id').primaryKey(),tokenHash:text('token_hash').notNull().unique(),createdAt:integer('created_at').notNull(),expiresAt:integer('expires_at').notNull()});
export const scoreboardLinks=sqliteTable('scoreboard_links',{id:text('id').primaryKey(),userA:text('user_a').notNull(),userB:text('user_b').notNull(),createdAt:integer('created_at').notNull()},t=>[index('scoreboard_links_a').on(t.userA),index('scoreboard_links_b').on(t.userB),uniqueIndex('scoreboard_links_pair').on(t.userA,t.userB)]);
export const onboarding=sqliteTable('onboarding',{userId:text('user_id').primaryKey(),data:text('data').notNull(),startDay:text('start_day').notNull(),completedAt:integer('completed_at').notNull(),updatedAt:integer('updated_at').notNull(),revision:integer('revision').notNull().default(1),writeToken:text('write_token').notNull()});

export const installDrafts=sqliteTable('install_drafts',{tokenHash:text('token_hash').primaryKey(),data:text('data').notNull(),creator:text('creator').notNull(),expiresAt:integer('expires_at').notNull()},t=>[index('install_drafts_expiry').on(t.expiresAt),index('install_drafts_creator').on(t.creator)]);

export const accountIdentities=sqliteTable('account_identities',{clerkId:text('clerk_id').primaryKey(),ownerId:text('owner_id').notNull().unique(),createdAt:integer('created_at').notNull()});

export const releaseSubscribers=sqliteTable('release_subscribers',{userId:text('user_id').primaryKey(),email:text('email').notNull(),enabled:integer('enabled').notNull().default(0),confirmHash:text('confirm_hash'),expiresAt:integer('expires_at'),unsubscribeToken:text('unsubscribe_token').notNull().unique(),updatedAt:integer('updated_at').notNull(),confirmedAt:integer('confirmed_at'),lastRelease:text('last_release')},t=>[index('release_subscribers_confirmation').on(t.confirmHash)]);
export const releaseDeliveries=sqliteTable('release_deliveries',{userId:text('user_id').notNull(),releaseId:text('release_id').notNull(),status:text('status').notNull(),updatedAt:integer('updated_at').notNull()},t=>[primaryKey({columns:[t.userId,t.releaseId]})]);
export const galaRuns=sqliteTable('gala_runs',{id:text('id').primaryKey(),tokenHash:text('token_hash').notNull(),creator:text('creator').notNull(),startedAt:integer('started_at').notNull(),djName:text('dj_name'),moniker:text('moniker'),djAt:integer('dj_at'),galaAt:integer('gala_at'),lilAt:integer('lil_at'),corgiAt:integer('corgi_at'),handAt:integer('hand_at'),armieAt:integer('armie_at'),completedAt:integer('completed_at'),durationMs:integer('duration_ms'),installedAt:integer('installed_at'),joinedAt:integer('joined_at'),publicName:text('public_name').unique()},t=>[index('gala_runs_creator_started').on(t.creator,t.startedAt),index('gala_runs_leaderboard').on(t.joinedAt,t.durationMs)]);
