import {sqliteTable,text,integer,real,index,primaryKey} from 'drizzle-orm/sqlite-core';
export const profiles=sqliteTable('profiles',{userId:text('user_id').primaryKey(),data:text('data').notNull().default('{}'),revision:integer('revision').notNull().default(0),updatedAt:integer('updated_at').notNull()});
export const workouts=sqliteTable('workouts',{id:text('id').primaryKey(),userId:text('user_id').notNull(),mode:text('mode').notNull(),goal:real('goal').notNull(),startedAt:integer('started_at').notNull(),completedAt:integer('completed_at'),value:real('value'),active:real('active')},t=>[index('workouts_user_completed').on(t.userId,t.completedAt)]);
export const meals=sqliteTable('meals',{id:text('id').primaryKey(),userId:text('user_id').notNull(),name:text('name').notNull(),portion:text('portion').notNull(),calories:real('calories'),protein:real('protein'),carbs:real('carbs'),fat:real('fat'),micros:text('micros').notNull().default('{}'),nutritionSource:text('nutrition_source'),eatenAt:text('eaten_at').notNull(),createdAt:integer('created_at').notNull()},t=>[index('meals_user_date').on(t.userId,t.eatenAt)]);
export const reminders=sqliteTable('reminders',{id:text('id').primaryKey(),userId:text('user_id').notNull(),kind:text('kind').notNull(),time:text('time').notNull(),timezone:text('timezone').notNull(),enabled:integer('enabled').notNull().default(1),quietStart:text('quiet_start').notNull().default('22:00'),quietEnd:text('quiet_end').notNull().default('07:00'),tone:text('tone').notNull().default('direct'),daysPerWeek:integer('days_per_week').notNull().default(7)},t=>[index('reminders_user').on(t.userId)]);
export const subscriptions=sqliteTable('subscriptions',{endpoint:text('endpoint').primaryKey(),userId:text('user_id').notNull(),data:text('data').notNull(),createdAt:integer('created_at').notNull()},t=>[index('subscriptions_user').on(t.userId)]);
export const deliveries=sqliteTable('deliveries',{reminderId:text('reminder_id').notNull(),day:text('day').notNull(),endpoint:text('endpoint').notNull(),status:text('status').notNull(),updatedAt:integer('updated_at').notNull()},t=>[primaryKey({columns:[t.reminderId,t.day,t.endpoint]})]);
export const system=sqliteTable('system',{key:text('key').primaryKey(),value:text('value').notNull()});
export const onboarding=sqliteTable('onboarding',{userId:text('user_id').primaryKey(),data:text('data').notNull(),startDay:text('start_day').notNull(),completedAt:integer('completed_at').notNull(),updatedAt:integer('updated_at').notNull(),revision:integer('revision').notNull().default(1),writeToken:text('write_token').notNull()});

export const installDrafts=sqliteTable('install_drafts',{tokenHash:text('token_hash').primaryKey(),data:text('data').notNull(),creator:text('creator').notNull(),expiresAt:integer('expires_at').notNull()},t=>[index('install_drafts_expiry').on(t.expiresAt),index('install_drafts_creator').on(t.creator)]);

export const accountIdentities=sqliteTable('account_identities',{clerkId:text('clerk_id').primaryKey(),ownerId:text('owner_id').notNull().unique(),createdAt:integer('created_at').notNull()});
