// Turns a ?recordPose=1 recording into a k-NN samples file and a replay fixture.
//   node scripts/pose-samples.mjs <recording.json> [--reps N] [--use]
//     Writes tests/fixtures/pose-replay/<name>.replay.json (+ <name>.samples.json beside it) and prints how the
//     rules and the k-NN counted. --use moves the samples to pose-samples/<exercise>.samples.json and registers
//     them in pose-samples.mjs, so the app counts that exercise with the k-NN.
//   node scripts/pose-samples.mjs --example
//     Rebuilds the synthetic squat example (tests/pose-fixtures.mjs) in tests/fixtures/pose-replay.
import {readFile,writeFile,readdir,mkdir,rm} from 'node:fs/promises';
import {basename} from 'node:path';
import {fileURLToPath} from 'node:url';
import {MovementSession,MOVEMENTS,features} from '../movement-engine.mjs';
import {embed,EMBED_LANDMARKS} from '../pose-classifier.mjs';
const root=new URL('../',import.meta.url),fixtures=new URL('tests/fixtures/pose-replay/',root),registry=new URL('pose-samples/',root);
const MAX_BYTES=50*1024,PER_CLASS=100;
const round=(v,d=3)=>Math.round(v*10**d)/10**d;
const evenly=(list,n)=>list.length<=n?list:Array.from({length:n},(_,i)=>list[Math.floor(i*list.length/n)]);
// Replay frames keep only the landmarks counting uses; the rest come back invisible.
const points=frame=>{const p=Array.from({length:27},()=>({x:0,y:0,visibility:0}));frame.forEach(([x,y,visibility],i)=>{p[EMBED_LANDMARKS[i]]={x,y,visibility};});return p;};
export function replay(fixture,options={}){
 const session=new MovementSession(fixture.exercise,options);
 for(const [t,frame] of fixture.frames)session.update(points(frame),t,fixture.aspect);
 return session.count;
}
export function convert(recording,{reps=null}={}){
 const {exercise,aspect=1,frames,labels=[]}=recording;
 if(MOVEMENTS[exercise]?.kind!=='reps')throw new Error(`${exercise} is not a rep exercise; the k-NN only counts reps.`);
 const t0=frames[0][0],compact=frames.map(([t,p])=>[Math.round(t-t0),EMBED_LANDMARKS.map(i=>[round(p[i][0]),round(p[i][1]),round(p[i][2],2)])]);
 const labelled=compact.flatMap(([t,frame])=>{const label=labels.find(l=>t+t0>=l.from&&t+t0<=l.to)?.label;return label?[{label,f:features(points(frame),aspect)}]:[];});
 // Landmarks clear in 90% of the labelled frames are required; a side view only needs its near side.
 const need=EMBED_LANDMARKS.filter(i=>labelled.filter(({f})=>f.visible([i])&&f.p[i].visibility>=.6).length>=.9*labelled.length);
 if(![11,23].every(i=>need.includes(i))&&![12,24].every(i=>need.includes(i)))throw new Error('No clear shoulder and hip in the labelled frames. Record again with the body in view.');
 const byLabel={};for(const {label,f} of labelled)if(f.visible(need))(byLabel[label]??=[]).push(embed(f.p).map(v=>round(v)));
 if(!byLabel.up?.length||!byLabel.down?.length)throw new Error('The recording needs both "up" and "down" labels.');
 const samples={exercise,need,samples:Object.entries(byLabel).flatMap(([label,list])=>evenly(list,PER_CLASS).map(e=>[label,e]))};
 if(JSON.stringify(samples).length>MAX_BYTES)throw new Error('Samples file over 50 KB.');
 const fixture={exercise,aspect,reps,rules:0,knn:0,frames:compact};
 fixture.rules=replay(fixture,{samples:null});fixture.knn=replay(fixture,{samples});
 return {samples,fixture};
}
async function register(){
 const files=(await readdir(registry).catch(()=>[])).filter(n=>n.endsWith('.samples.json')).sort();
 await writeFile(new URL('pose-samples.mjs',root),['// Generated by scripts/pose-samples.mjs from pose-samples/*.samples.json. Do not edit by hand.','// Exercises listed here count reps with the k-NN pose classifier; every other exercise uses the rules.',
  ...files.map((n,i)=>`import s${i} from './pose-samples/${n}' with {type:'json'};`),`export default {${files.map((n,i)=>`${JSON.stringify(n.replace('.samples.json',''))}:s${i}`).join(',')}};`,''].join('\n'));
}
async function main(args){
 const example=args.includes('--example'),use=args.includes('--use'),reps=args.includes('--reps')?Number(args[args.indexOf('--reps')+1]):null;
 const file=args.find(a=>!a.startsWith('--')&&a!==String(reps));
 const recording=example?(await import('../tests/pose-fixtures.mjs')).syntheticRecording():JSON.parse(await readFile(file,'utf8'));
 const {samples,fixture}=convert(recording,{reps:example?6:reps});
 const name=example?'squat-synthetic':basename(file,'.json').replace(/^recordPose-/,'');
 await mkdir(fixtures,{recursive:true});
 await writeFile(new URL(name+'.replay.json',fixtures),JSON.stringify(fixture)+'\n');
 if(use){
  await mkdir(registry,{recursive:true});await writeFile(new URL(samples.exercise+'.samples.json',registry),JSON.stringify(samples)+'\n');
  await rm(new URL(name+'.samples.json',fixtures),{force:true});await register();
  // Other replays of this exercise count with the registered samples: re-lock their k-NN counts.
  for(const other of (await readdir(fixtures)).filter(n=>n.endsWith('.replay.json')&&n!==name+'.replay.json')){
   const url=new URL(other,fixtures),old=JSON.parse(await readFile(url,'utf8'));
   if(old.exercise!==samples.exercise||(await readdir(fixtures)).includes(other.replace('.replay.json','.samples.json')))continue;
   old.knn=replay(old,{samples});await writeFile(url,JSON.stringify(old)+'\n');
  }
 }else await writeFile(new URL(name+'.samples.json',fixtures),JSON.stringify(samples)+'\n');
 console.log(`${samples.exercise}: ${samples.samples.length} samples, needs landmarks ${samples.need.join(' ')}. Rules counted ${fixture.rules}, k-NN counted ${fixture.knn}${reps===null&&!example?'':`, you did ${fixture.reps}`}.`);
 console.log(use?`k-NN now counts ${samples.exercise} in the app. Run npm test, then commit pose-samples/ and the replay.`:`Replay saved as tests/fixtures/pose-replay/${name}.replay.json. Add --use to count ${samples.exercise} with the k-NN in the app.`);
}
if(process.argv[1]===fileURLToPath(import.meta.url))main(process.argv.slice(2)).catch(error=>{console.error(error.message);process.exit(1);});
