const css=document.createElement('link');css.rel='stylesheet';css.href='/war-room/war-room.css';document.head.append(css);
const $=id=>document.getElementById(id);
const CHECKS=[['djscratch','DJ Scratch'],['gala','Gala'],['lilboyfriend','Lil Boyfriend'],['corgi','Corgi'],['hand','Helping Hand'],['armie','Coach Armie']];
const api=async(path,options)=>{const r=await fetch(path,{credentials:'same-origin',cache:'no-store',...options});const value=await r.json();if(!r.ok)throw Error(value.error||'The War Room service is unavailable.');return value;};
const time=ms=>{if(!Number.isFinite(Number(ms)))return '—';const s=Math.max(0,Math.round(Number(ms)/1000));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;};
let arsenal=null;
function renderArsenal(state){arsenal=state;$('weaponType').value=state.loadout.type;$('weaponTier').value=String(state.loadout.tier);$('arsenalStatus').textContent=state.updatedAt?'Saved to this account.':'No saved loadout yet.';}
function renderRun(run){$('runStatus').textContent=run?'Run '+(run.completedAt?'complete':'in progress')+'.':'No saved Gala run found.';$('identity').textContent=run?.djName||'No DJ identity attached.';$('checks').replaceChildren(...CHECKS.map(([key,label])=>{const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=run?.completed?.includes(key)?'✓ complete':'— pending';row.append(dt,dd);return row;}));}
async function load(){ $('refresh').disabled=true;$('access').textContent='Verified Coach Army access';try{const [runReply,board,room]=await Promise.all([api('/api/gala/install-draft'),api('/api/gala/leaderboard'),api('/api/war-room')]);renderRun(runReply.data);renderArsenal(room.state);const rows=board.items||[];$('leaderRows').replaceChildren(...rows.map(item=>{const tr=document.createElement('tr');for(const value of [String(item.rank).padStart(2,'0'),item.djName||'Unnamed DJ',time(item.durationMs)]){const td=document.createElement('td');td.textContent=value;tr.append(td);}return tr;}));$('boardStatus').textContent=rows.length?'Live escapee records.':'No ranked runs yet.';}catch(error){$('runStatus').textContent=error.message;$('boardStatus').textContent='Leaderboard unavailable: '+error.message;$('arsenalStatus').textContent='Arsenal unavailable: '+error.message;$('access').textContent='Verified access · service unavailable';}finally{$('refresh').disabled=false;}}
$('refresh').addEventListener('click',load);load();
$('saveLoadout').addEventListener('click',async()=>{if(!arsenal)return;const button=$('saveLoadout');button.disabled=true;try{const reply=await api('/api/war-room/loadout',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:arsenal.revision,loadout:{type:$('weaponType').value,tier:Number($('weaponTier').value)}})});renderArsenal(reply.state);}catch(error){$('arsenalStatus').textContent=error.message;}finally{button.disabled=false;}});
