import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { initialScene,normalizeBackground,normalizeShip,resolveSceneSwap,sampleApproach } from './ship-scene-domain.mjs';

const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
const RECIPE_KEY='myr5-recipe-v1';
const recipe=()=>{try{return JSON.parse(localStorage.getItem(RECIPE_KEY)||'{}')}catch{return{}}};
const SHIP_SETTINGS_KEY='myr5-ship-customization-v1';
const savedShip=owner=>{try{return JSON.parse(localStorage.getItem(`${SHIP_SETTINGS_KEY}/${owner}`)||'{}')}catch{return{}}};
function disposeModel(root){const geometries=new Set(),materials=new Set(),textures=new Set();root?.traverse(node=>{if(node.geometry)geometries.add(node.geometry);for(const mat of Array.isArray(node.material)?node.material:[node.material])if(mat){materials.add(mat);for(const value of Object.values(mat))if(value?.isTexture)textures.add(value);}});for(const t of textures){t.source?.data?.close?.();t.dispose();}for(const m of materials)m.dispose();for(const g of geometries)g.dispose();}

/** Mount the coach-arrival scene. `assetBridge` must come from signed, owned, verified chunk data, or with
 * `starter` serve Original MYR5's bundled starter ship from /pod/worlds/starter/ (no owner needed; never marks a reveal seen). */
export function mountShipScene({host=document.getElementById('view'),customizer='/creature/index.html',assetBridge,ship:initialShip,starter=false}={}){
 if(!host||!assetBridge?.getShipUrl||!assetBridge?.getBackgroundUrl)throw new Error('A verified owned ship section is required.');
 const ownerId=globalThis.myr5AuthenticatedAccount?.user?.id;if(!ownerId&&!starter)throw new Error('An authenticated ship owner is required.');
 const lifecycle=new AbortController();
 const assertLive=()=>{if(lifecycle.signal.aborted||globalThis.myr5AuthenticatedAccount?.user?.id!==ownerId)throw new DOMException('Ship scene cancelled','AbortError');assetBridge.ownedShipIds();};
 const pause=ms=>new Promise((resolve,reject)=>{assertLive();const cancelled=()=>{clearTimeout(timer);reject(new DOMException('Ship scene cancelled','AbortError'));},timer=setTimeout(()=>{lifecycle.signal.removeEventListener('abort',cancelled);try{assertLive();resolve();}catch(error){reject(error);}},ms);lifecycle.signal.addEventListener('abort',cancelled,{once:true});});
 const ownedShips=assetBridge.ownedShipIds?.()||[];if(!ownedShips.length)throw new Error('No owned ship is available for the arrival scene.');
 if(host.querySelector(':scope > .ship-scene'))return window.myr5ShipScene||null;
 const root=document.createElement('section');root.className='ship-scene';root.setAttribute('aria-label','Coach arrival');
 root.innerHTML='<div class="ship-scene-background" aria-hidden="true"></div><div class="ship-scene-vignette" aria-hidden="true"></div><div class="ship-scene-beam" aria-hidden="true"></div><canvas class="ship-scene-canvas" tabindex="0" role="button" aria-label="Customize this coach"></canvas><p class="ship-scene-status" role="status">Preparing coach arrival…</p>';
 host.prepend(root);host.classList.add('ship-intro-conceals-coach');
 const backgroundEl=root.querySelector('.ship-scene-background'),beam=root.querySelector('.ship-scene-beam'),canvas=root.querySelector('canvas'),status=root.querySelector('.ship-scene-status');
 const flash=document.createElement('div');flash.className='ship-scene-flash';flash.setAttribute('aria-hidden','true');document.body.append(flash);
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.1,100);let renderer;
 try{renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:'high-performance'});}catch(error){host.classList.remove('ship-intro-conceals-coach');root.remove();flash.remove();assetBridge.dispose?.();throw error;}
 renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;
 camera.position.set(0,.45,7);camera.lookAt(0,.9,0);scene.add(new THREE.HemisphereLight(0xe9d9ff,0x23162d,2.5));
 const key=new THREE.DirectionalLight(0xffefca,4.2);key.position.set(-3,5,4);key.castShadow=true;scene.add(key);const rim=new THREE.DirectionalLight(0xb58cff,3.2);rim.position.set(4,2,-3);scene.add(rim);
 const manager=new THREE.LoadingManager();manager.setURLModifier(url=>{if(!/^(blob:|data:)/.test(url)&&!(starter&&url.startsWith('/pod/worlds/starter/')))throw new Error('Ship assets must be embedded verified bytes');return url;});
 const loader=new GLTFLoader(manager),raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),cache=new Map(),models=new Set(),custom=savedShip(ownerId);let state={...initialScene(recipe()),ship:ownedShips.includes(initialShip)?initialShip:ownedShips.includes(custom.ship)?custom.ship:ownedShips.includes(recipe().coach)?recipe().coach:ownedShips[0]},ship=null,shipMeshes=[],shipEpoch=0,disposed=false,raf=0,approachStart=0,approaching=false,hoverStart=performance.now(),swapChain=Promise.resolve(),shipTint=/^#[0-9a-f]{6}$/i.test(custom.tint||'')?custom.tint:'#ffffff';
 const css=document.createElement('link');css.rel='stylesheet';css.href='/modules/ships/ship-scene.css';document.head.append(css);
 const resize=()=>{const rect=root.getBoundingClientRect(),w=Math.max(1,rect.width),h=Math.max(1,rect.height);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()};
 const observer=new ResizeObserver(resize);observer.observe(root);resize();
 function tintShip(color){shipTint=/^#[0-9a-f]{6}$/i.test(color||'')?color:'#ffffff';for(const mesh of shipMeshes){const mats=Array.isArray(mesh.material)?mesh.material:[mesh.material];for(const material of mats)if(material?.color){material.color.set(shipTint);material.needsUpdate=true;}}}
 async function loadShip(id){assertLive();id=normalizeShip(id);const epoch=++shipEpoch;status.textContent=`Loading ${id} ship…`;let source=cache.get(id);if(!source){source=loader.loadAsync(assetBridge.getShipUrl(id)).then(gltf=>{if(disposed){disposeModel(gltf.scene);throw new DOMException('Ship scene cancelled','AbortError');}const box=new THREE.Box3().setFromObject(gltf.scene),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),normalized=new THREE.Group();gltf.scene.position.sub(center);normalized.add(gltf.scene);normalized.scale.setScalar(2.25/(Math.max(size.x,size.y,size.z)||1));models.add(normalized);return normalized;}).catch(error=>{cache.delete(id);throw error;});cache.set(id,source)}const loaded=await source;assertLive();if(epoch!==shipEpoch)return false;if(ship)scene.remove(ship);ship=new THREE.Group();ship.add(loaded.clone(true));ship.position.set(0,1.82,0);ship.rotation.set(.08,-.32,0);scene.add(ship);shipMeshes=[];ship.traverse(o=>{if(o.isMesh)shipMeshes.push(o)});tintShip(shipTint);state=resolveSceneSwap(state,{ship:id});root.dataset.ship=id;status.textContent='Ship ready.';return true;}
 function setBackground(id){id=normalizeBackground(id);backgroundEl.style.backgroundImage=`url("${assetBridge.getBackgroundUrl(id)}")`;root.dataset.background=id;state=resolveSceneSwap(state,{background:id});return id}
 function setCoach(coach){state=resolveSceneSwap(state,{coach});root.dataset.coach=typeof coach==='string'?coach:'recipe';if(coach&&typeof coach==='object')window.dispatchEvent(new CustomEvent('myr5:recipe',{detail:coach}));window.dispatchEvent(new CustomEvent('myr5:coach-scene-swap',{detail:{coach}}));return coach}
 async function ensureCoach(){if(!document.querySelector('.myr5-companion-card'))try{await import('/creature/assets/phone.js')}catch(error){console.warn('Coach viewer unavailable',error)}assertLive();const started=performance.now();while(!document.querySelector('.myr5-companion-card')&&performance.now()-started<8000)await pause(50);if(!document.querySelector('.myr5-companion-card'))throw new Error('Coach viewer did not become ready');}
 async function flashTransition(change){assertLive();flash.setAttribute('popover','manual');try{flash.showPopover?.();}catch{}flash.classList.add('is-on');window.dispatchEvent(new CustomEvent('myr5:portal-transition',{detail:{phase:'flash',duration:reduced()?112:732,source:'coach-scene'}}));try{await pause(16);await pause(reduced()?40:340);await change();assertLive();host.classList.remove('ship-intro-conceals-coach');host.classList.add('ship-intro-revealed');await pause(16);flash.classList.remove('is-on');await pause(reduced()?40:360);assertLive();window.dispatchEvent(new CustomEvent('myr5:portal-transition',{detail:{phase:'complete',source:'coach-scene'}}));}finally{flash.classList.remove('is-on');try{flash.hidePopover?.();}catch{}}}
 function ready(revealComplete=false){assertLive();window.dispatchEvent(new CustomEvent('myr5:ship-scene-ready',{detail:{...state,revealComplete:revealComplete&&!starter,ownerId,starter}}))}
 async function revealShip(id=state.ship,coach=state.coach){assertLive();if(!assetBridge.ownedShipIds().includes(normalizeShip(id)))throw new Error('ship is not owned');state=resolveSceneSwap(state,{ship:id,coach});setBackground(state.background);const loaded=await Promise.all([loadShip(state.ship),ensureCoach()]);assertLive();if(!loaded[0])return false;if(!reduced()){approaching=true;approachStart=performance.now();beam.classList.add('is-charging');await pause(1900);beam.classList.add('is-open');await pause(450);}await flashTransition(async()=>{beam.classList.remove('is-open','is-charging');setCoach(coach)});status.textContent='Coach ready. Select the ship to customize.';ready(true);return true}
 async function swap(next={},options={}){swapChain=swapChain.catch(()=>{}).then(async()=>{assertLive();const target=resolveSceneSwap(state,next);if(!assetBridge.ownedShipIds().includes(target.ship))throw new Error('ship is not owned');const change=async()=>{if(target.ship!==state.ship&&!await loadShip(target.ship))throw new Error('Ship changed while loading');assertLive();if(target.background!==state.background)setBackground(target.background);if(target.coach!==state.coach)setCoach(target.coach);state=target};if(options.flash===false)await change();else await flashTransition(change);ready(false);return state});return swapChain}
 async function play(){return revealShip(state.ship,state.coach)}
 function hit(event){if(!ship)return false;const rect=canvas.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-((event.clientY-rect.top)/rect.height*2-1));raycaster.setFromCamera(pointer,camera);return raycaster.intersectObjects(shipMeshes,false).length>0}
 const openCustomizer=()=>location.assign(customizer);canvas.addEventListener('pointermove',e=>canvas.classList.toggle('is-over-ship',hit(e)));canvas.addEventListener('pointerleave',()=>canvas.classList.remove('is-over-ship'));canvas.addEventListener('click',e=>{if(hit(e))openCustomizer()});canvas.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openCustomizer()}});
 function tick(now){if(disposed)return;if(ship){if(reduced()){approaching=false;ship.position.set(0,1.82,0);ship.scale.setScalar(1);ship.rotation.set(.08,-.32,0);}else if(approaching){const p=sampleApproach(now-approachStart);ship.position.set(p.x,p.y,p.z);ship.scale.setScalar(p.scale);ship.rotation.z=p.roll;if(p.done){approaching=false;hoverStart=now;ship.rotation.z=0}}else{ship.position.y=1.82+Math.sin((now-hoverStart)/820)*.07;ship.rotation.y=-.32+Math.sin((now-hoverStart)/1700)*.055}}renderer.render(scene,camera);raf=requestAnimationFrame(tick)}raf=requestAnimationFrame(tick);
 const failed=error=>{if(!disposed){status.textContent='Ship unavailable. Your coach is still ready.';host.classList.remove('ship-intro-conceals-coach');beam.classList.remove('is-open','is-charging');}if(error?.name!=='AbortError')console.warn('Coach ship unavailable',error);};
 const storage=e=>{if(e.key===RECIPE_KEY&&e.newValue)try{const next=initialScene(JSON.parse(e.newValue));void swap(next).catch(failed)}catch{}};
 const recolor=e=>{if(e.detail?.ownerId!==ownerId)return;if(e.detail.ship===state.ship)tintShip(e.detail.tint);else if(assetBridge.ownedShipIds().includes(e.detail.ship))void swap({ship:e.detail.ship},{flash:false}).then(()=>tintShip(e.detail.tint)).catch(failed);};
 const accountChanged=()=>{if(globalThis.myr5AuthenticatedAccount?.user?.id!==ownerId)api.dispose();};
 window.addEventListener('storage',storage);window.addEventListener('myr5:ship-customization',recolor);window.addEventListener('myr5:account-ready',accountChanged);window.addEventListener('myr5:account-cleared',accountChanged);
 const api={get state(){return{...state}},swap,setShip:ship=>swap({ship},{flash:false}),setBackground:background=>swap({background},{flash:false}),setCoach:coach=>swap({coach},{flash:false}),setShipTint:tint=>{assertLive();tintShip(tint)},play,reveal:revealShip,openCustomizer,dispose(){if(disposed)return;disposed=true;lifecycle.abort();++shipEpoch;cancelAnimationFrame(raf);observer.disconnect();window.removeEventListener('storage',storage);window.removeEventListener('myr5:ship-customization',recolor);window.removeEventListener('myr5:account-ready',accountChanged);window.removeEventListener('myr5:account-cleared',accountChanged);window.removeEventListener('pagehide',pagehide);for(const model of models)disposeModel(model);models.clear();cache.clear();renderer.dispose();renderer.forceContextLoss();flash.remove();root.remove();css.remove();host.classList.remove('ship-intro-conceals-coach','ship-intro-revealed');assetBridge.dispose?.();if(window.myr5ShipScene===api)delete window.myr5ShipScene;}};
 const pagehide=()=>api.dispose();window.addEventListener('pagehide',pagehide);
 window.myr5ShipScene=api;api.ready=revealShip(state.ship,state.coach).catch(error=>{failed(error);return false;});return api;
}
